import { createHash } from 'node:crypto';
import pg from 'pg';
import { DRAFT_IPX_PLTR_POLICY_VERSION, type DraftVerdict, type HypotheticalIpxConfiguration, type PreflightSimulationRecord, type RiskDimension, type RiskStatus, type IpxPltrSimulationStore, IpxPltrPreflightSimulatorService, IpxPltrSimulationError } from './ipxPltrPreflightSimulatorService';
import type { PltrPreflightState } from './rhChainPltrPreflightService';
import { resolvePostgresPool, RetryablePostgresSchema, type PostgresPoolSource } from '../persistence/retryablePostgresSchema';

/**
 * v0.5.1 is an append-only, read-only research layer. It deliberately has no
 * wallet, signer, router, deployment, reserve, purchase, or transaction API.
 */
export const IPX_PLTR_SHADOW_LAB_VERSION = 'ipx-pltr-shadow-preflight-v0.5.1';
export const MARKET_CAPACITY_GRID_VERSION = 'IPX_PLTR_MARKET_CAPACITY_GRID_V1';
export const RANGE_WIDTH_RULES_VERSION = 'IPX_PLTR_RANGE_WIDTH_RULES_V1';
export const SHADOW_MINIMUM_EVIDENCE_POLICY = { version: 'IPX_PLTR_SHADOW_EVIDENCE_WINDOW_V1', target_calendar_days: [7, 14], minimum_ready_snapshots: 7, grants_launch_authorization: false } as const;
export type CandidateName = 'CANDIDATE_NATIVE_V1' | 'CANDIDATE_ANCHOR_V1' | 'CANDIDATE_RESERVE_ANCHOR_V1';
export type BasisRegime = 'NEAR_PAR' | 'MODERATE_PREMIUM' | 'MATERIAL_PREMIUM' | 'MODERATE_DISCOUNT' | 'MATERIAL_DISCOUNT';
export type IdentityMarketRobustness = 'ROBUST_UNDER_DRAFT' | 'FRAGILE' | 'SUPPORT_EXHAUSTION_RISK' | 'CONCENTRATION_CONSTRAINED' | 'INSUFFICIENT_DATA';

const common = {
  asset_owner: 'INFOPUNKS' as const, first_party_asset: true as const, ipx_decimals: 18,
  hypothetical_total_supply: '100000000', hypothetical_circulating_supply_at_launch: '10000000', initial_price_pltr_per_ipx: '0.01',
  other_first_party_ipx_linked_pltr_holdings: [], v4_fee: 3000, tick_spacing: 200, hook_configuration: { kind: 'ZERO_HOOK' as const },
  reserve_policy_metadata: { withdrawal_policy_descriptor: 'Illustrative disclosure only; no withdrawals simulated.', custody_descriptor: 'Hypothetical first-party custody state.', acquisition_policy_descriptor: 'No reserve purchase or acquisition cadence is simulated.' },
  reference_trade_notionals_usd: ['1000', '5000', '10000', '25000', '50000', '100000']
};
const position = (pltr: string, ipx: string, tickLower = -60000, tickUpper = -30000) => [{ position_id: 'canonical-wide-range', tick_lower: tickLower, tick_upper: tickUpper, pltr_principal: pltr, ipx_principal: ipx }];
export const PINNED_CANDIDATE_CONFIGURATIONS: Record<CandidateName, HypotheticalIpxConfiguration> = {
  CANDIDATE_NATIVE_V1: { ...common, simulation_name: 'ILLUSTRATIVE ONLY // PLTR NATIVE', architecture: 'PLTR_NATIVE', pltr_allocated_to_ipx_pltr_liquidity: '400', ipx_allocated_to_ipx_pltr_liquidity: '40000', pltr_allocated_to_first_party_reserve: '0', liquidity_positions: position('400', '40000'), hypothetical_usdg_execution_market_exists: false, hypothetical_weth_execution_market_exists: false, hypothetical_capital_allocation_pct: { pltr: '100', usdg: '0', weth: '0' } },
  CANDIDATE_ANCHOR_V1: { ...common, simulation_name: 'ILLUSTRATIVE ONLY // PLTR ANCHOR', architecture: 'PLTR_ANCHOR', pltr_allocated_to_ipx_pltr_liquidity: '250', ipx_allocated_to_ipx_pltr_liquidity: '25000', pltr_allocated_to_first_party_reserve: '0', liquidity_positions: position('250', '25000'), hypothetical_usdg_execution_market_exists: true, hypothetical_weth_execution_market_exists: true, hypothetical_capital_allocation_pct: { pltr: '50', usdg: '30', weth: '20' } },
  CANDIDATE_RESERVE_ANCHOR_V1: { ...common, simulation_name: 'ILLUSTRATIVE ONLY // PLTR RESERVE ANCHOR', architecture: 'PLTR_RESERVE_ANCHOR', pltr_allocated_to_ipx_pltr_liquidity: '100', ipx_allocated_to_ipx_pltr_liquidity: '10000', pltr_allocated_to_first_party_reserve: '300', liquidity_positions: position('100', '10000'), hypothetical_usdg_execution_market_exists: true, hypothetical_weth_execution_market_exists: true, hypothetical_capital_allocation_pct: { pltr: '25', usdg: '45', weth: '30' } }
};

export type PinnedCandidateConfiguration = { record_type: 'PINNED_SHADOW_CANDIDATE_CONFIGURATION'; candidate_id: CandidateName; configuration_hash: string; architecture: HypotheticalIpxConfiguration['architecture']; market_parameters: HypotheticalIpxConfiguration; created_at: string; status: 'SHADOW_ONLY'; immutable: true; no_launch_authorization: true };
export type ShadowPreflightRun = { record_type: 'SHADOW_PREFLIGHT_RUN'; shadow_run_id: string; state_snapshot_id: string; configuration_hash: string; simulation_id: string; draft_policy_version: typeof DRAFT_IPX_PLTR_POLICY_VERSION; result: { draft_simulation_verdict: DraftVerdict; market_impact_state: RiskStatus; range_fragility: RiskStatus; identity_market_robustness: IdentityMarketRobustness }; risk_dimensions: RiskDimension[]; timestamp: string; immutable: true; transaction_capability: 'NONE_SIMULATION_ONLY' };
export type ShadowSeriesPoint = { snapshot_time: string; state_snapshot_id: string; pltr_supply: string; pltr_usdg: string; basis_bps: string; basis_regime: BasisRegime; session: string; direct_depth_state: string | null; first_party_concentration_pct: string; market_impact_metrics: { max_absolute_impact_pct: string; support_exhaustion: boolean }; range_fragility: RiskStatus; route_topology_state: string; draft_verdict: DraftVerdict; identity_market_robustness: IdentityMarketRobustness };
export type ShadowTransition = { record_type: 'SHADOW_VERDICT_TRANSITION'; configuration_hash: string; from_state_snapshot_id: string | null; to_state_snapshot_id: string; transition: `${DraftVerdict}_TO_${DraftVerdict}` | 'INITIAL_OBSERVATION'; associated_input_changes: Array<'PLTR_SUPPLY' | 'BASIS' | 'SESSION' | 'DIRECT_DEPTH' | 'FIRST_PARTY_CONCENTRATION' | 'MARKET_IMPACT' | 'RANGE_RISK' | 'ROUTE_TOPOLOGY'>; deltas: Record<string, string | boolean | null>; causal_interpretation: 'NOT_ASSERTED'; immutable: true };
export type MarketImpactCurvePoint = { notional_usd: string; impact_pct: string; ending_price_pltr_per_ipx: string; range_state: 'ACTIVE' | 'EXHAUSTED'; support_exhausted: boolean; pltr_delta: string; ipx_delta: string };
export type IdentityMarketEfficiency = { label: 'IDENTITY_MARKET_EFFICIENCY'; usable_capacity_usd_per_pltr_concentration_pct: string | null; numerator: 'MODELED_USABLE_CAPACITY_USD'; denominator: 'FIRST_PARTY_PLTR_CONCENTRATION_PCT'; interpretation: 'DESCRIPTIVE_SHADOW_METRIC_NOT_TOKEN_SCORE_OR_RECOMMENDATION' };
export type CapacityFrontierObservation = { record_type: 'CAPACITY_FRONTIER_OBSERVATION'; state_snapshot_id: string; architecture: HypotheticalIpxConfiguration['architecture']; pltr_lp_principal: string; reserve_principal: string; range_family: RangeFamily; first_party_pltr_concentration_pct: string; modeled_usable_market_capacity_usd: string; identity_market_efficiency: IdentityMarketEfficiency; market_impact_characteristics: { maximum_absolute_impact_pct: string; support_exhaustion: boolean }; research_only: true };
export type RangeFamily = 'NARROW' | 'MEDIUM' | 'WIDE' | 'VERY_WIDE';
export type MarketCapacitySweep = { record_type: 'MARKET_CAPACITY_SWEEP'; sweep_id: string; state_snapshot_id: string; grid_version: typeof MARKET_CAPACITY_GRID_VERSION; range_rules_version: typeof RANGE_WIDTH_RULES_VERSION; created_at: string; immutable: true; research_only: true; not_an_optimizer: true; no_launch_authorization: true; scenarios: Array<{ scenario_id: string; pltr_lp_principal: string; range_family: RangeFamily; supply_growth: 'CURRENT' | '+10%' | '+25%' | '+50%' | '+100%'; direct_market_depth_growth: 'CONSTANT' | '+25%' | '+50%' | '+100%'; rejected: boolean; rejection_reason: string | null; principal_requirements: { pltr: string; ipx: string }; active_liquidity: string; buy_impact_curve: MarketImpactCurvePoint[]; sell_impact_curve: MarketImpactCurvePoint[]; modeled_usable_capacity_usd: string; support_exhaustion: boolean; one_sided_transition: boolean; capital_efficiency: string; identity_market_efficiency: IdentityMarketEfficiency; first_party_concentration_pct: string; identity_market_robustness: IdentityMarketRobustness; capital_anchor_flow_test: Array<{ pltr_flow_share_pct: 100 | 75 | 50 | 25 | 10; canonical_identity_market_preserved: boolean; inferred_liquidity_migration: false }>; frontier: CapacityFrontierObservation }>; };

export interface IpxPltrShadowLabStore { createCandidate(record: PinnedCandidateConfiguration): Promise<PinnedCandidateConfiguration>; listCandidates(): Promise<PinnedCandidateConfiguration[]>; createRun(record: ShadowPreflightRun): Promise<ShadowPreflightRun>; listRuns(configurationHash?: string): Promise<ShadowPreflightRun[]>; createSweep(record: MarketCapacitySweep): Promise<MarketCapacitySweep>; getSweep(id: string): Promise<MarketCapacitySweep | null>; }
export class InMemoryIpxPltrShadowLabStore implements IpxPltrShadowLabStore {
  private candidates = new Map<string, PinnedCandidateConfiguration>(); private runs = new Map<string, ShadowPreflightRun>(); private sweeps = new Map<string, MarketCapacitySweep>();
  async createCandidate(record: PinnedCandidateConfiguration) { const old = this.candidates.get(record.configuration_hash); if (old && canonical(old) !== canonical(record)) throw new IpxPltrSimulationError('SIMULATION_RECORD_CONFLICT'); this.candidates.set(record.configuration_hash, clone(old ?? record)); return clone(old ?? record); }
  async listCandidates() { return [...this.candidates.values()].sort((a, b) => a.candidate_id.localeCompare(b.candidate_id)).map(clone); }
  async createRun(record: ShadowPreflightRun) { const old = this.runs.get(record.shadow_run_id); if (old && canonical(old) !== canonical(record)) throw new IpxPltrSimulationError('SIMULATION_RECORD_CONFLICT'); this.runs.set(record.shadow_run_id, clone(old ?? record)); return clone(old ?? record); }
  async listRuns(hash?: string) { return [...this.runs.values()].filter((run) => !hash || run.configuration_hash === hash).sort((a, b) => a.timestamp.localeCompare(b.timestamp) || a.shadow_run_id.localeCompare(b.shadow_run_id)).map(clone); }
  async createSweep(record: MarketCapacitySweep) { const old = this.sweeps.get(record.sweep_id); if (old && canonical(old) !== canonical(record)) throw new IpxPltrSimulationError('SIMULATION_RECORD_CONFLICT'); this.sweeps.set(record.sweep_id, clone(old ?? record)); return clone(old ?? record); }
  async getSweep(id: string) { const record = this.sweeps.get(id); return record ? clone(record) : null; }
}
export class PostgresIpxPltrShadowLabStore implements IpxPltrShadowLabStore {
  private readonly pool: pg.Pool; private readonly ownsPool: boolean; private readonly schema = new RetryablePostgresSchema('ipx_pltr_shadow_lab');
  constructor(source: PostgresPoolSource) { const resolved = resolvePostgresPool(source); this.pool = resolved.pool; this.ownsPool = resolved.ownsPool; }
  private ensure() { return this.schema.ensure(this.pool, "create table if not exists ipx_pltr_shadow_candidates (configuration_hash text primary key, candidate_id text not null, payload jsonb not null); create table if not exists ipx_pltr_shadow_runs (shadow_run_id text primary key, configuration_hash text not null, timestamp timestamptz not null, payload jsonb not null); create index if not exists ipx_pltr_shadow_runs_configuration_idx on ipx_pltr_shadow_runs (configuration_hash, timestamp); create table if not exists ipx_pltr_capacity_sweeps (sweep_id text primary key, state_snapshot_id text not null, payload jsonb not null);"); }
  async createCandidate(record: PinnedCandidateConfiguration) { await this.ensure(); await this.pool.query('insert into ipx_pltr_shadow_candidates (configuration_hash,candidate_id,payload) values ($1,$2,$3::jsonb) on conflict (configuration_hash) do nothing', [record.configuration_hash, record.candidate_id, JSON.stringify(record)]); const existing = (await this.pool.query<{ payload: PinnedCandidateConfiguration }>('select payload from ipx_pltr_shadow_candidates where configuration_hash=$1', [record.configuration_hash])).rows[0]?.payload; if (!existing || canonical(existing) !== canonical(record)) throw new IpxPltrSimulationError('SIMULATION_RECORD_CONFLICT'); return clone(existing); }
  async listCandidates() { await this.ensure(); return (await this.pool.query<{ payload: PinnedCandidateConfiguration }>('select payload from ipx_pltr_shadow_candidates order by candidate_id')).rows.map((row) => clone(row.payload)); }
  async createRun(record: ShadowPreflightRun) { await this.ensure(); await this.pool.query('insert into ipx_pltr_shadow_runs (shadow_run_id,configuration_hash,timestamp,payload) values ($1,$2,$3,$4::jsonb) on conflict (shadow_run_id) do nothing', [record.shadow_run_id, record.configuration_hash, record.timestamp, JSON.stringify(record)]); const existing = (await this.pool.query<{ payload: ShadowPreflightRun }>('select payload from ipx_pltr_shadow_runs where shadow_run_id=$1', [record.shadow_run_id])).rows[0]?.payload; if (!existing || canonical(existing) !== canonical(record)) throw new IpxPltrSimulationError('SIMULATION_RECORD_CONFLICT'); return clone(existing); }
  async listRuns(configurationHash?: string) { await this.ensure(); const result = configurationHash ? await this.pool.query<{ payload: ShadowPreflightRun }>('select payload from ipx_pltr_shadow_runs where configuration_hash=$1 order by timestamp,shadow_run_id', [configurationHash]) : await this.pool.query<{ payload: ShadowPreflightRun }>('select payload from ipx_pltr_shadow_runs order by timestamp,shadow_run_id'); return result.rows.map((row) => clone(row.payload)); }
  async createSweep(record: MarketCapacitySweep) { await this.ensure(); await this.pool.query('insert into ipx_pltr_capacity_sweeps (sweep_id,state_snapshot_id,payload) values ($1,$2,$3::jsonb) on conflict (sweep_id) do nothing', [record.sweep_id, record.state_snapshot_id, JSON.stringify(record)]); const existing = await this.getSweep(record.sweep_id); if (!existing || canonical(existing) !== canonical(record)) throw new IpxPltrSimulationError('SIMULATION_RECORD_CONFLICT'); return existing; }
  async getSweep(id: string) { await this.ensure(); const result = await this.pool.query<{ payload: MarketCapacitySweep }>('select payload from ipx_pltr_capacity_sweeps where sweep_id=$1', [id]); return result.rows[0] ? clone(result.rows[0].payload) : null; }
  async close() { if (this.ownsPool) await this.pool.end(); }
}

function canonical(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; if (value && typeof value === 'object') return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(',')}}`; return JSON.stringify(value); }
function hash(value: unknown) { return createHash('sha256').update(canonical(value)).digest('hex'); }
function clone<T>(value: T): T { return structuredClone(value); }
function maxImpact(record: PreflightSimulationRecord) { return Math.max(...[...record.result.trade_impact.buys, ...record.result.trade_impact.sells].map((item) => Math.abs(Number(item.price_impact_pct)))); }
export function basisRegime(basis: number): BasisRegime { return basis >= 200 ? 'MATERIAL_PREMIUM' : basis >= 50 ? 'MODERATE_PREMIUM' : basis <= -200 ? 'MATERIAL_DISCOUNT' : basis <= -50 ? 'MODERATE_DISCOUNT' : 'NEAR_PAR'; }
export function identityMarketRobustness(record: PreflightSimulationRecord): IdentityMarketRobustness { const risk = new Map(record.result.risk_dimensions.map((item) => [item.dimension, item.status])); if (risk.get('MISSION_INVENTORY_UNCERTAINTY') === 'UNAVAILABLE') return 'INSUFFICIENT_DATA'; if (risk.get('MARKET_IMPACT') === 'FAIL') return 'SUPPORT_EXHAUSTION_RISK'; if (risk.get('PLTR_CONCENTRATION') === 'FAIL') return 'CONCENTRATION_CONSTRAINED'; return record.result.draft_simulation_verdict.verdict === 'ALLOW' ? 'ROBUST_UNDER_DRAFT' : 'FRAGILE'; }
function point(record: PreflightSimulationRecord, direction: 'buys' | 'sells') { return record.result.trade_impact[direction].map((trade) => ({ notional_usd: trade.notional_usd, impact_pct: trade.price_impact_pct, ending_price_pltr_per_ipx: trade.ending_price_pltr_per_ipx, range_state: trade.range_exhausted ? 'EXHAUSTED' as const : 'ACTIVE' as const, support_exhausted: trade.exceeds_modeled_market_support, pltr_delta: trade.pltr_principal_change, ipx_delta: trade.ipx_principal_change })); }
function usableCapacity(record: PreflightSimulationRecord, boundary = 10) { const paired = record.result.trade_impact.buys.map((buy, index) => [buy, record.result.trade_impact.sells[index]] as const); const valid = paired.filter(([buy, sell]) => !buy.exceeds_modeled_market_support && !sell.exceeds_modeled_market_support && Math.max(Math.abs(Number(buy.price_impact_pct)), Math.abs(Number(sell.price_impact_pct))) <= boundary); return valid.at(-1)?.[0].notional_usd ?? '0'; }
function identityMarketEfficiency(capacity: string, concentrationPct: string): IdentityMarketEfficiency { const denominator = Number(concentrationPct); return { label: 'IDENTITY_MARKET_EFFICIENCY', usable_capacity_usd_per_pltr_concentration_pct: denominator > 0 ? (Number(capacity) / denominator).toFixed(2) : null, numerator: 'MODELED_USABLE_CAPACITY_USD', denominator: 'FIRST_PARTY_PLTR_CONCENTRATION_PCT', interpretation: 'DESCRIPTIVE_SHADOW_METRIC_NOT_TOKEN_SCORE_OR_RECOMMENDATION' }; }
function rangeTicks(family: RangeFamily) { return ({ NARROW: [-42000, -40000], MEDIUM: [-48000, -38000], WIDE: [-60000, -30000], VERY_WIDE: [-80000, -20000] } as const)[family]; }
function configurationForSweep(base: HypotheticalIpxConfiguration, pltr: string, family: RangeFamily): HypotheticalIpxConfiguration { const lp = Number(pltr); const ipx = String(lp * 100); const [lower, upper] = rangeTicks(family); return { ...base, simulation_name: `RESEARCH ONLY // ${base.architecture} // ${family} // ${pltr} PLTR`, pltr_allocated_to_ipx_pltr_liquidity: pltr, ipx_allocated_to_ipx_pltr_liquidity: ipx, liquidity_positions: position(pltr, ipx, lower, upper) }; }

export class IpxPltrShadowLabService {
  constructor(private readonly snapshotById: (id: string) => Promise<PltrPreflightState | null>, private readonly simulatorStore: IpxPltrSimulationStore, private readonly store: IpxPltrShadowLabStore = new InMemoryIpxPltrShadowLabStore()) {}
  private simulator() { return new IpxPltrPreflightSimulatorService(this.snapshotById, this.simulatorStore); }
  async pinCandidates(createdAt = '2026-09-02T07:45:09.000Z') { const records = await Promise.all((Object.entries(PINNED_CANDIDATE_CONFIGURATIONS) as [CandidateName, HypotheticalIpxConfiguration][]).map(([candidate_id, market_parameters]) => this.store.createCandidate({ record_type: 'PINNED_SHADOW_CANDIDATE_CONFIGURATION', candidate_id, configuration_hash: `sha256:${hash(market_parameters)}`, architecture: market_parameters.architecture, market_parameters: clone(market_parameters), created_at: createdAt, status: 'SHADOW_ONLY', immutable: true, no_launch_authorization: true }))); return records.sort((a, b) => a.candidate_id.localeCompare(b.candidate_id)); }
  async candidates() { const records = await this.store.listCandidates(); return records.length ? records : this.pinCandidates(); }
  async replay(stateSnapshotId: string) {
    if (!stateSnapshotId || stateSnapshotId.toLowerCase() === 'latest') throw new IpxPltrSimulationError(!stateSnapshotId ? 'EXPLICIT_SNAPSHOT_REQUIRED' : 'LATEST_NOT_ALLOWED');
    const snapshot = await this.snapshotById(stateSnapshotId); if (!snapshot || snapshot.observation_id !== stateSnapshotId) throw new IpxPltrSimulationError('STATE_SNAPSHOT_NOT_FOUND'); if (!snapshot.immutable || snapshot.readiness.status !== 'READY_FOR_SIMULATION') throw new IpxPltrSimulationError('STATE_NOT_READY');
    const candidates = await this.candidates(); const simulator = this.simulator();
    return Promise.all(candidates.map(async (candidate) => { const simulation = await simulator.simulate({ state_snapshot_id: stateSnapshotId, hypothetical_configuration: candidate.market_parameters }); const marketImpact = simulation.result.risk_dimensions.find((risk) => risk.dimension === 'MARKET_IMPACT')!.status; const range = simulation.result.risk_dimensions.find((risk) => risk.dimension === 'RANGE_FRAGILITY')!.status; const record: ShadowPreflightRun = { record_type: 'SHADOW_PREFLIGHT_RUN', shadow_run_id: `shadow-${hash({ stateSnapshotId, configuration_hash: candidate.configuration_hash, simulation_id: simulation.simulation_id })}`, state_snapshot_id: stateSnapshotId, configuration_hash: candidate.configuration_hash, simulation_id: simulation.simulation_id, draft_policy_version: DRAFT_IPX_PLTR_POLICY_VERSION, result: { draft_simulation_verdict: simulation.result.draft_simulation_verdict.verdict, market_impact_state: marketImpact, range_fragility: range, identity_market_robustness: identityMarketRobustness(simulation) }, risk_dimensions: clone(simulation.result.risk_dimensions), timestamp: snapshot.observation!.observed_at, immutable: true, transaction_capability: 'NONE_SIMULATION_ONLY' }; return this.store.createRun(record); }));
  }
  async series(configurationHash: string) { const runs = await this.store.listRuns(configurationHash); const output: ShadowSeriesPoint[] = []; for (const run of runs) { const simulation = await this.simulatorStore.get(run.simulation_id); if (!simulation) continue; const state = simulation.result.state_snapshot; output.push({ snapshot_time: state.observed_at, state_snapshot_id: state.observation_id, pltr_supply: state.canonical_pltr_total_supply, pltr_usdg: state.direct_pltr_usdg_price, basis_bps: state.basis_bps, basis_regime: basisRegime(Number(state.basis_bps)), session: state.session, direct_depth_state: state.direct_market_depth_state, first_party_concentration_pct: simulation.result.first_party_pltr_footprint.canonical_supply_pct, market_impact_metrics: { max_absolute_impact_pct: String(maxImpact(simulation)), support_exhaustion: [...simulation.result.trade_impact.buys, ...simulation.result.trade_impact.sells].some((trade) => trade.exceeds_modeled_market_support) }, range_fragility: run.result.range_fragility, route_topology_state: simulation.result.route_migration.length ? 'MULTI_ROUTE_HYPOTHETICAL' : 'PLTR_ONLY_HYPOTHETICAL', draft_verdict: run.result.draft_simulation_verdict, identity_market_robustness: run.result.identity_market_robustness }); } return output;
  }
  async transitions(configurationHash: string) { const rows = await this.series(configurationHash); return rows.map((current, index): ShadowTransition => { const prior = rows[index - 1]; const changes: ShadowTransition['associated_input_changes'] = []; const delta = (a: string, b: string) => String(Number(a) - Number(b)); if (prior) { if (current.pltr_supply !== prior.pltr_supply) changes.push('PLTR_SUPPLY'); if (current.basis_bps !== prior.basis_bps) changes.push('BASIS'); if (current.session !== prior.session) changes.push('SESSION'); if (current.direct_depth_state !== prior.direct_depth_state) changes.push('DIRECT_DEPTH'); if (current.first_party_concentration_pct !== prior.first_party_concentration_pct) changes.push('FIRST_PARTY_CONCENTRATION'); if (current.market_impact_metrics.max_absolute_impact_pct !== prior.market_impact_metrics.max_absolute_impact_pct) changes.push('MARKET_IMPACT'); if (current.range_fragility !== prior.range_fragility) changes.push('RANGE_RISK'); if (current.route_topology_state !== prior.route_topology_state) changes.push('ROUTE_TOPOLOGY'); }
      return { record_type: 'SHADOW_VERDICT_TRANSITION', configuration_hash: configurationHash, from_state_snapshot_id: prior?.state_snapshot_id ?? null, to_state_snapshot_id: current.state_snapshot_id, transition: prior ? `${prior.draft_verdict}_TO_${current.draft_verdict}` : 'INITIAL_OBSERVATION', associated_input_changes: changes, deltas: prior ? { pltr_supply_delta: delta(current.pltr_supply, prior.pltr_supply), basis_delta_bps: delta(current.basis_bps, prior.basis_bps), session_changed: current.session !== prior.session, direct_depth_delta: current.direct_depth_state && prior.direct_depth_state ? delta(current.direct_depth_state, prior.direct_depth_state) : null, concentration_delta_pct: delta(current.first_party_concentration_pct, prior.first_party_concentration_pct), market_impact_delta_pct: delta(current.market_impact_metrics.max_absolute_impact_pct, prior.market_impact_metrics.max_absolute_impact_pct), range_risk_changed: current.range_fragility !== prior.range_fragility } : {}, causal_interpretation: 'NOT_ASSERTED', immutable: true };
    });
  }
  async summary(configurationHash: string) { const series = await this.series(configurationHash); const counts = { ALLOW: 0, DEGRADE: 0, BLOCK: 0 }; series.forEach((row) => { counts[row.draft_verdict] += 1; }); const impacts = series.map((row) => Number(row.market_impact_metrics.max_absolute_impact_pct)); return { configuration_hash: configurationHash, ready_snapshot_count: series.length, verdict_counts: counts, support_exhaustion_frequency: series.filter((row) => row.market_impact_metrics.support_exhaustion).length, market_impact: impacts.length ? { median: [...impacts].sort((a, b) => a - b)[Math.floor(impacts.length / 2)], range: [Math.min(...impacts), Math.max(...impacts)] } : null, concentration_range: series.length ? [Math.min(...series.map((row) => Number(row.first_party_concentration_pct))), Math.max(...series.map((row) => Number(row.first_party_concentration_pct)))] : null, basis_range_bps: series.length ? [Math.min(...series.map((row) => Number(row.basis_bps))), Math.max(...series.map((row) => Number(row.basis_bps)))] : null, session_composition: Object.fromEntries(['OPEN', 'CLOSED', 'WEEKEND', 'HOLIDAY'].map((session) => [session, series.filter((row) => row.session === session).length])), risk_dimension_frequency: Object.fromEntries(['PASS', 'WARN', 'FAIL', 'UNAVAILABLE'].map((status) => [status, 0])), evidence_window: { ...SHADOW_MINIMUM_EVIDENCE_POLICY, status: series.length >= SHADOW_MINIMUM_EVIDENCE_POLICY.minimum_ready_snapshots ? 'MINIMUM_N_REACHED' : 'SHADOW_WINDOW_INSUFFICIENT' }, profitability_statistics: 'NOT_OUTPUT' as const, launch_authorization: false };
  }
  async capacitySweep(stateSnapshotId: string, baseCandidate: CandidateName = 'CANDIDATE_ANCHOR_V1') {
    const snapshot = await this.snapshotById(stateSnapshotId); if (!snapshot || snapshot.observation_id !== stateSnapshotId) throw new IpxPltrSimulationError('STATE_SNAPSHOT_NOT_FOUND'); if (!snapshot.immutable || snapshot.readiness.status !== 'READY_FOR_SIMULATION' || !snapshot.observation) throw new IpxPltrSimulationError('STATE_NOT_READY'); const base = PINNED_CANDIDATE_CONFIGURATIONS[baseCandidate]; const supply = Number(snapshot.observation.total_supply_units); const grid = ['50', '100', '250', '500', '750', '1000', '1500']; const simulator = this.simulator(); const scenarios: MarketCapacitySweep['scenarios'] = [];
    for (const pltr of grid) for (const range_family of ['NARROW', 'MEDIUM', 'WIDE', 'VERY_WIDE'] as RangeFamily[]) for (const supply_growth of ['CURRENT', '+10%', '+25%', '+50%', '+100%'] as const) for (const direct_market_depth_growth of ['CONSTANT', '+25%', '+50%', '+100%'] as const) {
      const rejected = Number(pltr) > supply; const config = configurationForSweep(base, pltr, range_family); let record: PreflightSimulationRecord | null = null; if (!rejected) record = await simulator.simulate({ state_snapshot_id: stateSnapshotId, hypothetical_configuration: config }); const concentration = record ? record.result.supply_stress.find((row) => row.scenario === supply_growth)?.first_party_concentration_pct ?? record.result.first_party_pltr_footprint.canonical_supply_pct : '0'; const max = record ? String(maxImpact(record)) : '0'; const support = record ? [...record.result.trade_impact.buys, ...record.result.trade_impact.sells].some((trade) => trade.exceeds_modeled_market_support) : true; const capacity = record ? usableCapacity(record) : '0'; const ime = identityMarketEfficiency(capacity, concentration); const frontier: CapacityFrontierObservation = { record_type: 'CAPACITY_FRONTIER_OBSERVATION', state_snapshot_id: stateSnapshotId, architecture: base.architecture, pltr_lp_principal: pltr, reserve_principal: config.pltr_allocated_to_first_party_reserve, range_family, first_party_pltr_concentration_pct: concentration, modeled_usable_market_capacity_usd: capacity, identity_market_efficiency: ime, market_impact_characteristics: { maximum_absolute_impact_pct: max, support_exhaustion: support }, research_only: true };
      scenarios.push({ scenario_id: `capacity-${hash({ stateSnapshotId, pltr, range_family, supply_growth, direct_market_depth_growth })}`, pltr_lp_principal: pltr, range_family, supply_growth, direct_market_depth_growth, rejected, rejection_reason: rejected ? 'PROPOSED_PLTR_EXCEEDS_CANONICAL_SNAPSHOT_SUPPLY' : null, principal_requirements: { pltr, ipx: config.ipx_allocated_to_ipx_pltr_liquidity }, active_liquidity: record?.result.market.active_liquidity ?? '0', buy_impact_curve: record ? point(record, 'buys') : [], sell_impact_curve: record ? point(record, 'sells') : [], modeled_usable_capacity_usd: capacity, support_exhaustion: support, one_sided_transition: record ? record.result.range_stress.some((row) => row.active_liquidity === '0') : true, capital_efficiency: record ? String(Number(capacity) / Math.max(1, Number(pltr))) : '0', identity_market_efficiency: ime, first_party_concentration_pct: concentration, identity_market_robustness: record ? identityMarketRobustness(record) : 'INSUFFICIENT_DATA', capital_anchor_flow_test: [100, 75, 50, 25, 10].map((pltr_flow_share_pct) => ({ pltr_flow_share_pct: pltr_flow_share_pct as 100 | 75 | 50 | 25 | 10, canonical_identity_market_preserved: base.architecture === 'PLTR_ANCHOR' && Number(pltr) > 0, inferred_liquidity_migration: false })), frontier });
    }
    const output: MarketCapacitySweep = { record_type: 'MARKET_CAPACITY_SWEEP', sweep_id: `capacity-${hash({ stateSnapshotId, baseCandidate, grid_version: MARKET_CAPACITY_GRID_VERSION, range_rules_version: RANGE_WIDTH_RULES_VERSION })}`, state_snapshot_id: stateSnapshotId, grid_version: MARKET_CAPACITY_GRID_VERSION, range_rules_version: RANGE_WIDTH_RULES_VERSION, created_at: snapshot.observation.observed_at, immutable: true, research_only: true, not_an_optimizer: true, no_launch_authorization: true, scenarios }; return this.store.createSweep(output);
  }
  getSweep(id: string) { return this.store.getSweep(id); }
}
