import { normalizeBlockscoutAddress } from '../providers/blockscoutProvider';
import { REFLEXIVE_CHAIN_ID, formatTokenUnits, type CanonicalStockAsset, type Evidence } from './rhChainReflexiveRadarService';

/** v0.4 deliberately separates a venue's identity proof from its inventory proof. */
export type MissionMarketVenue = 'PAIR' | 'LONG';
export type LongFailure = 'LONG_MARKET_DISCOVERY_ONLY' | 'LONG_FACTORY_UNVERIFIED' | 'QUOTE_NONCANONICAL' | 'POOL_ID_UNRESOLVED' | 'LIQUIDITY_CONTAINER_UNRESOLVED' | 'POSITION_UNRESOLVED' | 'VAULT_INVENTORY_UNAVAILABLE' | 'POOL_STATE_UNAVAILABLE' | 'ARCHIVE_REQUIRED' | 'TEMPORAL_MISMATCH' | 'PARTIAL_MARKET_COVERAGE';
export type LongMarketCandidate = { market_id: string; mission_contract: string; mission_symbol: string; quote_contract: string; quote_symbol: string; pool_id: string | null; source: Evidence; launch_tx: string | null; launch_block: number | null; launch_timestamp: string | null; venue_version: string | null };
export type VerifiedMissionMarket = { market_id: string; venue: MissionMarketVenue; venue_version: string | null; chain_id: number; mission_contract: string; mission_symbol: string; stock_asset_id: string | null; stock_contract: string; stock_symbol: string; pool_id: string | null; quote_direction: 'MISSION_PER_STOCK' | null; launch_tx: string | null; launch_block: number | null; launch_timestamp: string | null; identity_status: 'VERIFIED' | 'UNAVAILABLE'; failures: LongFailure[]; evidence: Evidence[]; observed_block: number | null; observed_at: string; methodology_version: 'rmm-v0.4.0'; immutable: true };
export type VenueInventoryObservation = { observation_id: string; inventory_identity: string; market_id: string; venue: MissionMarketVenue; venue_version: string | null; verification_method: string; inventory_method: string; scope: 'PAIR_TRACKED_LOCKED_POSITIONS' | 'LONG_TRACKED_MARKETS' | 'LONG_CANONICAL_LAUNCH_POSITION_INVENTORY'; status: 'AVAILABLE' | 'UNAVAILABLE'; failure: LongFailure | null; stock_asset_id: string; stock_contract: string; stock_symbol: string; stock_decimals: number | null; stock_principal_raw: string | null; stock_principal_units: string | null; stock_total_supply_raw: string | null; stock_total_supply_units: string | null; absorption_pct: string | null; observed_block: number | null; observed_at: string; evidence: Evidence[]; methodology_version: 'rmm-v0.4.0'; immutable: true };
export type ExternalClaim = { claim_id: string; subject: string; metric: string; reported_value: string; reported_unit: string; reported_scope: string; source: Evidence; source_type: 'PROTOCOL_REPORTED' | 'MEDIA_REPORTED' | 'THIRD_PARTY_RESEARCH'; published_at: string | null; observed_at: string; notes: string; immutable: true };
export type ClaimAuditStatus = 'CONFIRMED' | 'PARTIALLY_CONFIRMED' | 'NOT_REPRODUCIBLE' | 'CONTRADICTED' | 'INSUFFICIENT_DATA' | 'NOT_COMPARABLE' | 'TEMPORAL_MISMATCH';
export type ClaimAudit = { audit_id: string; claim_id: string; market_id: string | null; reported_value: string; radar_value: string | null; difference_percentage_points: string | null; status: ClaimAuditStatus; scope_comparable: boolean; observed_block: number | null; observed_at: string; methodology_version: 'rmm-v0.4.0'; evidence: Evidence[]; immutable: true };
export type CrossVenueStockInventory = { stock_asset_id: string; stock_symbol: string; stock_contract: string; status: 'ALIGNED' | 'INCOMPLETE'; reference_block: number | null; included_observation_ids: string[]; duplicate_inventory_ids: string[]; pair_raw_units: string | null; long_raw_units: string | null; total_raw_units: string | null; total_supply_raw: string | null; coverage_pct: string | null; unclassified_pct: string | null; methodology_version: 'rmm-v0.4.0'; immutable: true };

const version = 'rmm-v0.4.0' as const;
const percent = (n: bigint, d: bigint) => d > 0n ? formatTokenUnits(n * 100n * 10n ** 10n / d, 10) : null;
const id = (...parts: string[]) => parts.join('|');

export function verifyLongMarketCandidate(candidate: LongMarketCandidate, assets: CanonicalStockAsset[], state: { pool_initialized: boolean; observed_block: number | null; observed_at: string }): VerifiedMissionMarket {
  const asset = assets.find((item) => item.chain_id === REFLEXIVE_CHAIN_ID && item.status === 'ASSET_STATUS_ACTIVE' && item.canonical_contract === normalizeBlockscoutAddress(candidate.quote_contract)); const failures: LongFailure[] = [];
  if (!asset) failures.push('QUOTE_NONCANONICAL'); if (!candidate.pool_id) failures.push('POOL_ID_UNRESOLVED'); else if (!state.pool_initialized) failures.push('POOL_STATE_UNAVAILABLE');
  // A public LONG page/index is useful discovery context, never factory provenance.
  failures.push('LONG_FACTORY_UNVERIFIED');
  return { market_id: candidate.market_id, venue: 'LONG', venue_version: candidate.venue_version, chain_id: REFLEXIVE_CHAIN_ID, mission_contract: normalizeBlockscoutAddress(candidate.mission_contract), mission_symbol: candidate.mission_symbol, stock_asset_id: asset?.asset_id ?? null, stock_contract: normalizeBlockscoutAddress(candidate.quote_contract), stock_symbol: candidate.quote_symbol, pool_id: candidate.pool_id?.toLowerCase() ?? null, quote_direction: asset && candidate.pool_id && state.pool_initialized ? 'MISSION_PER_STOCK' : null, launch_tx: candidate.launch_tx, launch_block: candidate.launch_block, launch_timestamp: candidate.launch_timestamp, identity_status: asset && candidate.pool_id && state.pool_initialized ? 'VERIFIED' : 'UNAVAILABLE', failures, evidence: [candidate.source], observed_block: state.observed_block, observed_at: state.observed_at, methodology_version: version, immutable: true };
}

/** Never falls back to V4 aggregate liquidity or PoolManager balances. */
export function unresolvedLongInventory(market: VerifiedMissionMarket): VenueInventoryObservation {
  return { observation_id: id('long-inventory-unavailable', market.market_id, market.observed_at), inventory_identity: id(String(REFLEXIVE_CHAIN_ID), market.venue, market.pool_id ?? market.market_id, 'liquidity-container-unresolved'), market_id: market.market_id, venue: 'LONG', venue_version: market.venue_version, verification_method: 'LONG_V4_MARKET_IDENTITY_V1', inventory_method: 'UNAVAILABLE_NO_ENUMERABLE_LIQUIDITY_CONTAINER', scope: 'LONG_TRACKED_MARKETS', status: 'UNAVAILABLE', failure: market.identity_status === 'VERIFIED' ? 'LIQUIDITY_CONTAINER_UNRESOLVED' : market.failures[0] ?? 'LONG_MARKET_DISCOVERY_ONLY', stock_asset_id: market.stock_asset_id ?? 'unresolved', stock_contract: market.stock_contract, stock_symbol: market.stock_symbol, stock_decimals: null, stock_principal_raw: null, stock_principal_units: null, stock_total_supply_raw: null, stock_total_supply_units: null, absorption_pct: null, observed_block: market.observed_block, observed_at: market.observed_at, evidence: market.evidence, methodology_version: version, immutable: true };
}

export function auditPercentageClaim(claim: ExternalClaim, observation: VenueInventoryObservation, maxTemporalSkewMs = 120_000): ClaimAudit {
  const comparable = claim.reported_unit === 'PERCENT_OF_CANONICAL_STOCK_SUPPLY' && claim.reported_scope === observation.scope; const sameTime = claim.published_at !== null && Math.abs(Date.parse(claim.published_at) - Date.parse(observation.observed_at)) <= maxTemporalSkewMs;
  const value = observation.absorption_pct === null ? null : Number(observation.absorption_pct); const reported = Number(claim.reported_value); let status: ClaimAuditStatus = 'INSUFFICIENT_DATA';
  if (!comparable) status = 'NOT_COMPARABLE'; else if (!sameTime) status = 'TEMPORAL_MISMATCH'; else if (value === null || !Number.isFinite(value) || !Number.isFinite(reported)) status = 'INSUFFICIENT_DATA'; else { const gap = Math.abs(value - reported); status = gap <= .25 ? 'CONFIRMED' : gap <= 2 ? 'PARTIALLY_CONFIRMED' : value === 0 ? 'NOT_REPRODUCIBLE' : 'CONTRADICTED'; }
  return { audit_id: id('claim-audit', claim.claim_id, observation.observation_id), claim_id: claim.claim_id, market_id: observation.market_id, reported_value: claim.reported_value, radar_value: observation.absorption_pct, difference_percentage_points: comparable && sameTime && value !== null && Number.isFinite(reported) ? String(value - reported) : null, status, scope_comparable: comparable, observed_block: observation.observed_block, observed_at: observation.observed_at, methodology_version: version, evidence: [claim.source, ...observation.evidence], immutable: true };
}

export function aggregateCrossVenueStockInventory(asset: CanonicalStockAsset, observations: VenueInventoryObservation[]): CrossVenueStockInventory {
  const candidates = observations.filter((item) => item.stock_asset_id === asset.asset_id && item.status === 'AVAILABLE' && item.stock_principal_raw && item.stock_total_supply_raw && item.observed_block !== null); const duplicate: string[] = []; const unique: VenueInventoryObservation[] = []; const seen = new Set<string>();
  for (const item of candidates) { if (seen.has(item.inventory_identity)) duplicate.push(item.observation_id); else { seen.add(item.inventory_identity); unique.push(item); } }
  const reference = unique[0]; const aligned = Boolean(reference) && unique.every((item) => item.observed_block === reference.observed_block && item.stock_total_supply_raw === reference.stock_total_supply_raw); const pair = aligned ? unique.filter((item) => item.venue === 'PAIR').reduce((sum, item) => sum + BigInt(item.stock_principal_raw!), 0n) : null; const long = aligned ? unique.filter((item) => item.venue === 'LONG').reduce((sum, item) => sum + BigInt(item.stock_principal_raw!), 0n) : null; const total = pair !== null && long !== null ? pair + long : null; const supply = aligned && reference ? BigInt(reference.stock_total_supply_raw!) : null;
  const decimals = reference?.stock_decimals; const display = (amount: bigint | null) => amount === null || decimals === null || decimals === undefined ? null : formatTokenUnits(amount, decimals);
  return { stock_asset_id: asset.asset_id, stock_symbol: asset.ticker, stock_contract: asset.canonical_contract, status: aligned ? 'ALIGNED' : 'INCOMPLETE', reference_block: aligned ? reference!.observed_block : null, included_observation_ids: aligned ? unique.map((item) => item.observation_id) : [], duplicate_inventory_ids: duplicate, pair_raw_units: display(pair), long_raw_units: display(long), total_raw_units: display(total), total_supply_raw: supply === null ? null : String(supply), coverage_pct: total === null || supply === null ? null : percent(total, supply), unclassified_pct: total === null || supply === null ? null : percent(supply - total, supply), methodology_version: version, immutable: true };
}
