import { createHash } from 'node:crypto';
import pg from 'pg';
import { normalizeBlockscoutAddress } from '../providers/blockscoutProvider';
import { resolvePostgresPool, RetryablePostgresSchema, type PostgresPoolSource } from '../persistence/retryablePostgresSchema';

/**
 * Reflexive Radar deliberately models observations, not CALL/RESOLUTION/PRINT
 * receipts.  The source data is append-only and every number retains units.
 */
export const REFLEXIVE_CHAIN_ID = 4663;
export const REFLEXIVE_METHOD_VERSION = 'rmm-v0.3.1';
export const TRACKED_PAIR_ABSORPTION_THRESHOLDS_VERSION = 'TRACKED_PAIR_ABSORPTION_THRESHOLDS_V1';
export const TRACKED_PAIR_ABSORPTION_THRESHOLDS = [1, 5, 10, 25] as const;
export const PAIR_V5_ABI_SOURCE = 'PAIR production frontend + documentation, observed 2026-09-01';
/** Addresses are documentation candidates; PairV5OnchainVerifier verifies chain id and deployed bytecode before use. */
export const PAIR_V5_DEPLOYMENTS = {
  launchpad: '0x8660A7F019C7943b0b0A91B8E39AFf3b6DB6Ae62', locker: '0xeFcF476E8870fB3eb8680f039414fdcCE6C2a117', hook: '0x16D1560630Ce74af4478d9b8AD46548A092A2000',
  poolManager: '0x8366a39CC670B4001A1121B8F6A443A643e40951', positionManager: '0x58daec3116aae6D93017bAAea7749052E8a04fA7', stateView: '0xF3334192D15450CdD385c8B70e03f9A6bD9E673b'
} as const;
export type CanonicalStockAsset = { asset_id: string; ticker: string; name: string; chain_id: number; canonical_contract: string; status: string; current_multiplier: string; pending_multiplier: string | null; pending_multiplier_effective_at: string | null; trading_capabilities: Record<string, unknown> | null; logo: string | null; observed_at: string; fetched_at: string; provenance: string; first_party_asset: boolean };
export type PoolKey = { currency0: string; currency1: string; fee: number; tick_spacing: number; hooks: string };
export type PairBirthRecord = { birth_id: string; mission_pair_id: string; launch_group_id: string; chain_id: number; mission_contract: string; mission_symbol: string; quote_contract: string; quote_ticker: string; rh_asset_id: string; venue: 'PAIR'; venue_version: 'V5'; launchpad_proxy: string; launch_implementation: string | null; pool_key: PoolKey; pool_id: string; pool_manager: string; hook: string; fee: number; tickSpacing: number; launch_tx: string; launch_block: number; launch_timestamp: string; discovery_source: string; canonical_evidence: Evidence[]; birth_recorded_at: string; methodology_version: string; immutable: true };
export type LifecycleCheckpoint = { checkpoint_id: string; pair_id: string; checkpoint: 'T10M' | 'T1H' | 'T6H' | 'T24H' | 'D3' | 'D7' | 'D30'; target_at: string; state: 'PENDING' | 'OBSERVED' | 'MISSED' | 'UNAVAILABLE'; actual_observation_id: string | null; actual_observed_at: string | null; distance_ms: number | null; source_completeness: 'complete' | 'partial' | 'unavailable' };
export type PairVerification = { verification_status: 'CANDIDATE' | 'PARTIALLY_VERIFIED' | 'VERIFIED'; failure_reasons: VerificationFailure[]; verified_at: string | null; verification_block: number | null; observed_block: number | null; confirmed_block: number | null; launch_provenance_method: 'launchpad_registry_and_receipt' | null; launch_implementation_observed: string | null; pool_key: PoolKey | null; state_view_address: string | null; state_observed_block: number | null; state_observed_at: string | null; rpc_provider: string | null; sqrt_price_x96: string | null; tick: number | null; active_liquidity: string | null; position_token_id: string | null; position_verification_status: 'VERIFIED_LOCKER_POSITION' | 'POSITION_UNRESOLVED' | 'NOT_ATTEMPTED' };
export type VerificationFailure = 'PAIR_API_ONLY' | 'CHAIN_ID_MISMATCH' | 'NONCANONICAL_STOCK_TOKEN' | 'LAUNCHPAD_PROVENANCE_MISSING' | 'POOL_KEY_UNRESOLVED' | 'POOL_ID_MISMATCH' | 'POOL_NOT_INITIALIZED' | 'STATEVIEW_UNAVAILABLE' | 'HOOK_MISMATCH' | 'LAUNCH_TX_UNCONFIRMED' | 'POSITION_UNRESOLVED' | 'POSITION_POOL_MISMATCH' | 'POSITION_STATE_MISMATCH' | 'POSITION_NOT_LOCKED' | 'ZERO_STOCK_SUPPLY' | 'RPC_UNAVAILABLE';
export type MissionPair = { pair_id: string; launch_id: string; launch_group_id: string; chain_id: number; protocol: string; venue: string; pool_id: string; pool_address: string | null; mission_contract: string; mission_symbol: string; stock_asset_id: string; quote_contract: string; launched_at: string; launch_block: number | null; canonicality: 'verified' | 'rejected' | 'source_required'; first_party_asset: boolean; fee_policy: string | null; evidence: Evidence[]; verification: PairVerification };
export type Evidence = { source: string; href: string; observed_at: string; fetched_at: string; note: string; quality: 'onchain' | 'official_api' | 'indexed_context' | 'unavailable' };
export type PairObservation = { observation_id: string; pair_id: string; observed_at: string; fetched_at: string; observed_block: number | null; sqrt_price_x96: string | null; tick: number | null; active_liquidity: string | null; mission_stock_price: string | null; multiplier_context: string | null; mission_usd_price: number | null; stock_dex_usd_price: number | null; underlying_usd_price: number | null; underlying_observed_at: string | null; liquidity_usd: number | null; volume_24h_usd: number | null; quote_inventory_raw: string | null; quote_inventory_share_equivalent: string | null; inventory_method: 'v4_position_reconstruction' | 'locked_position_accounting' | 'event_derived_position_accounting' | 'unavailable'; fresh: boolean; provenance: Evidence[]; immutable: true };
export type PositionIdentityObservation = { position_identity_id: string; mission_pair_id: string; pool_id: string; token_id: string; position_manager: string; core_position_owner: string; core_position_salt: string; nft_owner: string | null; expected_locker: string; lock_status: 'VERIFIED_LOCKED' | 'VERIFIED_NOT_LOCKED' | 'UNRESOLVED'; pool_key: PoolKey; tick_lower: number; tick_upper: number; liquidity_raw: string; observed_block: number; observed_at: string; methodology_version: string; immutable: true };
export type PositionStateProof = { proof_id: string; mission_pair_id: string; pool_id: string; position_manager: string; token_id: string; owner_locker: string | null; tick_lower: number; tick_upper: number; position_manager_liquidity_raw: string; v4_core_liquidity_raw: string | null; salt: string; state_view: string; observed_block: number | null; observed_at: string; match_status: 'POSITIONMANAGER_CORE_MATCH' | 'POSITION_STATE_MISMATCH' | 'CORE_POSITION_UNAVAILABLE'; methodology_version: string; evidence: Evidence[]; immutable: true };
export type LockedInventoryObservation = { observation_id: string; mission_pair_id: string; position_identity_id: string | null; position_state_proof_id: string | null; status: 'AVAILABLE' | 'UNAVAILABLE'; accounting_classification: 'VERIFIED_POSITION_ACCOUNTING' | 'UNAVAILABLE'; reason: VerificationFailure | 'ARCHIVE_STATE_UNAVAILABLE' | 'CORE_POSITION_UNAVAILABLE' | null; scope: 'CANONICAL_LOCKED_POSITION'; method: 'VERIFIED_LOCKED_POSITION_RECONSTRUCTION_V1'; token_id: string | null; position_manager: string; stock_asset_id: string; stock_symbol: string; stock_contract: string; stock_decimals: number | null; mission_principal_raw: string | null; mission_principal_units: string | null; stock_principal_raw: string | null; stock_principal_units: string | null; stock_share_equivalent_units: string | null; amount0_raw: string | null; amount1_raw: string | null; stock_total_supply_raw: string | null; stock_total_supply_units: string | null; stock_total_supply_share_equivalent_units: string | null; absorption_pct: string | null; range_state: 'BELOW_RANGE' | 'IN_RANGE' | 'ABOVE_RANGE' | null; tick_lower: number | null; tick_upper: number | null; current_tick: number | null; sqrt_price_x96: string | null; position_liquidity_raw: string | null; core_position_liquidity_raw: string | null; multiplier: string | null; pending_multiplier: string | null; pending_multiplier_effective_at: string | null; observed_block: number | null; observed_at: string; rpc_provider: string; evidence: Evidence[]; methodology_version: string; immutable: true };
export type TrackedStockInventoryAggregate = { aggregate_observation_id: string; stock_asset_id: string; stock_symbol: string; stock_contract: string; status: 'ALIGNED' | 'INCOMPLETE'; aggregation_scope: 'TRACKED_PAIR_CANONICAL_LOCKED_POSITIONS'; reference_block: number | null; reference_time: string | null; included_observation_ids: string[]; excluded_observations: Array<{ observation_id: string; reason: 'STALE' | 'MISMATCHED_BLOCK' | 'DUPLICATE_TOKEN_ID' | 'UNAVAILABLE' }>; raw_stock_token_units: string | null; share_equivalent_units: string | null; stock_total_supply_raw: string | null; stock_total_supply_units: string | null; tracked_pair_locked_absorption_pct: string | null; position_count: number; mission_pair_count: number; methodology_version: string; immutable: true };
export type PositionInventoryDelta = { delta_id: string; mission_pair_id: string; token_id: string; previous_observation_id: string; current_observation_id: string; previous_amount_raw: string; current_amount_raw: string; delta_raw: string; delta_pct: string | null; previous_stock_total_supply_raw: string | null; current_stock_total_supply_raw: string | null; stock_total_supply_delta_raw: string | null; elapsed_ms: number; previous_range_state: LockedInventoryObservation['range_state']; current_range_state: LockedInventoryObservation['range_state']; previous_price_context: string | null; current_price_context: string | null; label: 'POSITION INVENTORY CHANGED'; methodology_version: string; immutable: true };
export type InventoryBaseline = { mission_pair_id: string; inventory_baseline_observation_id: string; recorded_at: string; methodology_version: string; immutable: true };
export type StockSupplyEvent = { event_id: string; asset_id: string; event_type: 'mint' | 'burn' | 'multiplier_change'; raw_token_amount: string | null; share_equivalent_amount: string | null; block: number | null; tx_hash: string | null; timestamp: string; before_supply_raw: string | null; after_supply_raw: string | null; provenance: Evidence };
export type ReflexivityEvent = { event_id: string; event_type: 'NEW_STOCK_PAIRED_MARKET' | 'QUOTE_ABSORPTION_MILESTONE' | 'STOCK_TOKEN_BASIS_EXCURSION' | 'STOCK_SUPPLY_MINT' | 'STOCK_SUPPLY_BURN' | 'SUPPLY_RESPONSE_AFTER_STRESS' | 'MISSION_ALPHA_BREAKOUT' | 'QUOTE_VOLUME_SHARE_MILESTONE' | 'D1_SURVIVAL' | 'D3_SURVIVAL' | 'D7_SURVIVAL'; subject_id: string; occurred_at: string; trigger_version: string; trigger: string; evidence_ids: string[] };
export type ThesisState = 'SUPPORTING' | 'MIXED' | 'AGAINST' | 'INSUFFICIENT_DATA';
export type ThesisEvidence = { hypothesis_id: 'H1' | 'H2' | 'H3' | 'H4' | 'H5' | 'H6'; state: ThesisState; rule_version: string; rationale: string; evidence_ids: string[]; observed_at: string };
export type ReflexiveSnapshot = { assets: CanonicalStockAsset[]; pairs: MissionPair[]; births: PairBirthRecord[]; lifecycle: LifecycleCheckpoint[]; observations: PairObservation[]; position_identities: PositionIdentityObservation[]; position_state_proofs: PositionStateProof[]; inventory_observations: LockedInventoryObservation[]; inventory_aggregates: TrackedStockInventoryAggregate[]; inventory_deltas: PositionInventoryDelta[]; inventory_baselines: InventoryBaseline[]; supply_events: StockSupplyEvent[]; events: ReflexivityEvent[]; thesis: ThesisEvidence[]; refreshed_at: string; cursor: string | null };

export interface ReflexiveStore { readonly adapter: 'memory' | 'postgres'; readonly durable: boolean; load(): Promise<ReflexiveSnapshot>; save(snapshot: ReflexiveSnapshot): Promise<void>; }
const emptySnapshot = (): ReflexiveSnapshot => ({ assets: [], pairs: [], births: [], lifecycle: [], observations: [], position_identities: [], position_state_proofs: [], inventory_observations: [], inventory_aggregates: [], inventory_deltas: [], inventory_baselines: [], supply_events: [], events: [], thesis: defaultThesis(), refreshed_at: new Date(0).toISOString(), cursor: null });
export class InMemoryReflexiveStore implements ReflexiveStore { readonly adapter = 'memory' as const; readonly durable = false; private snapshot = emptySnapshot(); async load() { return structuredClone(this.snapshot); } async save(snapshot: ReflexiveSnapshot) { this.snapshot = structuredClone(snapshot); } }
export class PostgresReflexiveStore implements ReflexiveStore {
  readonly adapter = 'postgres' as const; readonly durable = true; private readonly pool: pg.Pool; private readonly ownsPool: boolean; private readonly schema = new RetryablePostgresSchema('rh_chain_reflexive_store');
  constructor(source: PostgresPoolSource) { const result = resolvePostgresPool(source); this.pool = result.pool; this.ownsPool = result.ownsPool; }
  async load() { await this.ensure(); const row = await this.pool.query<{ payload: ReflexiveSnapshot }>('select payload from rh_chain_reflexive_snapshots order by refreshed_at desc limit 1'); return hydrateSnapshot(row.rows[0]?.payload); }
  async save(snapshot: ReflexiveSnapshot) { await this.ensure(); await this.pool.query('insert into rh_chain_reflexive_snapshots (snapshot_id, refreshed_at, payload) values ($1,$2,$3::jsonb)', [stableId('snapshot', snapshot.refreshed_at), snapshot.refreshed_at, JSON.stringify(snapshot)]); }
  async close() { if (this.ownsPool) await this.pool.end(); }
  private ensure() { return this.schema.ensure(this.pool, 'create table if not exists rh_chain_reflexive_snapshots (snapshot_id text primary key, refreshed_at timestamptz not null, payload jsonb not null); create index if not exists rh_chain_reflexive_snapshots_refreshed_at_idx on rh_chain_reflexive_snapshots (refreshed_at desc);'); }
}
function hydrateSnapshot(value: ReflexiveSnapshot | undefined): ReflexiveSnapshot { const base = value ?? emptySnapshot(); return { ...emptySnapshot(), ...base, position_identities: base.position_identities ?? [], position_state_proofs: base.position_state_proofs ?? [], inventory_observations: base.inventory_observations ?? [], inventory_aggregates: base.inventory_aggregates ?? [], inventory_deltas: base.inventory_deltas ?? [], inventory_baselines: base.inventory_baselines ?? [] }; }

type RobinhoodAsset = { id?: unknown; tokenSymbol?: unknown; tokenName?: unknown; deployments?: unknown; currentMultiplier?: unknown; pendingMultiplier?: unknown; pendingMultiplierEffectiveTime?: unknown; tradingCapabilities?: unknown; logoUrl?: unknown; status?: unknown };
export type PairDiscoveryCandidate = { protocol: string; venue: string; pool_id: string; pool_address?: string | null; mission_contract: string; mission_symbol: string; quote_contract: string; launched_at: string; launch_tx_hash?: string | null; launch_block?: number | null; launch_id?: string; hook?: string | null; fee_policy?: string | null; evidence: Evidence[]; onchain?: PairVerification; first_party_asset?: boolean };
export type ReflexiveProvider = { assets(): Promise<unknown>; discover?(assets: CanonicalStockAsset[], cursor: string | null): Promise<PairDiscoveryCandidate[]>; observations?(pairs: MissionPair[], assets: CanonicalStockAsset[]): Promise<PairObservation[]>; inventory?(pairs: MissionPair[], assets: CanonicalStockAsset[]): Promise<{ identities: PositionIdentityObservation[]; proofs: PositionStateProof[]; observations: LockedInventoryObservation[] }>; supplyEvents?(assets: CanonicalStockAsset[]): Promise<StockSupplyEvent[]> };

/** PAIR's index is discovery context. A candidate is emitted only after an independent
 * verifier accepts the V4 pool id/mission/quote relationship; API cards never qualify a pair. */
export class PairV5DiscoveryAdapter {
  constructor(private readonly options: { fetchImpl?: typeof fetch; baseUrl?: string; verifyPool: (input: PairDiscoveryCandidate) => Promise<boolean | PairVerification>; now?: () => Date }) {}
  async discover(assets: CanonicalStockAsset[]): Promise<PairDiscoveryCandidate[]> {
    const fetched = (this.options.now ?? (() => new Date()))().toISOString(); const response = await (this.options.fetchImpl ?? fetch)(`${(this.options.baseUrl ?? 'https://pair.fund').replace(/\/$/, '')}/api/tokens`);
    if (!response.ok) throw new Error(`pair_tokens_http_${response.status}`); const body = await response.json() as { items?: unknown[] }; const items = Array.isArray(body.items) ? body.items : []; const output: PairDiscoveryCandidate[] = [];
    for (const item of items) { if (!isRecord(item)) continue; const mission = string(item.address); const symbol = string(item.symbol); const launchedAt = unixToIso(item.launchedAt); const launchTx = string(item.launchTxHash); const pairs = Array.isArray(item.pairs) ? item.pairs : [];
      if (!mission || !symbol || !launchedAt) continue;
      for (const pair of pairs) { if (!isRecord(pair) || string(pair.ammVersion) !== 'V4_MULTI') continue; const quote = isRecord(pair.quoteToken) ? string(pair.quoteToken.address) : null; const poolId = string(pair.poolId); if (!quote || !poolId || !isCanonicalStockContract(assets, quote)) continue;
        const candidate: PairDiscoveryCandidate = { protocol: 'uniswap-v4', venue: 'PAIR', pool_id: poolId, pool_address: null, mission_contract: mission, mission_symbol: symbol, quote_contract: quote, launched_at: launchedAt, launch_id: string(item.launchTxHash) ?? undefined, launch_tx_hash: launchTx, hook: isRecord(pair) ? string(pair.hookAddress) : null, fee_policy: 'PAIR V5; fee semantics must be read from verified launch configuration.', evidence: [{ source: 'PAIR /api/tokens', href: 'https://pair.fund/api/tokens', observed_at: fetched, fetched_at: fetched, note: 'PAIR indexed discovery context; chain verification is required.', quality: 'indexed_context' }, ...(launchTx ? [{ source: 'PAIR launch transaction', href: `https://robinhoodchain.blockscout.com/tx/${launchTx}`, observed_at: fetched, fetched_at: fetched, note: 'Launch transaction reference supplied by discovery index.', quality: 'indexed_context' as const }] : [])] };
        const result = await this.options.verifyPool(candidate); if (!result) continue; candidate.onchain = typeof result === 'boolean' ? { verification_status: 'VERIFIED', failure_reasons: [], verified_at: fetched, verification_block: null, observed_block: null, confirmed_block: null, launch_provenance_method: 'launchpad_registry_and_receipt', launch_implementation_observed: null, pool_key: null, state_view_address: null, state_observed_block: null, state_observed_at: null, rpc_provider: 'adapter_verify_callback', sqrt_price_x96: null, tick: null, active_liquidity: null, position_token_id: null, position_verification_status: 'NOT_ATTEMPTED' } : result; output.push(candidate);
      }
    }
    return output;
  }
}

const launchpadAbi = [
  { type: 'function', name: 'getLaunchPoolCount', stateMutability: 'view', inputs: [{ type: 'address' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getLaunchPool', stateMutability: 'view', inputs: [{ type: 'address' }, { type: 'uint256' }], outputs: [{ type: 'tuple', components: [{ name: 'quoteToken', type: 'address' }, { name: 'weightBps', type: 'uint16' }, { name: 'poolId', type: 'bytes32' }, { name: 'positionId', type: 'uint256' }, { name: 'initialProjectTokenAmount', type: 'uint256' }, { name: 'tickLower', type: 'int24' }, { name: 'tickUpper', type: 'int24' }, { name: 'quoteUsdAtLaunchE8', type: 'uint256' }, { name: 'quotePriceFeed', type: 'address' }, { name: 'quoteDecimals', type: 'uint8' }] }] }
] as const;
/**
 * Minimal ABI copied from the deployed V4 StateView verified interface.  Core positions
 * are keyed by (PoolId, owner, tickLower, tickUpper, salt); `getLiquidity(poolId)` is
 * aggregate active liquidity and is deliberately never used for a position proof.
 */
export const stateViewAbi = [
  { type: 'function', name: 'getSlot0', stateMutability: 'view', inputs: [{ name: 'poolId', type: 'bytes32' }], outputs: [{ name: 'sqrtPriceX96', type: 'uint160' }, { name: 'tick', type: 'int24' }, { name: 'protocolFee', type: 'uint24' }, { name: 'lpFee', type: 'uint24' }] },
  { type: 'function', name: 'getLiquidity', stateMutability: 'view', inputs: [{ name: 'poolId', type: 'bytes32' }], outputs: [{ type: 'uint128' }] },
  { type: 'function', name: 'getPositionInfo', stateMutability: 'view', inputs: [{ name: 'poolId', type: 'bytes32' }, { name: 'owner', type: 'address' }, { name: 'tickLower', type: 'int24' }, { name: 'tickUpper', type: 'int24' }, { name: 'salt', type: 'bytes32' }], outputs: [{ name: 'liquidity', type: 'uint128' }, { name: 'feeGrowthInside0LastX128', type: 'uint256' }, { name: 'feeGrowthInside1LastX128', type: 'uint256' }] }
] as const;
/** Pinned minimal ABI from the deployed Uniswap v4 PositionManager interface. */
const positionManagerAbi = [
  { type: 'function', name: 'ownerOf', stateMutability: 'view', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'address' }] },
  { type: 'function', name: 'getPositionLiquidity', stateMutability: 'view', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'uint128' }] },
  { type: 'function', name: 'getPoolAndPositionInfo', stateMutability: 'view', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ name: 'poolKey', type: 'tuple', components: [{ name: 'currency0', type: 'address' }, { name: 'currency1', type: 'address' }, { name: 'fee', type: 'uint24' }, { name: 'tickSpacing', type: 'int24' }, { name: 'hooks', type: 'address' }] }, { name: 'info', type: 'uint256' }] }
] as const;
const erc20Abi = [{ type: 'function', name: 'decimals', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint8' }] }, { type: 'function', name: 'totalSupply', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] }] as const;
const EIP1967_IMPLEMENTATION_SLOT = '0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc' as `0x${string}`;

/** The PositionManager maps its NFT id directly into the V4 core position salt. */
export function positionTokenIdSalt(tokenId: string | bigint): `0x${string}` {
  const value = BigInt(tokenId); if (value < 0n || value > MAX_UINT256) throw new RangeError('invalid_position_token_id');
  return `0x${value.toString(16).padStart(64, '0')}`;
}
export function reconcilePositionLiquidity(positionManagerLiquidity: string | bigint, coreLiquidity: string | bigint | null | undefined) {
  if (coreLiquidity === null || coreLiquidity === undefined) return { match_status: 'CORE_POSITION_UNAVAILABLE' as const, position_manager_liquidity_raw: String(positionManagerLiquidity), v4_core_liquidity_raw: null };
  const pm = BigInt(positionManagerLiquidity); const core = BigInt(coreLiquidity);
  return { match_status: pm === core ? 'POSITIONMANAGER_CORE_MATCH' as const : 'POSITION_STATE_MISMATCH' as const, position_manager_liquidity_raw: String(pm), v4_core_liquidity_raw: String(core) };
}
export function archiveCapabilityStatus(historicalEthCallSucceeded: boolean): 'ARCHIVE_CAPABLE' | 'PROSPECTIVE_ONLY' { return historicalEthCallSucceeded ? 'ARCHIVE_CAPABLE' : 'PROSPECTIVE_ONLY'; }

export function normalizePoolKey(mission: string, quote: string, fee: number, tickSpacing: number, hooks: string): PoolKey {
  const [currency0, currency1] = [normalizeBlockscoutAddress(mission), normalizeBlockscoutAddress(quote)].sort();
  return { currency0, currency1, fee, tick_spacing: tickSpacing, hooks: normalizeBlockscoutAddress(hooks) };
}
/** This is the deployed Uniswap V4 PoolKey hash: keccak256(abi.encode(PoolKey)); no custom formula. */
export async function deriveUniswapV4PoolId(key: PoolKey): Promise<`0x${string}`> {
  const { encodeAbiParameters, keccak256 } = await import('viem');
  return keccak256(encodeAbiParameters([{ type: 'address' }, { type: 'address' }, { type: 'uint24' }, { type: 'int24' }, { type: 'address' }], [key.currency0 as `0x${string}`, key.currency1 as `0x${string}`, key.fee, key.tick_spacing, key.hooks as `0x${string}`]));
}
export function missionPerStockFromSqrtPrice(sqrtPriceX96: bigint, missionIsCurrency0: boolean, missionDecimals: number, stockDecimals: number): string | null {
  if (sqrtPriceX96 <= 0n || !Number.isInteger(missionDecimals) || !Number.isInteger(stockDecimals) || missionDecimals < 0 || stockDecimals < 0) return null;
  // raw currency1/currency0 = (sqrtPriceX96 / 2^96)^2. Convert raw units to human units before orienting mission/stock.
  const root = Number(sqrtPriceX96) / Number(2n ** 96n); const c1PerC0 = root * root * 10 ** (missionDecimals - stockDecimals);
  const value = missionIsCurrency0 ? c1PerC0 : 1 / c1PerC0;
  return Number.isFinite(value) && value > 0 && value < Number.MAX_VALUE ? value.toString() : null;
}

const Q96 = 2n ** 96n;
const MAX_UINT256 = (2n ** 256n) - 1n;
/** Canonical TickMath port. It returns Q64.96 and intentionally uses integer rounding-up exactly as v3/v4 TickMath. */
export function sqrtRatioAtTick(tick: number): bigint {
  if (!Number.isInteger(tick) || tick < -887272 || tick > 887272) throw new RangeError('tick_out_of_range');
  let abs = BigInt(Math.abs(tick)); let ratio = (abs & 1n) !== 0n ? 0xfffcb933bd6fad37aa2d162d1a594001n : 0x100000000000000000000000000000000n;
  const multipliers = [0xfff97272373d413259a46990580e213an, 0xfff2e50f5f656932ef12357cf3c7fdccn, 0xffe5caca7e10e4e61c3624eaa0941cd0n, 0xffcb9843d60f6159c9db58835c926644n, 0xff973b41fa98c081472e6896dfb254c0n, 0xff2ea16466c96a3843ec78b326b52861n, 0xfe5dee046a99a2a811c461f1969c3053n, 0xfcbe86c7900a88aedcffc83b479aa3a4n, 0xf987a7253ac413176f2b074cf7815e54n, 0xf3392b0822b70005940c7a398e4b70f3n, 0xe7159475a2c29b7443b29c7fa6e889d9n, 0xd097f3bdfd2022b8845ad8f792aa5825n, 0xa9f746462d870fdf8a65dc1f90e061e5n, 0x70d869a156d2a1b890bb3df62baf32f7n, 0x31be135f97d08fd981231505542fcfa6n, 0x9aa508b5b7a84e1c677de54f3e99bc9n, 0x5d6af8dedb81196699c329225ee604n, 0x2216e584f5fa1ea926041bedfe98n, 0x48a170391f7dc42444e8fa2n];
  for (let index = 0; index < multipliers.length; index++) { const bit = 2n << BigInt(index); if ((abs & bit) !== 0n) ratio = (ratio * multipliers[index]) >> 128n; }
  if (tick > 0) ratio = MAX_UINT256 / ratio;
  return (ratio >> 32n) + (ratio % (2n ** 32n) === 0n ? 0n : 1n);
}
/** Snapshot principal is rounded down, never up: this is a conservative lower-bound token amount and excludes fees. */
function amount0Delta(sqrtA: bigint, sqrtB: bigint, liquidity: bigint): bigint { const [a, b] = sqrtA > sqrtB ? [sqrtB, sqrtA] : [sqrtA, sqrtB]; return liquidity * (b - a) * Q96 / b / a; }
function amount1Delta(sqrtA: bigint, sqrtB: bigint, liquidity: bigint): bigint { const [a, b] = sqrtA > sqrtB ? [sqrtB, sqrtA] : [sqrtA, sqrtB]; return liquidity * (b - a) / Q96; }
export function reconstructPositionPrincipal(liquidity: bigint, tickLower: number, tickUpper: number, sqrtPriceX96: bigint) {
  if (liquidity < 0n || tickLower >= tickUpper || sqrtPriceX96 <= 0n) throw new RangeError('invalid_position_state'); const lower = sqrtRatioAtTick(tickLower); const upper = sqrtRatioAtTick(tickUpper);
  if (sqrtPriceX96 <= lower) return { amount0: amount0Delta(lower, upper, liquidity), amount1: 0n, range_state: 'BELOW_RANGE' as const };
  if (sqrtPriceX96 >= upper) return { amount0: 0n, amount1: amount1Delta(lower, upper, liquidity), range_state: 'ABOVE_RANGE' as const };
  return { amount0: amount0Delta(sqrtPriceX96, upper, liquidity), amount1: amount1Delta(lower, sqrtPriceX96, liquidity), range_state: 'IN_RANGE' as const };
}
export function formatTokenUnits(raw: bigint, decimals: number): string { if (decimals < 0 || !Number.isInteger(decimals)) throw new RangeError('invalid_decimals'); const sign = raw < 0n ? '-' : ''; const digits = (raw < 0n ? -raw : raw).toString().padStart(decimals + 1, '0'); if (decimals === 0) return `${sign}${digits}`; const whole = digits.slice(0, -decimals) || '0'; const fraction = digits.slice(-decimals).replace(/0+$/, ''); return `${sign}${whole}${fraction ? `.${fraction}` : ''}`; }
function decimalProduct(value: bigint, decimals: number, multiplier: string): string | null { const parsed = /^([0-9]+)(?:\.([0-9]+))?$/.exec(multiplier); if (!parsed) return null; const fraction = parsed[2] ?? ''; if (fraction.length > 18) return null; const scaled = BigInt(`${parsed[1]}${fraction.padEnd(18, '0')}`); return formatTokenUnits(value * scaled, decimals + 18); }
function percentage(numerator: bigint, denominator: bigint): string | null { if (numerator < 0n || denominator <= 0n) return null; return formatTokenUnits(numerator * 10n ** 10n * 100n / denominator, 10); }
function unpackSigned24(value: bigint): number { const raw = Number(value & 0xffffffn); return raw >= 0x800000 ? raw - 0x1000000 : raw; }

/**
 * A category aggregate is valid only when all selected positions and the canonical
 * totalSupply were read at the same block. We intentionally publish INCOMPLETE rather
 * than a partial numerator when the cohort is not synchronized.
 */
export function aggregateTrackedPairInventory(asset: CanonicalStockAsset, observations: LockedInventoryObservation[]): TrackedStockInventoryAggregate {
  const relevant = observations.filter((item) => item.stock_asset_id === asset.asset_id);
  const excluded: TrackedStockInventoryAggregate['excluded_observations'] = [];
  const ordered = [...relevant].sort((a, b) => b.observed_at.localeCompare(a.observed_at)); const selected: LockedInventoryObservation[] = [];
  const tokenIds = new Set<string>();
  for (const item of ordered) {
    if (item.status !== 'AVAILABLE' || item.accounting_classification !== 'VERIFIED_POSITION_ACCOUNTING' || !item.token_id || !item.stock_principal_raw || !item.stock_total_supply_raw || item.observed_block === null) { excluded.push({ observation_id: item.observation_id, reason: 'UNAVAILABLE' }); continue; }
    if (tokenIds.has(item.token_id)) { excluded.push({ observation_id: item.observation_id, reason: 'DUPLICATE_TOKEN_ID' }); continue; }
    tokenIds.add(item.token_id); selected.push(item);
  }
  const reference = selected[0] ?? null;
  const mismatched = reference ? selected.filter((item) => item.observed_block !== reference.observed_block || item.stock_total_supply_raw !== reference.stock_total_supply_raw || item.multiplier !== reference.multiplier) : [];
  for (const item of mismatched) excluded.push({ observation_id: item.observation_id, reason: 'MISMATCHED_BLOCK' });
  const included = selected.filter((item) => !mismatched.includes(item)); const complete = Boolean(reference && mismatched.length === 0 && included.length);
  const numerator = complete ? included.reduce((sum, item) => sum + BigInt(item.stock_principal_raw!), 0n) : null; const denominator = complete && reference?.stock_total_supply_raw ? BigInt(reference.stock_total_supply_raw) : null; const decimals = reference?.stock_decimals ?? null;
  return { aggregate_observation_id: stableId('tracked-pair-inventory', asset.asset_id, String(reference?.observed_block ?? 'incomplete'), ...included.map((item) => item.observation_id).sort()), stock_asset_id: asset.asset_id, stock_symbol: asset.ticker, stock_contract: asset.canonical_contract, status: complete ? 'ALIGNED' : 'INCOMPLETE', aggregation_scope: 'TRACKED_PAIR_CANONICAL_LOCKED_POSITIONS', reference_block: complete ? reference!.observed_block : null, reference_time: complete ? reference!.observed_at : null, included_observation_ids: complete ? included.map((item) => item.observation_id) : [], excluded_observations: excluded, raw_stock_token_units: complete && numerator !== null && decimals !== null ? formatTokenUnits(numerator, decimals) : null, share_equivalent_units: complete && numerator !== null && decimals !== null ? decimalProduct(numerator, decimals, reference!.multiplier ?? '1') : null, stock_total_supply_raw: complete ? reference!.stock_total_supply_raw : null, stock_total_supply_units: complete ? reference!.stock_total_supply_units : null, tracked_pair_locked_absorption_pct: complete && numerator !== null && denominator !== null ? percentage(numerator, denominator) : null, position_count: complete ? included.length : 0, mission_pair_count: complete ? new Set(included.map((item) => item.mission_pair_id)).size : 0, methodology_version: REFLEXIVE_METHOD_VERSION, immutable: true };
}

export function derivePositionInventoryDelta(previous: LockedInventoryObservation, current: LockedInventoryObservation): PositionInventoryDelta | null {
  if (previous.status !== 'AVAILABLE' || current.status !== 'AVAILABLE' || previous.token_id !== current.token_id || previous.mission_pair_id !== current.mission_pair_id || !previous.stock_principal_raw || !current.stock_principal_raw) return null;
  const prior = BigInt(previous.stock_principal_raw); const next = BigInt(current.stock_principal_raw); const delta = next - prior;
  const oldSupply = previous.stock_total_supply_raw === null ? null : BigInt(previous.stock_total_supply_raw); const newSupply = current.stock_total_supply_raw === null ? null : BigInt(current.stock_total_supply_raw);
  return { delta_id: stableId('locked-stock-delta', previous.observation_id, current.observation_id), mission_pair_id: current.mission_pair_id, token_id: current.token_id!, previous_observation_id: previous.observation_id, current_observation_id: current.observation_id, previous_amount_raw: String(prior), current_amount_raw: String(next), delta_raw: String(delta), delta_pct: prior === 0n ? null : percentage(delta < 0n ? -delta : delta, prior) && `${delta < 0n ? '-' : ''}${percentage(delta < 0n ? -delta : delta, prior)}`, previous_stock_total_supply_raw: oldSupply === null ? null : String(oldSupply), current_stock_total_supply_raw: newSupply === null ? null : String(newSupply), stock_total_supply_delta_raw: oldSupply === null || newSupply === null ? null : String(newSupply - oldSupply), elapsed_ms: Math.max(0, Date.parse(current.observed_at) - Date.parse(previous.observed_at)), previous_range_state: previous.range_state, current_range_state: current.range_state, previous_price_context: previous.sqrt_price_x96, current_price_context: current.sqrt_price_x96, label: 'POSITION INVENTORY CHANGED', methodology_version: REFLEXIVE_METHOD_VERSION, immutable: true };
}

export class PairV5OnchainVerifier {
  private readonly client: Promise<any>;
  constructor(private readonly options: { rpcUrl: string; providerName: string; confirmations?: number; deployments?: typeof PAIR_V5_DEPLOYMENTS; now?: () => Date }) {
    const rpc = options.rpcUrl; this.client = import('viem').then(({ createPublicClient, defineChain, http }) => { const chain = defineChain({ id: REFLEXIVE_CHAIN_ID, name: 'Robinhood Chain', nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 }, rpcUrls: { default: { http: [rpc] } } }); return createPublicClient({ chain, transport: http(rpc, { timeout: 5_000, retryCount: 1, retryDelay: 250 }) }); });
  }
  async verify(candidate: PairDiscoveryCandidate, assets: CanonicalStockAsset[]): Promise<PairVerification> {
    const now = (this.options.now ?? (() => new Date()))().toISOString(); const deployments = this.options.deployments ?? PAIR_V5_DEPLOYMENTS; const failure: VerificationFailure[] = []; const client = await this.client;
    try {
      if (await client.getChainId() !== REFLEXIVE_CHAIN_ID) return this.failed(['CHAIN_ID_MISMATCH']);
      if (!isCanonicalStockContract(assets, candidate.quote_contract)) return this.failed(['NONCANONICAL_STOCK_TOKEN']);
      const required = [deployments.launchpad, deployments.poolManager, deployments.stateView, deployments.hook];
      const codes = await Promise.all(required.map((address) => client.getBytecode({ address: address as `0x${string}` })));
      if (codes.some((code) => !code || code === '0x')) return this.failed(['RPC_UNAVAILABLE']);
      if (candidate.hook && normalizeBlockscoutAddress(candidate.hook) !== normalizeBlockscoutAddress(deployments.hook)) return this.failed(['HOOK_MISMATCH']);
      if (!candidate.launch_tx_hash) return this.failed(['LAUNCHPAD_PROVENANCE_MISSING']);
      const receipt = await client.getTransactionReceipt({ hash: candidate.launch_tx_hash as `0x${string}` }); const transaction = await client.getTransaction({ hash: candidate.launch_tx_hash as `0x${string}` });
      if (receipt.status !== 'success' || !transaction.to || normalizeBlockscoutAddress(transaction.to) !== normalizeBlockscoutAddress(deployments.launchpad)) return this.failed(['LAUNCHPAD_PROVENANCE_MISSING']);
      const latest = await client.getBlockNumber(); const confirmations = this.options.confirmations ?? 3; if (latest < receipt.blockNumber + BigInt(confirmations)) return this.failed(['LAUNCH_TX_UNCONFIRMED']);
      const count = await client.readContract({ address: deployments.launchpad as `0x${string}`, abi: launchpadAbi, functionName: 'getLaunchPoolCount', args: [candidate.mission_contract as `0x${string}`] });
      let registry: { quoteToken: string; poolId: string; positionId: bigint } | null = null;
      for (let index = 0n; index < count; index++) { const pool = await client.readContract({ address: deployments.launchpad as `0x${string}`, abi: launchpadAbi, functionName: 'getLaunchPool', args: [candidate.mission_contract as `0x${string}`, index] }) as unknown as { quoteToken: string; poolId: string; positionId: bigint }; if (normalizeBlockscoutAddress(pool.quoteToken) === normalizeBlockscoutAddress(candidate.quote_contract) && pool.poolId.toLowerCase() === candidate.pool_id.toLowerCase()) { registry = pool; break; } }
      if (!registry) return this.failed(['LAUNCHPAD_PROVENANCE_MISSING']);
      const poolKey = normalizePoolKey(candidate.mission_contract, candidate.quote_contract, 10_000, 200, deployments.hook); const derived = await deriveUniswapV4PoolId(poolKey);
      if (derived.toLowerCase() !== candidate.pool_id.toLowerCase()) return this.failed(['POOL_ID_MISMATCH']);
      let slot0: readonly unknown[]; let liquidity: bigint;
      try { slot0 = await client.readContract({ address: deployments.stateView as `0x${string}`, abi: stateViewAbi, functionName: 'getSlot0', args: [derived] }) as unknown as readonly unknown[]; liquidity = await client.readContract({ address: deployments.stateView as `0x${string}`, abi: stateViewAbi, functionName: 'getLiquidity', args: [derived] }) as bigint; }
      catch { return this.failed(['STATEVIEW_UNAVAILABLE']); }
      if (BigInt(slot0[0] as bigint) === 0n) return this.failed(['POOL_NOT_INITIALIZED']);
      let implementation: string | null = null; try { const implementationStorage = await client.getStorageAt({ address: deployments.launchpad as `0x${string}`, slot: EIP1967_IMPLEMENTATION_SLOT, blockNumber: receipt.blockNumber }); implementation = implementationStorage && implementationStorage.length === 66 ? `0x${implementationStorage.slice(-40)}` : null; } catch { /* provider capability is evidence quality, not market identity */ }
      return { verification_status: 'VERIFIED', failure_reasons: failure, verified_at: now, verification_block: Number(latest), observed_block: Number(receipt.blockNumber), confirmed_block: Number(latest), launch_provenance_method: 'launchpad_registry_and_receipt', launch_implementation_observed: implementation, pool_key: poolKey, state_view_address: normalizeBlockscoutAddress(deployments.stateView), state_observed_block: Number(latest), state_observed_at: now, rpc_provider: this.options.providerName, sqrt_price_x96: String(slot0[0]), tick: Number(slot0[1]), active_liquidity: String(liquidity), position_token_id: registry.positionId > 0n ? String(registry.positionId) : null, position_verification_status: registry.positionId > 0n ? 'VERIFIED_LOCKER_POSITION' : 'POSITION_UNRESOLVED' };
    } catch { return this.failed(['RPC_UNAVAILABLE']); }
  }
  async currentBlock() { return (await this.client).getBlockNumber() as Promise<bigint>; }
  /** A historical eth_call check; full lifecycle backfills remain disabled when it fails. */
  async archiveCapability(poolId: `0x${string}`): Promise<'ARCHIVE_CAPABLE' | 'PROSPECTIVE_ONLY'> {
    try { const client = await this.client; const latest = await client.getBlockNumber(); if (latest < 10_000n) return 'PROSPECTIVE_ONLY'; await client.readContract({ address: (this.options.deployments ?? PAIR_V5_DEPLOYMENTS).stateView as `0x${string}`, abi: stateViewAbi, functionName: 'getSlot0', args: [poolId], blockNumber: latest - 10_000n }); return 'ARCHIVE_CAPABLE'; } catch { return 'PROSPECTIVE_ONLY'; }
  }
  /** Reads the specific PositionManager NFT and the independently-addressed V4 core position at one block. */
  async observeLockedPosition(pair: MissionPair, asset: CanonicalStockAsset, requestedBlock?: bigint): Promise<{ identity: PositionIdentityObservation | null; proof: PositionStateProof | null; observation: LockedInventoryObservation }> {
    const deployments = this.options.deployments ?? PAIR_V5_DEPLOYMENTS; const now = (this.options.now ?? (() => new Date()))().toISOString(); const unavailable = (reason: LockedInventoryObservation['reason']): { identity: null; proof: null; observation: LockedInventoryObservation } => ({ identity: null, proof: null, observation: { observation_id: stableId('locked-inventory-unavailable', pair.pair_id, now, String(reason)), mission_pair_id: pair.pair_id, position_identity_id: null, position_state_proof_id: null, status: 'UNAVAILABLE', accounting_classification: 'UNAVAILABLE', reason, scope: 'CANONICAL_LOCKED_POSITION', method: 'VERIFIED_LOCKED_POSITION_RECONSTRUCTION_V1', token_id: pair.verification.position_token_id, position_manager: normalizeBlockscoutAddress(deployments.positionManager), stock_asset_id: asset.asset_id, stock_symbol: asset.ticker, stock_contract: asset.canonical_contract, stock_decimals: null, mission_principal_raw: null, mission_principal_units: null, stock_principal_raw: null, stock_principal_units: null, stock_share_equivalent_units: null, amount0_raw: null, amount1_raw: null, stock_total_supply_raw: null, stock_total_supply_units: null, stock_total_supply_share_equivalent_units: null, absorption_pct: null, range_state: null, tick_lower: null, tick_upper: null, current_tick: null, sqrt_price_x96: null, position_liquidity_raw: null, core_position_liquidity_raw: null, multiplier: asset.current_multiplier, pending_multiplier: asset.pending_multiplier, pending_multiplier_effective_at: asset.pending_multiplier_effective_at, observed_block: null, observed_at: now, rpc_provider: this.options.providerName, evidence: [{ source: 'Infopunks PositionManager accounting', href: '', observed_at: now, fetched_at: now, note: `Inventory unavailable: ${reason}.`, quality: 'unavailable' }], methodology_version: REFLEXIVE_METHOD_VERSION, immutable: true } });
    const tokenId = pair.verification.position_token_id; if (!tokenId || !pair.verification.pool_key) return unavailable('POSITION_UNRESOLVED');
    try {
      const client = await this.client; const blockNumber = requestedBlock ?? await client.getBlockNumber(); const readAt = { blockNumber };
      const [poolAndInfo, liquidity, owner, slot0, stockDecimals, missionDecimals, totalSupply, block] = await Promise.all([
        client.readContract({ address: deployments.positionManager as `0x${string}`, abi: positionManagerAbi, functionName: 'getPoolAndPositionInfo', args: [BigInt(tokenId)], ...readAt }),
        client.readContract({ address: deployments.positionManager as `0x${string}`, abi: positionManagerAbi, functionName: 'getPositionLiquidity', args: [BigInt(tokenId)], ...readAt }),
        client.readContract({ address: deployments.positionManager as `0x${string}`, abi: positionManagerAbi, functionName: 'ownerOf', args: [BigInt(tokenId)], ...readAt }),
        client.readContract({ address: deployments.stateView as `0x${string}`, abi: stateViewAbi, functionName: 'getSlot0', args: [pair.pool_id as `0x${string}`], ...readAt }),
        client.readContract({ address: asset.canonical_contract as `0x${string}`, abi: erc20Abi, functionName: 'decimals', ...readAt }),
        client.readContract({ address: pair.mission_contract as `0x${string}`, abi: erc20Abi, functionName: 'decimals', ...readAt }),
        client.readContract({ address: asset.canonical_contract as `0x${string}`, abi: erc20Abi, functionName: 'totalSupply', ...readAt }),
        client.getBlock({ blockNumber })
      ]);
      const result = poolAndInfo as readonly [Record<string, unknown>, bigint]; const key = result[0]; const packedInfo = BigInt(result[1]); const returnedKey: PoolKey = { currency0: normalizeBlockscoutAddress(String(key.currency0)), currency1: normalizeBlockscoutAddress(String(key.currency1)), fee: Number(key.fee), tick_spacing: Number(key.tickSpacing), hooks: normalizeBlockscoutAddress(String(key.hooks)) };
      const expected = pair.verification.pool_key; if (JSON.stringify(returnedKey) !== JSON.stringify(expected)) return unavailable('POSITION_POOL_MISMATCH');
      const tickLower = unpackSigned24(packedInfo >> 8n); const tickUpper = unpackSigned24(packedInfo >> 32n); const liquidityRaw = BigInt(liquidity); const locked = normalizeBlockscoutAddress(String(owner)) === normalizeBlockscoutAddress(deployments.locker); const salt = positionTokenIdSalt(tokenId); const observedAt = new Date(Number(block.timestamp) * 1000).toISOString(); const identity: PositionIdentityObservation = { position_identity_id: stableId('position-identity', pair.pair_id, deployments.positionManager.toLowerCase(), tokenId), mission_pair_id: pair.pair_id, pool_id: pair.pool_id, token_id: tokenId, position_manager: normalizeBlockscoutAddress(deployments.positionManager), core_position_owner: normalizeBlockscoutAddress(deployments.positionManager), core_position_salt: salt, nft_owner: normalizeBlockscoutAddress(String(owner)), expected_locker: normalizeBlockscoutAddress(deployments.locker), lock_status: locked ? 'VERIFIED_LOCKED' : 'VERIFIED_NOT_LOCKED', pool_key: returnedKey, tick_lower: tickLower, tick_upper: tickUpper, liquidity_raw: String(liquidityRaw), observed_block: Number(blockNumber), observed_at: observedAt, methodology_version: REFLEXIVE_METHOD_VERSION, immutable: true };
      let corePosition: readonly unknown[] | null = null; try { corePosition = await client.readContract({ address: deployments.stateView as `0x${string}`, abi: stateViewAbi, functionName: 'getPositionInfo', args: [pair.pool_id as `0x${string}`, deployments.positionManager as `0x${string}`, tickLower, tickUpper, salt], ...readAt }) as readonly unknown[]; } catch { /* explicit unavailable proof below; never substitute aggregate liquidity */ }
      const reconciliation = reconcilePositionLiquidity(liquidityRaw, corePosition ? BigInt(corePosition[0] as bigint) : null); const proof: PositionStateProof = { proof_id: stableId('position-state-proof', pair.pair_id, tokenId, String(blockNumber), reconciliation.position_manager_liquidity_raw, reconciliation.v4_core_liquidity_raw ?? 'unavailable'), mission_pair_id: pair.pair_id, pool_id: pair.pool_id, position_manager: identity.position_manager, token_id: tokenId, owner_locker: identity.nft_owner, tick_lower: tickLower, tick_upper: tickUpper, position_manager_liquidity_raw: reconciliation.position_manager_liquidity_raw, v4_core_liquidity_raw: reconciliation.v4_core_liquidity_raw, salt, state_view: normalizeBlockscoutAddress(deployments.stateView), observed_block: Number(blockNumber), observed_at: observedAt, match_status: reconciliation.match_status, methodology_version: REFLEXIVE_METHOD_VERSION, evidence: [{ source: 'Uniswap V4 StateView getPositionInfo', href: `https://robinhoodchain.blockscout.com/address/${deployments.stateView}`, observed_at: observedAt, fetched_at: now, note: 'Core position read with PoolId, PositionManager owner, position ticks and bytes32(tokenId) salt.', quality: corePosition ? 'onchain' : 'unavailable' }], immutable: true };
      if (!locked) return { identity, proof, observation: { ...(unavailable('POSITION_NOT_LOCKED').observation), position_identity_id: identity.position_identity_id, position_state_proof_id: proof.proof_id, token_id: tokenId, observed_block: Number(blockNumber), observed_at: identity.observed_at } };
      if (reconciliation.match_status === 'POSITION_STATE_MISMATCH') return { identity, proof, observation: { ...(unavailable('POSITION_STATE_MISMATCH').observation), position_identity_id: identity.position_identity_id, position_state_proof_id: proof.proof_id, token_id: tokenId, observed_block: Number(blockNumber), observed_at: observedAt, position_liquidity_raw: String(liquidityRaw), core_position_liquidity_raw: reconciliation.v4_core_liquidity_raw } };
      if (reconciliation.match_status === 'CORE_POSITION_UNAVAILABLE') return { identity, proof, observation: { ...(unavailable('CORE_POSITION_UNAVAILABLE').observation), position_identity_id: identity.position_identity_id, position_state_proof_id: proof.proof_id, token_id: tokenId, observed_block: Number(blockNumber), observed_at: observedAt, position_liquidity_raw: String(liquidityRaw) } };
      const current = slot0 as readonly unknown[]; const principal = reconstructPositionPrincipal(liquidityRaw, tickLower, tickUpper, BigInt(current[0] as bigint)); const stockIsCurrency0 = returnedKey.currency0 === asset.canonical_contract; const stockRaw = stockIsCurrency0 ? principal.amount0 : principal.amount1; const missionRaw = stockIsCurrency0 ? principal.amount1 : principal.amount0; const stockUnits = formatTokenUnits(stockRaw, Number(stockDecimals)); const stockShareEquivalent = decimalProduct(stockRaw, Number(stockDecimals), asset.current_multiplier); const supplyRaw = BigInt(totalSupply);
      const observation: LockedInventoryObservation = { observation_id: stableId('locked-inventory', pair.pair_id, String(blockNumber), String(stockRaw), String(supplyRaw)), mission_pair_id: pair.pair_id, position_identity_id: identity.position_identity_id, position_state_proof_id: proof.proof_id, status: supplyRaw > 0n && stockShareEquivalent !== null ? 'AVAILABLE' : 'UNAVAILABLE', accounting_classification: supplyRaw > 0n && stockShareEquivalent !== null ? 'VERIFIED_POSITION_ACCOUNTING' : 'UNAVAILABLE', reason: supplyRaw > 0n && stockShareEquivalent !== null ? null : 'ZERO_STOCK_SUPPLY', scope: 'CANONICAL_LOCKED_POSITION', method: 'VERIFIED_LOCKED_POSITION_RECONSTRUCTION_V1', token_id: tokenId, position_manager: identity.position_manager, stock_asset_id: asset.asset_id, stock_symbol: asset.ticker, stock_contract: asset.canonical_contract, stock_decimals: Number(stockDecimals), mission_principal_raw: String(missionRaw), mission_principal_units: formatTokenUnits(missionRaw, Number(missionDecimals)), stock_principal_raw: String(stockRaw), stock_principal_units: stockUnits, stock_share_equivalent_units: stockShareEquivalent, amount0_raw: String(principal.amount0), amount1_raw: String(principal.amount1), stock_total_supply_raw: String(supplyRaw), stock_total_supply_units: formatTokenUnits(supplyRaw, Number(stockDecimals)), stock_total_supply_share_equivalent_units: decimalProduct(supplyRaw, Number(stockDecimals), asset.current_multiplier), absorption_pct: supplyRaw > 0n ? percentage(stockRaw, supplyRaw) : null, range_state: principal.range_state, tick_lower: tickLower, tick_upper: tickUpper, current_tick: Number(current[1]), sqrt_price_x96: String(current[0]), position_liquidity_raw: String(liquidityRaw), core_position_liquidity_raw: reconciliation.v4_core_liquidity_raw, multiplier: asset.current_multiplier, pending_multiplier: asset.pending_multiplier, pending_multiplier_effective_at: asset.pending_multiplier_effective_at, observed_block: Number(blockNumber), observed_at: observedAt, rpc_provider: this.options.providerName, evidence: [{ source: 'Uniswap V4 PositionManager', href: `https://robinhoodchain.blockscout.com/address/${deployments.positionManager}`, observed_at: observedAt, fetched_at: now, note: 'NFT owner, PoolKey, ticks and specific position liquidity were read onchain.', quality: 'onchain' }, { source: 'Uniswap V4 StateView + canonical ERC-20', href: `https://robinhoodchain.blockscout.com/address/${deployments.stateView}`, observed_at: observedAt, fetched_at: now, note: 'Core position liquidity, current slot0 and exact canonical Stock Token totalSupply were read at the observation block.', quality: 'onchain' }], methodology_version: REFLEXIVE_METHOD_VERSION, immutable: true };
      return { identity, proof, observation };
    } catch { return unavailable('RPC_UNAVAILABLE'); }
  }
  private failed(reasons: VerificationFailure[]): PairVerification { return { verification_status: reasons.includes('PAIR_API_ONLY') ? 'CANDIDATE' : 'PARTIALLY_VERIFIED', failure_reasons: reasons, verified_at: null, verification_block: null, observed_block: null, confirmed_block: null, launch_provenance_method: null, launch_implementation_observed: null, pool_key: null, state_view_address: null, state_observed_block: null, state_observed_at: null, rpc_provider: this.options.providerName, sqrt_price_x96: null, tick: null, active_liquidity: null, position_token_id: null, position_verification_status: 'NOT_ATTEMPTED' }; }
}

export function normalizeShareEquivalent(raw: string | number, multiplier: string | number): string { const result = Number(raw) * Number(multiplier); return Number.isFinite(result) ? String(result) : '0'; }
export function missionAlpha(missionStart: number, missionEnd: number, underlyingStart: number, underlyingEnd: number): number | null { if ([missionStart, missionEnd, underlyingStart, underlyingEnd].some((n) => !Number.isFinite(n) || n <= 0)) return null; return (missionEnd / missionStart) / (underlyingEnd / underlyingStart) - 1; }
export function stockTokenBasis(dexPrice: number | null, rawUnderlyingPrice: number | null, multiplier: string | number, dexAt: string | null, referenceAt: string | null, maxSkewMs = 120_000): number | null { if (!dexPrice || !rawUnderlyingPrice || !dexAt || !referenceAt || !Number.isFinite(Number(multiplier))) return null; if (Math.abs(Date.parse(dexAt) - Date.parse(referenceAt)) > maxSkewMs) return null; const tokenReference = rawUnderlyingPrice / Number(multiplier); return tokenReference > 0 ? dexPrice / tokenReference - 1 : null; }
export function isCanonicalStockContract(assets: readonly CanonicalStockAsset[], contract: string): boolean { const normalized = normalizeBlockscoutAddress(contract); return assets.some((asset) => asset.chain_id === REFLEXIVE_CHAIN_ID && asset.canonical_contract === normalized && asset.status === 'ASSET_STATUS_ACTIVE'); }
/** Operationally diverse, deliberately small inventory cohort. Discovery records remain intact; only expensive accounting is bounded. */
export function selectControlledBootstrapCohort(pairs: MissionPair[], assets: CanonicalStockAsset[]): MissionPair[] {
  const verified = pairs.filter((pair) => pair.canonicality === 'verified' && pair.verification.verification_status === 'VERIFIED'); const selected: MissionPair[] = [];
  const add = (pair: MissionPair) => { if (!selected.some((item) => item.pair_id === pair.pair_id)) selected.push(pair); };
  const aapl = assets.find((asset) => asset.ticker === 'AAPL'); const pear = verified.find((pair) => pair.mission_symbol.toUpperCase() === 'PEAR' && pair.stock_asset_id === aapl?.asset_id); if (pear) add(pear);
  const groups = new Map<string, MissionPair[]>(); for (const pair of verified) { const key = pair.launch_group_id; groups.set(key, [...(groups.get(key) ?? []), pair]); }
  const multipool = [...groups.values()].filter((group) => new Set(group.map((pair) => pair.stock_asset_id)).size >= 2).sort((a, b) => a[0].launched_at.localeCompare(b[0].launched_at))[0]; if (multipool) for (const pair of multipool) add(pair);
  const single = verified.filter((pair) => (groups.get(pair.launch_group_id)?.length ?? 0) === 1).sort((a, b) => a.launched_at.localeCompare(b.launched_at))[0]; if (single) add(single);
  return selected;
}
/** V4 singleton balances are intentionally never accepted as pool inventory. */
export function quoteInventory(raw: string | null, multiplier: string, method: PairObservation['inventory_method']) { return method === 'unavailable' || raw === null ? { raw: null, share_equivalent: null, method: 'unavailable' as const } : { raw, share_equivalent: normalizeShareEquivalent(raw, multiplier), method }; }
export function stableId(...parts: string[]) { return createHash('sha256').update(parts.join('|')).digest('hex').slice(0, 32); }

export class ReflexiveRadarService {
  constructor(private readonly store: ReflexiveStore, private readonly provider: ReflexiveProvider, private readonly now = () => new Date()) {}
  async refresh() {
    const prior = await this.store.load(); const fetchedAt = this.now().toISOString(); const assets = normalizeAssets(await this.provider.assets(), fetchedAt);
    const candidates = await this.provider.discover?.(assets, prior.cursor) ?? [];
    const pairs = dedupePairs([...prior.pairs, ...candidates.map((candidate) => candidateToPair(candidate, assets)).filter((pair): pair is MissionPair => Boolean(pair))]);
    const cohort = selectControlledBootstrapCohort(pairs, assets);
    const newlyObserved = await this.provider.observations?.(cohort, assets) ?? [];
    const inventory = await this.provider.inventory?.(cohort, assets) ?? { identities: [], proofs: [], observations: [] };
    // Observation ids include timestamp; previously published market state is never overwritten.
    const observations = dedupeObservations([...prior.observations, ...newlyObserved]);
    const supplyEvents = dedupeSupplyEvents([...prior.supply_events, ...await this.provider.supplyEvents?.(assets) ?? []]);
    const positionIdentities = dedupePositionIdentities([...prior.position_identities, ...inventory.identities]);
    const positionStateProofs = dedupePositionStateProofs([...prior.position_state_proofs, ...inventory.proofs]);
    const inventoryObservations = dedupeInventoryObservations([...prior.inventory_observations, ...inventory.observations]);
    const births = [...prior.births, ...cohort.filter((pair) => pair.verification.verification_status === 'VERIFIED' && !prior.births.some((birth) => birth.mission_pair_id === pair.pair_id)).map((pair) => birthRecord(pair, assets, fetchedAt))];
    const currentAggregates = assets.map((asset) => aggregateTrackedPairInventory(asset, inventoryObservations));
    const inventoryAggregates = dedupeInventoryAggregates([...prior.inventory_aggregates, ...currentAggregates]);
    const inventoryDeltas = dedupeInventoryDeltas([...prior.inventory_deltas, ...deriveInventoryDeltas(inventoryObservations)]);
    const baselines = appendInventoryBaselines(prior.inventory_baselines, inventoryObservations, births);
    const events = evaluateEvents(pairs, observations, supplyEvents, prior.events, currentAggregates);
    const thesis = evaluateThesis(pairs, observations, events, fetchedAt);
    const lifecycle = updateLifecycle([...prior.lifecycle], pairs, observations, fetchedAt);
    const snapshot: ReflexiveSnapshot = { assets, pairs, births, lifecycle, observations, position_identities: positionIdentities, position_state_proofs: positionStateProofs, inventory_observations: inventoryObservations, inventory_aggregates: inventoryAggregates, inventory_deltas: inventoryDeltas, inventory_baselines: baselines, supply_events: supplyEvents, events, thesis, refreshed_at: fetchedAt, cursor: prior.cursor };
    await this.store.save(snapshot); return snapshot;
  }
  async snapshot() { return this.store.load(); }
  async pair(pairId: string) { return (await this.store.load()).pairs.find((pair) => pair.pair_id === pairId) ?? null; }
  async stock(ticker: string) { const snapshot = await this.store.load(); const asset = snapshot.assets.find((item) => item.ticker.toUpperCase() === ticker.toUpperCase()); if (!asset) return null; const pairs = snapshot.pairs.filter((pair) => pair.stock_asset_id === asset.asset_id); const inventory = snapshot.inventory_observations.filter((item) => item.stock_asset_id === asset.asset_id && item.status === 'AVAILABLE'); const aggregate = [...snapshot.inventory_aggregates].filter((item) => item.stock_asset_id === asset.asset_id).sort((a, b) => (b.reference_time ?? '').localeCompare(a.reference_time ?? ''))[0] ?? aggregateTrackedPairInventory(asset, snapshot.inventory_observations); return { asset, pairs, observations: snapshot.observations.filter((item) => pairs.some((pair) => pair.pair_id === item.pair_id)), inventory_observations: inventory, tracked_pair_locked_inventory: aggregate, tracked_position_inventory: aggregate.raw_stock_token_units, tracked_absorption_pct: aggregate.tracked_pair_locked_absorption_pct, verified_position_count: aggregate.position_count, aggregation_status: aggregate.status, supply_events: snapshot.supply_events.filter((item) => item.asset_id === asset.asset_id), net_quote_demand: 'NOT_YET_ATTRIBUTABLE' as const }; }
}

function normalizeAssets(payload: unknown, fetchedAt: string): CanonicalStockAsset[] {
  const rows = Array.isArray(payload) ? payload : isRecord(payload) && Array.isArray(payload.assets) ? payload.assets : [];
  return rows.flatMap((value) => { const item = value as RobinhoodAsset; const id = string(item.id); const ticker = string(item.tokenSymbol); const deployments = Array.isArray(item.deployments) ? item.deployments : []; if (!id || !ticker) return []; return deployments.flatMap((deployment) => { const row = deployment as Record<string, unknown>; const chain = Number(row.chainId); const contract = string(row.contractAddress); if (chain !== REFLEXIVE_CHAIN_ID || !isAddress(contract)) return []; return [{ asset_id: id.toLowerCase(), ticker: ticker.toUpperCase(), name: string(item.tokenName) ?? ticker, chain_id: chain, canonical_contract: normalizeBlockscoutAddress(contract), status: string(item.status) ?? 'ASSET_STATUS_UNSPECIFIED', current_multiplier: string(item.currentMultiplier) ?? '1', pending_multiplier: string(item.pendingMultiplier), pending_multiplier_effective_at: string(item.pendingMultiplierEffectiveTime), trading_capabilities: isRecord(item.tradingCapabilities) ? item.tradingCapabilities : null, logo: string(item.logoUrl), observed_at: fetchedAt, fetched_at: fetchedAt, provenance: 'Robinhood RHJ /assets + chain 4663 deployment', first_party_asset: false }]; }); });
}
function candidateToPair(candidate: PairDiscoveryCandidate, assets: CanonicalStockAsset[]): MissionPair | null { if (!isCanonicalStockContract(assets, candidate.quote_contract) || !isAddress(candidate.mission_contract) || !candidate.pool_id || candidate.onchain?.verification_status !== 'VERIFIED') return null; const asset = assets.find((item) => item.canonical_contract === normalizeBlockscoutAddress(candidate.quote_contract)); if (!asset) return null; const pool = candidate.pool_id.toLowerCase(); const launch = candidate.launch_id ?? stableId(candidate.protocol, pool, candidate.mission_contract, asset.canonical_contract, candidate.launched_at); return { pair_id: stableId(String(REFLEXIVE_CHAIN_ID), candidate.protocol, pool, candidate.mission_contract.toLowerCase(), asset.canonical_contract, candidate.venue, candidate.launched_at), launch_id: launch, launch_group_id: stableId('launch-group', candidate.mission_contract.toLowerCase(), candidate.launch_tx_hash ?? launch), chain_id: REFLEXIVE_CHAIN_ID, protocol: candidate.protocol, venue: candidate.venue, pool_id: pool, pool_address: candidate.pool_address ? normalizeBlockscoutAddress(candidate.pool_address) : null, mission_contract: normalizeBlockscoutAddress(candidate.mission_contract), mission_symbol: candidate.mission_symbol, stock_asset_id: asset.asset_id, quote_contract: asset.canonical_contract, launched_at: candidate.launched_at, launch_block: candidate.onchain.observed_block ?? candidate.launch_block ?? null, canonicality: 'verified', first_party_asset: Boolean(candidate.first_party_asset), fee_policy: candidate.fee_policy ?? null, evidence: candidate.evidence, verification: candidate.onchain }; }
function evaluateEvents(pairs: MissionPair[], observations: PairObservation[], supply: StockSupplyEvent[], prior: ReflexivityEvent[], aggregates: TrackedStockInventoryAggregate[]) { const generated: ReflexivityEvent[] = []; for (const pair of pairs) { generated.push({ event_id: stableId('birth', pair.pair_id), event_type: 'NEW_STOCK_PAIRED_MARKET', subject_id: pair.pair_id, occurred_at: pair.launched_at, trigger_version: REFLEXIVE_METHOD_VERSION, trigger: 'verified canonical quote contract plus onchain-verifiable pool identity', evidence_ids: pair.evidence.map((item) => stableId(item.href, item.observed_at)) }); }
  for (const event of supply) generated.push({ event_id: stableId(event.event_type, event.event_id), event_type: event.event_type === 'mint' ? 'STOCK_SUPPLY_MINT' : event.event_type === 'burn' ? 'STOCK_SUPPLY_BURN' : 'SUPPLY_RESPONSE_AFTER_STRESS', subject_id: event.asset_id, occurred_at: event.timestamp, trigger_version: REFLEXIVE_METHOD_VERSION, trigger: `canonical Stock Token ${event.event_type} observation`, evidence_ids: [event.event_id] });
  for (const aggregate of aggregates) { const percent = Number(aggregate.tracked_pair_locked_absorption_pct); if (aggregate.status !== 'ALIGNED' || !Number.isFinite(percent) || !aggregate.reference_time) continue; for (const threshold of TRACKED_PAIR_ABSORPTION_THRESHOLDS) if (percent >= threshold) generated.push({ event_id: stableId('quote-absorption', aggregate.aggregate_observation_id, String(threshold)), event_type: 'QUOTE_ABSORPTION_MILESTONE', subject_id: aggregate.stock_asset_id, occurred_at: aggregate.reference_time, trigger_version: TRACKED_PAIR_ABSORPTION_THRESHOLDS_VERSION, trigger: `tracked PAIR canonical locked positions exceed ${threshold}% of Robinhood onchain ${aggregate.stock_symbol} token supply`, evidence_ids: aggregate.included_observation_ids }); }
  return [...prior, ...generated].filter((item, index, list) => list.findIndex((other) => other.event_id === item.event_id) === index).sort((a, b) => b.occurred_at.localeCompare(a.occurred_at));
}
function birthRecord(pair: MissionPair, assets: CanonicalStockAsset[], recordedAt: string): PairBirthRecord {
  const asset = assets.find((item) => item.asset_id === pair.stock_asset_id); const verification = pair.verification; if (!asset || !verification.pool_key || !verification.observed_block || !pair.launch_id) throw new Error('verified_birth_identity_incomplete');
  return { birth_id: stableId('birth-record', pair.pair_id), mission_pair_id: pair.pair_id, launch_group_id: pair.launch_group_id, chain_id: pair.chain_id, mission_contract: pair.mission_contract, mission_symbol: pair.mission_symbol, quote_contract: pair.quote_contract, quote_ticker: asset.ticker, rh_asset_id: asset.asset_id, venue: 'PAIR', venue_version: 'V5', launchpad_proxy: PAIR_V5_DEPLOYMENTS.launchpad.toLowerCase(), launch_implementation: verification.launch_implementation_observed, pool_key: verification.pool_key, pool_id: pair.pool_id, pool_manager: PAIR_V5_DEPLOYMENTS.poolManager.toLowerCase(), hook: verification.pool_key.hooks, fee: verification.pool_key.fee, tickSpacing: verification.pool_key.tick_spacing, launch_tx: pair.launch_id, launch_block: verification.observed_block, launch_timestamp: pair.launched_at, discovery_source: 'PAIR /api/tokens → independent onchain verification', canonical_evidence: pair.evidence, birth_recorded_at: recordedAt, methodology_version: REFLEXIVE_METHOD_VERSION, immutable: true };
}
const checkpointOffsets: Array<[LifecycleCheckpoint['checkpoint'], number]> = [['T10M', 10 * 60_000], ['T1H', 60 * 60_000], ['T6H', 6 * 60 * 60_000], ['T24H', 24 * 60 * 60_000], ['D3', 3 * 24 * 60 * 60_000], ['D7', 7 * 24 * 60 * 60_000], ['D30', 30 * 24 * 60 * 60_000]];
function updateLifecycle(existing: LifecycleCheckpoint[], pairs: MissionPair[], observations: PairObservation[], now: string) {
  const nowMs = Date.parse(now); const output = [...existing]; for (const pair of pairs) for (const [checkpoint, offset] of checkpointOffsets) { const id = stableId('checkpoint', pair.pair_id, checkpoint); if (output.some((item) => item.checkpoint_id === id)) continue; const target = Date.parse(pair.launched_at) + offset; const tolerance = checkpoint === 'T10M' ? 3 * 60_000 : Math.min(60 * 60_000, Math.round(offset * .1)); const candidate = observations.filter((item) => item.pair_id === pair.pair_id).map((item) => ({ item, distance: Math.abs(Date.parse(item.observed_at) - target) })).filter((item) => item.distance <= tolerance).sort((a, b) => a.distance - b.distance)[0]; const state: LifecycleCheckpoint['state'] = candidate ? 'OBSERVED' : nowMs > target + tolerance ? 'MISSED' : 'PENDING'; output.push({ checkpoint_id: id, pair_id: pair.pair_id, checkpoint, target_at: new Date(target).toISOString(), state, actual_observation_id: candidate?.item.observation_id ?? null, actual_observed_at: candidate?.item.observed_at ?? null, distance_ms: candidate?.distance ?? null, source_completeness: candidate ? 'partial' : 'unavailable' }); }
  return output;
}
function evaluateThesis(pairs: MissionPair[], observations: PairObservation[], events: ReflexivityEvent[], at: string): ThesisEvidence[] { const active = pairs.filter((pair) => pair.canonicality === 'verified').length; const complete = observations.filter((observation) => observation.fresh && observation.volume_24h_usd !== null).length; const state: ThesisState = active && complete ? 'SUPPORTING' : active ? 'MIXED' : 'INSUFFICIENT_DATA'; const h1: ThesisEvidence = { hypothesis_id: 'H1', state, rule_version: REFLEXIVE_METHOD_VERSION, rationale: active ? `${active} verified Stock-quoted market(s); volume completeness is ${complete}/${active}.` : 'No verified stock-paired market has been persisted.', evidence_ids: events.filter((event) => event.event_type === 'NEW_STOCK_PAIRED_MARKET').map((event) => event.event_id), observed_at: at }; return [h1, { hypothesis_id: 'H2', state: observations.some((item) => item.inventory_method !== 'unavailable') ? 'MIXED' : 'INSUFFICIENT_DATA', rule_version: REFLEXIVE_METHOD_VERSION, rationale: 'Persistent pool-specific inventory requires a defensible per-pool method; PoolManager balances are excluded.', evidence_ids: [], observed_at: at }, ...['H3', 'H4', 'H5', 'H6'].map((hypothesis_id) => ({ hypothesis_id: hypothesis_id as ThesisEvidence['hypothesis_id'], state: 'INSUFFICIENT_DATA' as ThesisState, rule_version: REFLEXIVE_METHOD_VERSION, rationale: hypothesis_id === 'H6' ? 'No defensible matched non-stock control cohort yet.' : 'Lifecycle evidence is not yet sufficient for a deterministic state.', evidence_ids: [], observed_at: at }))]; }
function defaultThesis(): ThesisEvidence[] { return evaluateThesis([], [], [], new Date(0).toISOString()); }
function deriveInventoryDeltas(items: LockedInventoryObservation[]) { const groups = new Map<string, LockedInventoryObservation[]>(); for (const item of items) { if (!item.token_id) continue; const key = `${item.mission_pair_id}|${item.token_id}`; groups.set(key, [...(groups.get(key) ?? []), item]); } return [...groups.values()].flatMap((group) => { const ordered = [...group].sort((a, b) => a.observed_at.localeCompare(b.observed_at)); return ordered.slice(1).flatMap((current, index) => { const delta = derivePositionInventoryDelta(ordered[index], current); return delta ? [delta] : []; }); }); }
function appendInventoryBaselines(existing: InventoryBaseline[], observations: LockedInventoryObservation[], births: PairBirthRecord[]) { const output = [...existing]; for (const birth of births) { if (output.some((item) => item.mission_pair_id === birth.mission_pair_id)) continue; const first = observations.filter((item) => item.mission_pair_id === birth.mission_pair_id && item.status === 'AVAILABLE' && item.accounting_classification === 'VERIFIED_POSITION_ACCOUNTING').sort((a, b) => a.observed_at.localeCompare(b.observed_at))[0]; if (first) output.push({ mission_pair_id: birth.mission_pair_id, inventory_baseline_observation_id: first.observation_id, recorded_at: first.observed_at, methodology_version: REFLEXIVE_METHOD_VERSION, immutable: true }); } return output; }
function dedupePairs(items: MissionPair[]) { return items.filter((item, index, list) => list.findIndex((other) => other.pair_id === item.pair_id) === index); }
function dedupeObservations(items: PairObservation[]) { return items.filter((item, index, list) => list.findIndex((other) => other.observation_id === item.observation_id) === index); }
function dedupeSupplyEvents(items: StockSupplyEvent[]) { return items.filter((item, index, list) => list.findIndex((other) => other.event_id === item.event_id) === index); }
function dedupePositionIdentities(items: PositionIdentityObservation[]) { return items.filter((item, index, list) => list.findIndex((other) => other.position_identity_id === item.position_identity_id) === index); }
function dedupePositionStateProofs(items: PositionStateProof[]) { return items.filter((item, index, list) => list.findIndex((other) => other.proof_id === item.proof_id) === index); }
function dedupeInventoryObservations(items: LockedInventoryObservation[]) { return items.filter((item, index, list) => list.findIndex((other) => other.observation_id === item.observation_id) === index); }
function dedupeInventoryAggregates(items: TrackedStockInventoryAggregate[]) { return items.filter((item, index, list) => list.findIndex((other) => other.aggregate_observation_id === item.aggregate_observation_id) === index); }
function dedupeInventoryDeltas(items: PositionInventoryDelta[]) { return items.filter((item, index, list) => list.findIndex((other) => other.delta_id === item.delta_id) === index); }
function string(value: unknown) { return typeof value === 'string' && value.trim() ? value.trim() : null; }
function isRecord(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function isAddress(value: string | null): value is string { return Boolean(value && /^0x[0-9a-fA-F]{40}$/.test(value)); }
function unixToIso(value: unknown) { const seconds = Number(value); return Number.isFinite(seconds) && seconds > 0 ? new Date(seconds * 1_000).toISOString() : null; }
