import { createHash, randomUUID } from 'node:crypto';
import pg from 'pg';
import { z } from 'zod';
import { resolvePostgresPool, type PostgresPoolSource } from '../persistence/retryablePostgresSchema';

/** Contract-first project claims. Identity, claims, evidence, observations and verdicts stay distinct. */
export const RH_CHAIN_PROJECT_IDENTITY_STATES = ['submitted', 'identity_unverified', 'identity_partially_verified', 'identity_verified', 'disputed', 'rejected', 'archived'] as const;
export const RH_CHAIN_PROJECT_CLAIM_STATES = ['submitted', 'queued', 'under_review', 'evidence_required', 'partially_supported', 'supported', 'contradicted', 'disputed', 'rejected', 'expired', 'superseded', 'archived'] as const;
export const RH_CHAIN_PROJECT_EVIDENCE_SOURCES = ['project_submitted', 'public_project_source', 'onchain_observation', 'provider_observation', 'independent_public_source', 'reviewed_infopunks_observation', 'unknown'] as const;
export const RH_CHAIN_PROJECT_EVIDENCE_STATUSES = ['submitted', 'accessible', 'inaccessible', 'source_required', 'corroborated', 'contradicted', 'stale', 'withdrawn', 'disputed', 'superseded'] as const;
export const RH_CHAIN_PROJECT_OBSERVATION_STATES = ['draft', 'source_required', 'reviewed', 'disputed', 'superseded', 'archived'] as const;
export const RH_CHAIN_PROJECT_VERDICT_STATES = ['draft', 'under_review', 'approved_for_publication', 'published', 'rejected', 'disputed', 'superseded', 'archived'] as const;
export const RH_CHAIN_PROJECT_RECEIPT_TYPES = ['project_identity', 'product_status', 'launch', 'market_activity', 'attention_quality', 'integration', 'RWA', 'agent_claim', 'revenue', 'security', 'full_project_verdict'] as const;
export const RH_CHAIN_PROJECT_CLAIM_CATEGORIES = ['identity', 'product_live', 'contract_ownership', 'protocol_integration', 'RWA_integration', 'stablecoin_integration', 'lending_integration', 'liquidity', 'users', 'transaction_activity', 'volume', 'revenue', 'fees', 'treasury', 'launch', 'security', 'audit', 'agent_activity', 'agent_autonomy', 'partnership', 'roadmap', 'governance', 'disclosure', 'other'] as const;
export const RH_CHAIN_CONTRACT_RELATIONSHIP_TYPES = ['primary', 'token', 'product', 'protocol', 'treasury', 'liquidity', 'executor', 'deprecated', 'unknown'] as const;
export const RH_CHAIN_CONTRACT_RELATIONSHIP_STATES = ['submitted', 'reviewed', 'verified', 'disputed', 'rejected', 'superseded'] as const;

const contract = z.string().trim().regex(/^0x[0-9a-fA-F]{40}$/, 'exact_rh_chain_contract_required').transform((value) => value.toLowerCase());
const url = z.string().trim().url().max(1000).refine((value) => ['https:', 'http:'].includes(new URL(value).protocol), 'unsupported_url_scheme');
const text = z.string().trim().min(1).max(4000);
const id = z.string().trim().min(1).max(128).regex(/^[A-Za-z0-9._:-]+$/);
const timestamp = z.string().datetime();
const confidence = z.enum(['low', 'medium', 'high']);
const source = z.enum(RH_CHAIN_PROJECT_EVIDENCE_SOURCES);
const version = z.number().int().positive();

export const RhChainProjectSubmissionSchema = z.object({
  project_name: z.string().trim().min(1).max(160), chain: z.literal('robinhood').default('robinhood'), exact_contract: contract,
  contact: z.string().trim().min(3).max(320), claim_category: z.enum(RH_CHAIN_PROJECT_CLAIM_CATEGORIES), claim_statement: text,
  supporting_evidence: z.array(url).min(1).max(12), disclosure_accepted: z.literal(true), authority_to_submit_confirmed: z.literal(true), privacy_consent: z.boolean().optional().default(false),
  website: url.optional(), documentation: url.optional(), socials: z.array(url).max(8).optional().default([]), additional_contracts: z.array(contract).max(20).optional().default([]), structured_claim_values: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()])).optional().default({}), notes: z.string().trim().max(2000).optional()
}).strict();
export type RhChainProjectSubmission = z.infer<typeof RhChainProjectSubmissionSchema>;

export type RhChainProject = { project_id: string; chain: 'robinhood'; primary_contract: string; additional_contracts: string[]; canonical_display_name: string; canonical_slug: string; ticker: string | null; project_type: string | null; reviewed_classification_reference: string | null; identity_status: typeof RH_CHAIN_PROJECT_IDENTITY_STATES[number]; official_website: string | null; official_documentation: string | null; official_social_accounts: string[]; team_operator_disclosures: string | null; first_observed_at: string; last_reviewed_at: string | null; provenance: string; schema_version: 1; version: number; created_at: string; updated_at: string; archived_at: string | null };
export type RhChainContractRelationship = { relationship_id: string; project_id: string; chain: 'robinhood'; exact_contract: string; relationship_type: typeof RH_CHAIN_CONTRACT_RELATIONSHIP_TYPES[number]; verification_state: typeof RH_CHAIN_CONTRACT_RELATIONSHIP_STATES[number]; evidence_references: string[]; reviewed_at: string | null; superseded_at: string | null; superseded_by_relationship_id: string | null; rejection_reason: string | null; version: number; schema_version: 1; created_at: string; updated_at: string };
export type RhChainProjectClaim = { claim_id: string; project_id: string; chain: 'robinhood'; exact_contract_context: string; claim_category: typeof RH_CHAIN_PROJECT_CLAIM_CATEGORIES[number]; claim_text: string; structured_claim_payload: Record<string, string | number | boolean | null>; submitter_type: 'project' | 'reviewer'; submitter_identifier: string; submitted_at: string; evidence_references: string[]; claim_status: typeof RH_CHAIN_PROJECT_CLAIM_STATES[number]; reviewer_state: 'unreviewed' | 'reviewed'; confidence: z.infer<typeof confidence> | null; effective_period: { start: string | null; end: string | null }; review_after_at: string | null; correction_history: Array<{ at: string; reason: string; receipt_id?: string }>; superseded_at: string | null; schema_version: 1; version: number };
export type RhChainProjectEvidence = { evidence_id: string; project_id: string; claim_id: string | null; target_type?: 'project_identity' | 'contract_relationship' | 'claim' | 'observation' | 'verdict' | 'receipt'; target_id?: string | null; evidence_type: string; source_class: z.infer<typeof source>; url: string | null; transaction_hash: string | null; block_number: string | null; contract: string | null; wallet: string | null; document_reference: string | null; market_snapshot_id: string | null; attention_quality_assessment_id: string | null; reviewed_classification_id: string | null; receipt_id: string | null; submitted_at: string; observed_at: string | null; fetched_at: string | null; freshness: 'fresh' | 'stale' | 'unknown'; confidence?: z.infer<typeof confidence> | null; content_hash: string | null; evidence_status: typeof RH_CHAIN_PROJECT_EVIDENCE_STATUSES[number]; public_summary?: string | null; reviewer_notes: string | null; provenance: string; schema_version: 1; version: number; superseded_at?: string | null; superseded_by_evidence_id?: string | null };
export type RhChainProjectObservation = { observation_id: string; project_id: string; exact_contract: string; observation_category: string; observation_statement: string; structured_measured_values: Record<string, string | number | boolean | null>; observation_window: { start: string | null; end: string | null }; source_inventory: string[]; evidence_references: string[]; confidence: z.infer<typeof confidence>; freshness: 'fresh' | 'stale' | 'unknown'; methodology_version: string; analyst_review_status: typeof RH_CHAIN_PROJECT_OBSERVATION_STATES[number]; created_at: string; superseded_at: string | null; version: number };
export type RhChainProjectVerdict = { verdict_id: string; project_id: string; verdict_type: string; verdict_statement: string; verdict_state: typeof RH_CHAIN_PROJECT_VERDICT_STATES[number]; supported_claim_ids: string[]; partially_supported_claim_ids: string[]; contradicted_claim_ids: string[]; unknown_claim_ids: string[]; disputed_claim_ids: string[]; evidence_inventory: string[]; observation_inventory: string[]; confidence: z.infer<typeof confidence>; limitations: string[]; draft_at: string; published_at: string | null; rejection_reason?: string | null; rejected_at?: string | null; methodology_version: string; superseded_at: string | null; replacement_receipt_id: string | null; version: number };
export type RhChainIntelligenceReceipt = { receipt_id: string; receipt_type: typeof RH_CHAIN_PROJECT_RECEIPT_TYPES[number]; project_id: string; chain: 'robinhood'; exact_contract_identity: string; canonical_project_name: string; publication_timestamp: string | null; observation_window: { start: string | null; end: string | null }; verdict: string; verdict_confidence: z.infer<typeof confidence>; claim_inventory: string[]; claim_states: Record<string, typeof RH_CHAIN_PROJECT_CLAIM_STATES[number]>; observation_inventory: string[]; evidence_inventory: string[]; reviewed_classification_reference: string | null; market_snapshot_references: string[]; attention_quality_reference: string | null; inclusion_totals: number; exclusion_totals: number; unknowns: string[]; disputes: string[]; stale_sources: string[]; methodology_version: string; reviewer_publication_state: 'draft' | 'approved_for_publication' | 'published' | 'rejected' | 'superseded'; rejection_reason?: string | null; rejected_at?: string | null; correction_history: Array<{ at: string; reason: string; replacement_receipt_id: string | null }>; superseded_receipt_id: string | null; replacement_receipt_id: string | null; integrity_hash: string | null; not_financial_advice: true; schema_version: 1; version: number; created_at: string; updated_at: string };
export type RhChainProjectAudit = { audit_id: string; project_id: string; action: string; reviewer_id: string | null; at: string; reason: string; payload: Record<string, unknown> };
type Page<T> = { items: T[]; next_cursor: string | null };

export interface RhChainProjectClaimsStore { readonly adapter: 'memory' | 'postgres'; readonly durable: boolean; saveProject(value: RhChainProject): Promise<void>; getProject(id: string): Promise<RhChainProject | null>; findProjectByContract(c: string): Promise<RhChainProject | null>; listProjects(cursor: string | undefined, limit: number): Promise<Page<RhChainProject>>; saveRelationship(value: RhChainContractRelationship): Promise<void>; getRelationship(id: string): Promise<RhChainContractRelationship | null>; relationships(projectId: string): Promise<RhChainContractRelationship[]>; findActiveRelationship(chain: 'robinhood', exactContract: string): Promise<RhChainContractRelationship | null>; saveClaim(value: RhChainProjectClaim): Promise<void>; claims(projectId: string): Promise<RhChainProjectClaim[]>; saveEvidence(value: RhChainProjectEvidence): Promise<void>; evidence(projectId: string): Promise<RhChainProjectEvidence[]>; getEvidence(id: string): Promise<RhChainProjectEvidence | null>; saveObservation(value: RhChainProjectObservation): Promise<void>; observations(projectId: string): Promise<RhChainProjectObservation[]>; saveVerdict(value: RhChainProjectVerdict): Promise<void>; getVerdict(id: string): Promise<RhChainProjectVerdict | null>; verdicts(projectId: string): Promise<RhChainProjectVerdict[]>; saveReceipt(value: RhChainIntelligenceReceipt): Promise<void>; getReceipt(id: string): Promise<RhChainIntelligenceReceipt | null>; receipts(projectId?: string): Promise<RhChainIntelligenceReceipt[]>; audit(value: RhChainProjectAudit): Promise<void>; auditFor(projectId: string): Promise<RhChainProjectAudit[]>; close?(): Promise<void> }

export class InMemoryRhChainProjectClaimsStore implements RhChainProjectClaimsStore {
  readonly adapter = 'memory' as const; readonly durable = false;
  private projects = new Map<string, RhChainProject>(); private relationshipMap = new Map<string, RhChainContractRelationship>(); private claimsByProject = new Map<string, RhChainProjectClaim[]>(); private evidenceByProject = new Map<string, RhChainProjectEvidence[]>(); private observationsByProject = new Map<string, RhChainProjectObservation[]>(); private verdictMap = new Map<string, RhChainProjectVerdict>(); private receiptMap = new Map<string, RhChainIntelligenceReceipt>(); private audits = new Map<string, RhChainProjectAudit[]>();
  async saveProject(value: RhChainProject) { this.projects.set(value.project_id, structuredClone(value)); }
  async getProject(value: string) { return clone(this.projects.get(value)); }
  async findProjectByContract(value: string) { return clone([...this.projects.values()].find((project) => project.primary_contract === normalize(value))); }
  async listProjects(cursor: string | undefined, limit: number) { const values = [...this.projects.values()].sort((left, right) => right.updated_at.localeCompare(left.updated_at) || left.project_id.localeCompare(right.project_id)); const start = cursor ? Math.max(0, values.findIndex((item) => item.project_id === cursor) + 1) : 0; return { items: values.slice(start, start + limit).map((item) => structuredClone(item)), next_cursor: values[start + limit]?.project_id ?? null }; }
  async saveRelationship(value: RhChainContractRelationship) { this.relationshipMap.set(value.relationship_id, structuredClone(value)); }
  async getRelationship(value: string) { return clone(this.relationshipMap.get(value)); }
  async relationships(projectId: string) { return [...this.relationshipMap.values()].filter((item) => item.project_id === projectId).map((item) => structuredClone(item)); }
  async findActiveRelationship(chain: 'robinhood', exactContract: string) { return clone([...this.relationshipMap.values()].find((item) => item.chain === chain && item.exact_contract === normalize(exactContract) && activeRelationship(item))); }
  async saveClaim(value: RhChainProjectClaim) { this.claimsByProject.set(value.project_id, replace(this.claimsByProject.get(value.project_id) ?? [], value, 'claim_id')); }
  async claims(projectId: string) { return (this.claimsByProject.get(projectId) ?? []).map((item) => structuredClone(item)); }
  async saveEvidence(value: RhChainProjectEvidence) { this.evidenceByProject.set(value.project_id, replace(this.evidenceByProject.get(value.project_id) ?? [], value, 'evidence_id')); }
  async evidence(projectId: string) { return (this.evidenceByProject.get(projectId) ?? []).map((item) => structuredClone(item)); }
  async getEvidence(value: string) { return clone([...this.evidenceByProject.values()].flat().find((item) => item.evidence_id === value)); }
  async saveObservation(value: RhChainProjectObservation) { this.observationsByProject.set(value.project_id, replace(this.observationsByProject.get(value.project_id) ?? [], value, 'observation_id')); }
  async observations(projectId: string) { return (this.observationsByProject.get(projectId) ?? []).map((item) => structuredClone(item)); }
  async saveVerdict(value: RhChainProjectVerdict) { this.verdictMap.set(value.verdict_id, structuredClone(value)); }
  async getVerdict(value: string) { return clone(this.verdictMap.get(value)); }
  async verdicts(projectId: string) { return [...this.verdictMap.values()].filter((item) => item.project_id === projectId).map((item) => structuredClone(item)); }
  async saveReceipt(value: RhChainIntelligenceReceipt) { this.receiptMap.set(value.receipt_id, structuredClone(value)); }
  async getReceipt(value: string) { return clone(this.receiptMap.get(value)); }
  async receipts(projectId?: string) { return [...this.receiptMap.values()].filter((item) => !projectId || item.project_id === projectId).sort((left, right) => right.created_at.localeCompare(left.created_at)).map((item) => structuredClone(item)); }
  async audit(value: RhChainProjectAudit) { this.audits.set(value.project_id, [...(this.audits.get(value.project_id) ?? []), structuredClone(value)]); }
  async auditFor(projectId: string) { return (this.audits.get(projectId) ?? []).map((item) => structuredClone(item)); }
}

/** Postgres stores purpose-specific payloads; database indexes protect active contract ownership. */
export class PostgresRhChainProjectClaimsStore implements RhChainProjectClaimsStore {
  readonly adapter = 'postgres' as const; readonly durable = true; private pool: pg.Pool; private ownsPool: boolean;
  constructor(source: PostgresPoolSource) { const resolved = resolvePostgresPool(source); this.pool = resolved.pool; this.ownsPool = resolved.ownsPool; }
  private async write(table: string, key: string, value: Record<string, unknown>, projectId?: string) { await this.pool.query(`insert into ${table} (${key}, project_id, payload) values ($1,$2,$3::jsonb) on conflict (${key}) do update set payload=excluded.payload, project_id=excluded.project_id`, [value[key], projectId ?? value.project_id, JSON.stringify(value)]); }
  async saveProject(value: RhChainProject) { await this.pool.query('insert into rh_chain_projects (project_id,chain,primary_contract,canonical_slug,identity_status,version,created_at,updated_at,payload) values ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) on conflict (project_id) do update set primary_contract=excluded.primary_contract,canonical_slug=excluded.canonical_slug,identity_status=excluded.identity_status,version=excluded.version,updated_at=excluded.updated_at,payload=excluded.payload', [value.project_id, value.chain, value.primary_contract, value.canonical_slug, value.identity_status, value.version, value.created_at, value.updated_at, JSON.stringify(value)]); }
  async getProject(value: string) { return this.one<RhChainProject>('select payload from rh_chain_projects where project_id=$1', [value]); }
  async findProjectByContract(value: string) { return this.one<RhChainProject>('select payload from rh_chain_projects where chain=$1 and primary_contract=$2', ['robinhood', normalize(value)]); }
  async listProjects(cursor: string | undefined, limit: number) { const result = await this.pool.query<{ payload: unknown }>('select payload from rh_chain_projects where ($1::text is null or project_id > $1) order by project_id asc limit $2', [cursor ?? null, limit + 1]); const values = result.rows.map((row) => parse<RhChainProject>(row.payload)); return { items: values.slice(0, limit), next_cursor: values[limit]?.project_id ?? null }; }
  async saveRelationship(value: RhChainContractRelationship) { await this.pool.query('insert into rh_chain_project_contract_relationships (relationship_id,project_id,chain,exact_contract,relationship_type,verification_state,version,created_at,updated_at,payload) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) on conflict (relationship_id) do update set exact_contract=excluded.exact_contract,relationship_type=excluded.relationship_type,verification_state=excluded.verification_state,version=excluded.version,updated_at=excluded.updated_at,payload=excluded.payload', [value.relationship_id, value.project_id, value.chain, value.exact_contract, value.relationship_type, value.verification_state, value.version, value.created_at, value.updated_at, JSON.stringify(value)]); }
  async getRelationship(value: string) { return this.one<RhChainContractRelationship>('select payload from rh_chain_project_contract_relationships where relationship_id=$1', [value]); }
  async relationships(projectId: string) { return this.many<RhChainContractRelationship>('rh_chain_project_contract_relationships', projectId); }
  async findActiveRelationship(chain: 'robinhood', exactContract: string) { const result = await this.pool.query<{ payload: unknown }>("select payload from rh_chain_project_contract_relationships where chain=$1 and exact_contract=$2 and verification_state in ('reviewed','verified') limit 1", [chain, normalize(exactContract)]); return result.rows[0] ? parse<RhChainContractRelationship>(result.rows[0].payload) : null; }
  async saveClaim(value: RhChainProjectClaim) { await this.write('rh_chain_project_claims', 'claim_id', value); }
  async claims(projectId: string) { return this.many<RhChainProjectClaim>('rh_chain_project_claims', projectId); }
  async saveEvidence(value: RhChainProjectEvidence) { await this.write('rh_chain_project_evidence', 'evidence_id', value); }
  async evidence(projectId: string) { return this.many<RhChainProjectEvidence>('rh_chain_project_evidence', projectId); }
  async getEvidence(value: string) { return this.one<RhChainProjectEvidence>('select payload from rh_chain_project_evidence where evidence_id=$1', [value]); }
  async saveObservation(value: RhChainProjectObservation) { await this.write('rh_chain_project_observations', 'observation_id', value); }
  async observations(projectId: string) { return this.many<RhChainProjectObservation>('rh_chain_project_observations', projectId); }
  async saveVerdict(value: RhChainProjectVerdict) { await this.write('rh_chain_project_verdicts', 'verdict_id', value); }
  async getVerdict(value: string) { return this.one<RhChainProjectVerdict>('select payload from rh_chain_project_verdicts where verdict_id=$1', [value]); }
  async verdicts(projectId: string) { return this.many<RhChainProjectVerdict>('rh_chain_project_verdicts', projectId); }
  async saveReceipt(value: RhChainIntelligenceReceipt) { await this.write('rh_chain_intelligence_receipts', 'receipt_id', value); }
  async getReceipt(value: string) { return this.one<RhChainIntelligenceReceipt>('select payload from rh_chain_intelligence_receipts where receipt_id=$1', [value]); }
  async receipts(projectId?: string) { const result = await this.pool.query<{ payload: unknown }>(`select payload from rh_chain_intelligence_receipts ${projectId ? 'where project_id=$1' : ''} order by created_at desc`, projectId ? [projectId] : []); return result.rows.map((row) => parse<RhChainIntelligenceReceipt>(row.payload)); }
  async audit(value: RhChainProjectAudit) { await this.pool.query('insert into rh_chain_project_audit (audit_id,project_id,action,reviewer_id,occurred_at,payload) values ($1,$2,$3,$4,$5,$6::jsonb)', [value.audit_id, value.project_id, value.action, value.reviewer_id, value.at, JSON.stringify(value)]); }
  async auditFor(projectId: string) { const result = await this.pool.query<{ payload: unknown }>('select payload from rh_chain_project_audit where project_id=$1 order by occurred_at asc', [projectId]); return result.rows.map((row) => parse<RhChainProjectAudit>(row.payload)); }
  private async one<T>(query: string, values: unknown[]) { const result = await this.pool.query<{ payload: unknown }>(query, values); return result.rows[0] ? parse<T>(result.rows[0].payload) : null; }
  private async many<T>(table: string, projectId: string) { const result = await this.pool.query<{ payload: unknown }>(`select payload from ${table} where project_id=$1`, [projectId]); return result.rows.map((row) => parse<T>(row.payload)); }
  async close() { if (this.ownsPool) await this.pool.end(); }
}

export class RhChainProjectClaimsError extends Error { constructor(readonly code: string) { super(code); } }

export class RhChainProjectClaimsService {
  constructor(readonly store: RhChainProjectClaimsStore, private now: () => Date = () => new Date(), private uuid: () => string = () => randomUUID()) {}

  async submit(raw: unknown) {
    const input = RhChainProjectSubmissionSchema.parse(raw); const now = this.at(); const activeRelationship = await this.store.findActiveRelationship('robinhood', input.exact_contract); let project = await this.store.findProjectByContract(input.exact_contract) ?? (activeRelationship ? await this.store.getProject(activeRelationship.project_id) : null);
    if (!project) { project = { project_id: `rhproj_${this.uuid()}`, chain: 'robinhood', primary_contract: input.exact_contract, additional_contracts: input.additional_contracts, canonical_display_name: input.project_name, canonical_slug: slug(input.project_name), ticker: null, project_type: null, reviewed_classification_reference: null, identity_status: 'submitted', official_website: input.website ?? null, official_documentation: input.documentation ?? null, official_social_accounts: input.socials, team_operator_disclosures: null, first_observed_at: now, last_reviewed_at: null, provenance: 'project_submitted', schema_version: 1, version: 1, created_at: now, updated_at: now, archived_at: null }; await this.store.saveProject(project); }
    const claimId = `rhclaim_${this.uuid()}`;
    const evidence = input.supporting_evidence.map((item) => this.projectSubmittedEvidence(project!.project_id, claimId, input.exact_contract, item, now));
    for (const item of evidence) await this.store.saveEvidence(item);
    const claim: RhChainProjectClaim = { claim_id: claimId, project_id: project.project_id, chain: 'robinhood', exact_contract_context: input.exact_contract, claim_category: input.claim_category, claim_text: input.claim_statement, structured_claim_payload: input.structured_claim_values, submitter_type: 'project', submitter_identifier: 'redacted_publicly', submitted_at: now, evidence_references: evidence.map((item) => item.evidence_id), claim_status: 'queued', reviewer_state: 'unreviewed', confidence: null, effective_period: { start: null, end: null }, review_after_at: null, correction_history: [], superseded_at: null, schema_version: 1, version: 1 };
    await this.store.saveClaim(claim); await this.log(project.project_id, 'project_claim_queued', null, 'Public submission queued; no endorsement, classification, reviewed truth, or publication.', { claim_id: claimId });
    return { status: 'queued_for_review', no_endorsement: true, no_automatic_publication: true, no_automatic_classification: true, submission_id: claimId, submitted_timestamp: now, next_review_state: 'queued' };
  }

  async project(projectId: string) { const project = await this.requireProject(projectId); return this.publicProject(project); }
  async list(raw: unknown) { const input = z.object({ cursor: z.string().max(128).optional(), limit: z.coerce.number().int().min(1).max(50).default(20) }).parse(raw); const page = await this.store.listProjects(input.cursor, input.limit); return { ...page, items: await Promise.all(page.items.map((item) => this.publicProject(item))) }; }
  async internalProject(projectId: string) { const project = await this.requireProject(projectId); const [relationships, claims, observations, evidence, verdicts, receipts] = await Promise.all([this.store.relationships(projectId), this.store.claims(projectId), this.store.observations(projectId), this.store.evidence(projectId), this.store.verdicts(projectId), this.store.receipts(projectId)]); return { project, relationships, claims, observations, evidence, verdicts, receipts, audit: await this.audit(projectId) }; }
  async publicProject(project: RhChainProject) {
    const [relationships, claims, observations, evidence, verdicts, receipts] = await Promise.all([this.store.relationships(project.project_id), this.store.claims(project.project_id), this.store.observations(project.project_id), this.store.evidence(project.project_id), this.store.verdicts(project.project_id), this.store.receipts(project.project_id)]);
    const visibleRelationships = relationships.filter((item) => item.verification_state === 'verified').map(publicRelationship);
    return { project: { ...project, canonical_contract_id: `robinhood:${project.primary_contract}` }, identity: { status: project.identity_status, exact_primary_contract: project.primary_contract, additional_reviewed_contracts: visibleRelationships.filter((item) => item.relationship_type !== 'primary'), verified_contract_relationships: visibleRelationships }, project_submitted_claims: claims.filter((item) => item.submitter_type === 'project'), infopunks_observations: observations, onchain_evidence: evidence.filter((item) => item.source_class === 'onchain_observation').map(publicEvidence), public_evidence: evidence.filter((item) => ['accessible', 'corroborated', 'contradicted', 'stale', 'disputed', 'inaccessible', 'source_required'].includes(item.evidence_status)).map(publicEvidence), reviewed_classification: project.reviewed_classification_reference, published_verdicts: verdicts.filter((item) => item.verdict_state === 'published'), unknowns: claims.filter((item) => ['queued', 'evidence_required', 'expired'].includes(item.claim_status)).map((item) => item.claim_id), disputes: claims.filter((item) => item.claim_status === 'disputed').map((item) => item.claim_id), receipts: receipts.filter((item) => ['published', 'superseded'].includes(item.reviewer_publication_state)).map(publicReceipt), provenance: { identity: project.provenance, evidence_classes: [...RH_CHAIN_PROJECT_EVIDENCE_SOURCES] }, freshness: { last_reviewed_at: project.last_reviewed_at }, not_financial_advice: true as const };
  }

  async linkContract(projectId: string, raw: unknown, reviewer: string) {
    const input = z.object({ expected_version: version, exact_contract: contract, relationship_type: z.enum(RH_CHAIN_CONTRACT_RELATIONSHIP_TYPES), evidence_references: z.array(id).max(100).default([]) }).strict().parse(raw); const project = await this.requireProject(projectId); this.assertVersion(project, input.expected_version); const collision = await this.store.findActiveRelationship('robinhood', input.exact_contract); if (collision && collision.project_id !== projectId) throw new RhChainProjectClaimsError('rh_chain_contract_project_collision'); if (collision && collision.project_id === projectId && collision.relationship_type === input.relationship_type) throw new RhChainProjectClaimsError('rh_chain_contract_duplicate_active_relationship'); if (input.relationship_type === 'primary' && (await this.store.relationships(projectId)).some((item) => item.relationship_type === 'primary' && activeRelationship(item))) throw new RhChainProjectClaimsError('rh_chain_multiple_active_primary_contracts');
    const now = this.at(); const relationship: RhChainContractRelationship = { relationship_id: `rhrel_${this.uuid()}`, project_id: projectId, chain: 'robinhood', exact_contract: input.exact_contract, relationship_type: input.relationship_type, verification_state: 'reviewed', evidence_references: input.evidence_references, reviewed_at: now, superseded_at: null, superseded_by_relationship_id: null, rejection_reason: null, version: 1, schema_version: 1, created_at: now, updated_at: now };
    await this.store.saveRelationship(relationship); await this.store.saveProject({ ...project, version: project.version + 1, updated_at: now, last_reviewed_at: now }); await this.log(projectId, 'contract_relationship_linked', reviewer, 'Contract relationship attached for independent review.', { relationship_id: relationship.relationship_id, exact_contract: relationship.exact_contract, relationship_type: relationship.relationship_type }); return relationship;
  }
  async verifyContract(projectId: string, relationshipId: string, raw: unknown, reviewer: string) {
    const input = z.object({ expected_version: version, evidence_references: z.array(id).max(100).default([]), reason: text }).strict().parse(raw); const relation = await this.requireRelationship(projectId, relationshipId); this.assertVersion(relation, input.expected_version); if (relation.verification_state !== 'reviewed') throw new RhChainProjectClaimsError('rh_chain_contract_invalid_transition'); const collision = await this.store.findActiveRelationship('robinhood', relation.exact_contract); if (collision && collision.relationship_id !== relation.relationship_id && collision.project_id !== projectId) throw new RhChainProjectClaimsError('rh_chain_contract_project_collision'); const relationships = await this.store.relationships(projectId); if (relation.relationship_type === 'primary' && relationships.some((item) => item.relationship_id !== relation.relationship_id && item.relationship_type === 'primary' && item.verification_state === 'verified')) throw new RhChainProjectClaimsError('rh_chain_multiple_active_primary_contracts');
    const now = this.at(); const next = { ...relation, verification_state: 'verified' as const, evidence_references: unique([...relation.evidence_references, ...input.evidence_references]), reviewed_at: now, version: relation.version + 1, updated_at: now }; await this.store.saveRelationship(next); const project = await this.requireProject(projectId); const patch = relation.relationship_type === 'primary' ? { primary_contract: relation.exact_contract, additional_contracts: project.additional_contracts.filter((item) => item !== relation.exact_contract), identity_status: 'identity_verified' as const } : { additional_contracts: unique([...project.additional_contracts, relation.exact_contract]), identity_status: project.identity_status === 'submitted' ? 'identity_partially_verified' as const : project.identity_status }; await this.store.saveProject({ ...project, ...patch, version: project.version + 1, last_reviewed_at: now, updated_at: now }); await this.log(projectId, 'contract_relationship_verified', reviewer, input.reason, { relationship_id: relationshipId, exact_contract: relation.exact_contract }); return next;
  }
  async disputeContract(projectId: string, relationshipId: string, raw: unknown, reviewer: string) { return this.transitionContract(projectId, relationshipId, raw, reviewer, 'disputed'); }
  async rejectContract(projectId: string, relationshipId: string, raw: unknown, reviewer: string) { return this.transitionContract(projectId, relationshipId, raw, reviewer, 'rejected'); }
  async supersedeContract(projectId: string, relationshipId: string, raw: unknown, reviewer: string) {
    const input = z.object({ expected_version: version, replacement_relationship_id: id, reason: text }).strict().parse(raw); const relation = await this.requireRelationship(projectId, relationshipId); this.assertVersion(relation, input.expected_version); if (!activeRelationship(relation)) throw new RhChainProjectClaimsError('rh_chain_contract_invalid_transition'); const replacement = await this.requireRelationship(projectId, input.replacement_relationship_id); if (replacement.verification_state !== 'verified' || replacement.relationship_type !== relation.relationship_type) throw new RhChainProjectClaimsError('rh_chain_contract_invalid_replacement'); const now = this.at(); const next = { ...relation, verification_state: 'superseded' as const, superseded_at: now, superseded_by_relationship_id: replacement.relationship_id, version: relation.version + 1, updated_at: now }; await this.store.saveRelationship(next); const project = await this.requireProject(projectId); const patch = relation.relationship_type === 'primary' ? { primary_contract: replacement.exact_contract } : { additional_contracts: project.additional_contracts.filter((item) => item !== relation.exact_contract) }; await this.store.saveProject({ ...project, ...patch, version: project.version + 1, last_reviewed_at: now, updated_at: now }); await this.log(projectId, 'contract_relationship_superseded', reviewer, input.reason, { relationship_id: relationshipId, replacement_relationship_id: replacement.relationship_id }); return next;
  }
  async relationshipAudit(projectId: string, relationshipId: string) { await this.requireRelationship(projectId, relationshipId); return (await this.audit(projectId)).filter((item) => item.payload.relationship_id === relationshipId); }

  async attachEvidence(projectId: string, raw: unknown, reviewer: string) {
    const input = evidenceAttachmentSchema.parse(raw); const target = await this.evidenceTarget(projectId, input.target_type, input.target_id); this.assertVersion(target, input.expected_version); if (input.source_class === 'project_submitted') throw new RhChainProjectClaimsError('rh_chain_reviewer_evidence_source_invalid'); if (input.target_type === 'receipt' && (target as RhChainIntelligenceReceipt).reviewer_publication_state === 'published') throw new RhChainProjectClaimsError('rh_chain_receipt_immutable'); const now = this.at(); const evidence: RhChainProjectEvidence = { evidence_id: `rhevidence_${this.uuid()}`, project_id: projectId, claim_id: input.target_type === 'claim' ? input.target_id : null, target_type: input.target_type, target_id: input.target_id, evidence_type: input.evidence_type, source_class: input.source_class, url: input.url ?? null, transaction_hash: input.transaction_hash ?? null, block_number: input.block_number ?? null, contract: input.contract ?? null, wallet: null, document_reference: input.document_reference ?? null, market_snapshot_id: input.market_snapshot_id ?? null, attention_quality_assessment_id: input.attention_quality_assessment_id ?? null, reviewed_classification_id: input.reviewed_classification_id ?? null, receipt_id: input.existing_receipt_id ?? null, submitted_at: now, observed_at: input.observed_at ?? null, fetched_at: input.fetched_at ?? null, freshness: input.freshness, confidence: input.confidence ?? null, content_hash: input.integrity_hash ?? null, evidence_status: input.evidence_status, public_summary: input.public_summary, reviewer_notes: input.private_reviewer_notes ?? null, provenance: 'reviewer_attached', schema_version: 1, version: 1, superseded_at: null, superseded_by_evidence_id: null };
    await this.store.saveEvidence(evidence); await this.bumpEvidenceTarget(projectId, input.target_type, target, evidence.evidence_id, now); await this.log(projectId, 'reviewer_evidence_attached', reviewer, input.evidence_statement, { evidence_id: evidence.evidence_id, target_type: input.target_type, target_id: input.target_id, source_class: input.source_class }); return internalEvidence(evidence);
  }
  async transitionEvidence(projectId: string, evidenceId: string, raw: unknown, reviewer: string) {
    const input = z.object({ expected_version: version, evidence_status: z.enum(RH_CHAIN_PROJECT_EVIDENCE_STATUSES), reason: text }).strict().parse(raw); const evidence = await this.store.getEvidence(evidenceId); if (!evidence || evidence.project_id !== projectId) throw new RhChainProjectClaimsError('rh_chain_evidence_not_found'); this.assertVersion(evidence, input.expected_version); if (evidence.evidence_status === 'disputed' && input.evidence_status === 'corroborated') throw new RhChainProjectClaimsError('rh_chain_evidence_invalid_transition'); if (['withdrawn', 'superseded'].includes(evidence.evidence_status)) throw new RhChainProjectClaimsError('rh_chain_evidence_invalid_transition'); const next = { ...evidence, evidence_status: input.evidence_status, version: (evidence.version ?? 1) + 1 }; await this.store.saveEvidence(next); await this.log(projectId, 'evidence_status_changed', reviewer, input.reason, { evidence_id: evidenceId, from: evidence.evidence_status, to: input.evidence_status }); return internalEvidence(next);
  }
  async supersedeEvidence(projectId: string, evidenceId: string, raw: unknown, reviewer: string) { const input = z.object({ expected_version: version, replacement_evidence_id: id, reason: text }).strict().parse(raw); const evidence = await this.store.getEvidence(evidenceId); const replacement = await this.store.getEvidence(input.replacement_evidence_id); if (!evidence || evidence.project_id !== projectId || !replacement || replacement.project_id !== projectId) throw new RhChainProjectClaimsError('rh_chain_evidence_not_found'); this.assertVersion(evidence, input.expected_version); if (evidence.evidence_status === 'superseded') throw new RhChainProjectClaimsError('rh_chain_evidence_invalid_transition'); const next = { ...evidence, evidence_status: 'superseded' as const, superseded_at: this.at(), superseded_by_evidence_id: replacement.evidence_id, version: (evidence.version ?? 1) + 1 }; await this.store.saveEvidence(next); await this.log(projectId, 'evidence_superseded', reviewer, input.reason, { evidence_id: evidenceId, replacement_evidence_id: replacement.evidence_id }); return internalEvidence(next); }

  async reviewClaim(projectId: string, claimId: string, raw: unknown, reviewer: string) { const input = z.object({ expected_version: version, claim_status: z.enum(RH_CHAIN_PROJECT_CLAIM_STATES), confidence: confidence.nullable().optional(), reason: text }).strict().parse(raw); const claim = (await this.store.claims(projectId)).find((item) => item.claim_id === claimId); if (!claim) throw new RhChainProjectClaimsError('rh_chain_claim_not_found'); this.assertVersion(claim, input.expected_version); if (claim.submitter_type === 'reviewer' && claim.submitter_identifier === reviewer) throw new RhChainProjectClaimsError('rh_chain_claim_self_approval_forbidden'); if (!claimTransitionAllowed(claim.claim_status, input.claim_status)) throw new RhChainProjectClaimsError('rh_chain_claim_invalid_transition'); const next = { ...claim, claim_status: input.claim_status, reviewer_state: 'reviewed' as const, confidence: input.confidence ?? claim.confidence, version: claim.version + 1 }; await this.store.saveClaim(next); await this.log(projectId, 'claim_reviewed', reviewer, input.reason, { claim_id: claimId, from: claim.claim_status, to: input.claim_status }); return next; }
  async addObservation(projectId: string, raw: unknown, reviewer: string) { const input = z.object({ expected_version: version.optional(), exact_contract: contract, observation_category: z.string().trim().min(1).max(120), observation_statement: text, structured_measured_values: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()])).default({}), source_inventory: z.array(id).max(50).default([]), evidence_references: z.array(id).max(50).default([]), confidence, methodology_version: z.string().trim().min(1).max(120), analyst_review_status: z.enum(RH_CHAIN_PROJECT_OBSERVATION_STATES).default('draft') }).strict().parse(raw); const project = await this.requireProject(projectId); if (input.expected_version) this.assertVersion(project, input.expected_version); const now = this.at(); const observation: RhChainProjectObservation = { observation_id: `rhobs_${this.uuid()}`, project_id: projectId, exact_contract: input.exact_contract, observation_category: input.observation_category, observation_statement: input.observation_statement, structured_measured_values: input.structured_measured_values, observation_window: { start: null, end: null }, source_inventory: input.source_inventory, evidence_references: input.evidence_references, confidence: input.confidence, freshness: 'unknown', methodology_version: input.methodology_version, analyst_review_status: input.analyst_review_status, created_at: now, superseded_at: null, version: 1 }; await this.store.saveObservation(observation); await this.store.saveProject({ ...project, version: project.version + 1, updated_at: now }); await this.log(projectId, 'observation_created', reviewer, 'Infopunks observation created separately from project claims.', { observation_id: observation.observation_id }); return observation; }
  async createVerdict(projectId: string, raw: unknown, reviewer: string) { const input = verdictSchema.parse(raw); const project = await this.requireProject(projectId); if (input.expected_version) this.assertVersion(project, input.expected_version); const now = this.at(); const verdict: RhChainProjectVerdict = { verdict_id: `rhverdict_${this.uuid()}`, project_id: projectId, verdict_type: input.verdict_type, verdict_statement: input.verdict_statement, verdict_state: 'draft', supported_claim_ids: input.supported_claim_ids, partially_supported_claim_ids: input.partially_supported_claim_ids, contradicted_claim_ids: input.contradicted_claim_ids, unknown_claim_ids: input.unknown_claim_ids, disputed_claim_ids: input.disputed_claim_ids, evidence_inventory: input.evidence_inventory, observation_inventory: input.observation_inventory, confidence: input.confidence, limitations: input.limitations, draft_at: now, published_at: null, rejection_reason: null, rejected_at: null, methodology_version: input.methodology_version, superseded_at: null, replacement_receipt_id: null, version: 1 }; await this.store.saveVerdict(verdict); await this.store.saveProject({ ...project, version: project.version + 1, updated_at: now }); await this.log(projectId, 'verdict_drafted', reviewer, 'Verdict draft created; it is not public.', { verdict_id: verdict.verdict_id }); return verdict; }
  async approveVerdict(projectId: string, verdictId: string, expectedVersion: number, reviewer: string) { const verdict = await this.requireVerdict(projectId, verdictId); this.assertVersion(verdict, expectedVersion); if (!['draft', 'under_review'].includes(verdict.verdict_state)) throw new RhChainProjectClaimsError('rh_chain_verdict_invalid_transition'); const next = { ...verdict, verdict_state: 'approved_for_publication' as const, version: verdict.version + 1 }; await this.store.saveVerdict(next); await this.log(projectId, 'verdict_approved', reviewer, 'Approved for immutable receipt publication.', { verdict_id: verdictId }); return next; }
  async rejectVerdict(projectId: string, verdictId: string, raw: unknown, reviewer: string) { const input = z.object({ expected_version: version, rejection_reason: text }).strict().parse(raw); const verdict = await this.requireVerdict(projectId, verdictId); this.assertVersion(verdict, input.expected_version); if (!['draft', 'under_review', 'approved_for_publication'].includes(verdict.verdict_state)) throw new RhChainProjectClaimsError('rh_chain_verdict_invalid_transition'); const now = this.at(); const next = { ...verdict, verdict_state: 'rejected' as const, rejection_reason: input.rejection_reason, rejected_at: now, version: verdict.version + 1 }; await this.store.saveVerdict(next); await this.log(projectId, 'verdict_rejected', reviewer, input.rejection_reason, { verdict_id: verdictId }); return next; }
  async publishReceipt(projectId: string, verdictId: string, raw: unknown, reviewer: string) { const input = receiptInputSchema.parse(raw); const verdict = await this.requireVerdict(projectId, verdictId); this.assertVersion(verdict, input.expected_version); if (verdict.verdict_state !== 'approved_for_publication') throw new RhChainProjectClaimsError('rh_chain_verdict_invalid_transition'); const receipt = await this.makeReceipt(projectId, verdict, input, 'published'); await this.store.saveReceipt(receipt); await this.store.saveVerdict({ ...verdict, verdict_state: 'published', published_at: receipt.publication_timestamp, version: verdict.version + 1 }); await this.log(projectId, 'receipt_published', reviewer, 'Immutable intelligence receipt published.', { receipt_id: receipt.receipt_id, integrity_hash: receipt.integrity_hash }); return receipt; }
  async createReceiptDraft(projectId: string, verdictId: string, raw: unknown, reviewer: string) { const input = receiptInputSchema.parse(raw); const verdict = await this.requireVerdict(projectId, verdictId); this.assertVersion(verdict, input.expected_version); if (verdict.verdict_state !== 'approved_for_publication') throw new RhChainProjectClaimsError('rh_chain_verdict_invalid_transition'); const receipt = await this.makeReceipt(projectId, verdict, input, 'draft'); await this.store.saveReceipt(receipt); await this.log(projectId, 'receipt_drafted', reviewer, 'Receipt draft stored privately.', { receipt_id: receipt.receipt_id, verdict_id: verdictId }); return receipt; }
  async approveReceiptDraft(projectId: string, receiptId: string, raw: unknown, reviewer: string) { const input = z.object({ expected_version: version }).strict().parse(raw); const receipt = await this.requireReceipt(projectId, receiptId); this.assertVersion(receipt, input.expected_version); if (receipt.reviewer_publication_state !== 'draft') throw new RhChainProjectClaimsError('rh_chain_receipt_invalid_transition'); const next = { ...receipt, reviewer_publication_state: 'approved_for_publication' as const, version: receipt.version + 1, updated_at: this.at() }; await this.store.saveReceipt(next); await this.log(projectId, 'receipt_draft_approved', reviewer, 'Receipt draft approved for publication.', { receipt_id: receiptId }); return next; }
  async rejectReceiptDraft(projectId: string, receiptId: string, raw: unknown, reviewer: string) { const input = z.object({ expected_version: version, rejection_reason: text }).strict().parse(raw); const receipt = await this.requireReceipt(projectId, receiptId); this.assertVersion(receipt, input.expected_version); if (!['draft', 'approved_for_publication'].includes(receipt.reviewer_publication_state)) throw new RhChainProjectClaimsError('rh_chain_receipt_invalid_transition'); const now = this.at(); const next = { ...receipt, reviewer_publication_state: 'rejected' as const, rejection_reason: input.rejection_reason, rejected_at: now, version: receipt.version + 1, updated_at: now }; await this.store.saveReceipt(next); await this.log(projectId, 'receipt_draft_rejected', reviewer, input.rejection_reason, { receipt_id: receiptId }); return next; }
  async publishReceiptDraft(projectId: string, receiptId: string, raw: unknown, reviewer: string) { const input = z.object({ expected_version: version }).strict().parse(raw); const receipt = await this.requireReceipt(projectId, receiptId); this.assertVersion(receipt, input.expected_version); if (receipt.reviewer_publication_state !== 'approved_for_publication') throw new RhChainProjectClaimsError('rh_chain_receipt_invalid_transition'); const now = this.at(); const base = { ...receipt, reviewer_publication_state: 'published' as const, publication_timestamp: now, updated_at: now, version: receipt.version + 1, integrity_hash: null }; const next = { ...base, integrity_hash: hash(base) }; await this.store.saveReceipt(next); await this.log(projectId, 'receipt_published', reviewer, 'Immutable intelligence receipt published from approved draft.', { receipt_id: receiptId, integrity_hash: next.integrity_hash }); return next; }
  async supersedeReceipt(receiptId: string, raw: unknown, reviewer: string) { const input = z.object({ expected_version: version, reason: text, replacement_receipt_id: id }).strict().parse(raw); const receipt = await this.store.getReceipt(receiptId); const replacement = await this.store.getReceipt(input.replacement_receipt_id); if (!receipt || !replacement) throw new RhChainProjectClaimsError('rh_chain_receipt_not_found'); this.assertVersion(receipt, input.expected_version); if (receipt.reviewer_publication_state !== 'published' || replacement.reviewer_publication_state !== 'published' || receipt.project_id !== replacement.project_id) throw new RhChainProjectClaimsError('rh_chain_receipt_invalid_transition'); const now = this.at(); await this.store.saveReceipt({ ...receipt, reviewer_publication_state: 'superseded', replacement_receipt_id: replacement.receipt_id, correction_history: [...receipt.correction_history, { at: now, reason: input.reason, replacement_receipt_id: replacement.receipt_id }], updated_at: now, version: receipt.version + 1 }); await this.store.saveReceipt({ ...replacement, superseded_receipt_id: receipt.receipt_id, updated_at: now, version: replacement.version + 1 }); await this.log(receipt.project_id, 'receipt_superseded', reviewer, input.reason, { receipt_id: receiptId, replacement_receipt_id: replacement.receipt_id }); return { original: await this.store.getReceipt(receiptId), replacement: await this.store.getReceipt(replacement.receipt_id) }; }
  async audit(projectId: string) { return this.store.auditFor(projectId); }

  private async transitionContract(projectId: string, relationshipId: string, raw: unknown, reviewer: string, state: 'disputed' | 'rejected') { const input = z.object({ expected_version: version, reason: text }).strict().parse(raw); const relationship = await this.requireRelationship(projectId, relationshipId); this.assertVersion(relationship, input.expected_version); if (!['reviewed', 'verified'].includes(relationship.verification_state)) throw new RhChainProjectClaimsError('rh_chain_contract_invalid_transition'); const now = this.at(); const next = { ...relationship, verification_state: state, rejection_reason: state === 'rejected' ? input.reason : null, version: relationship.version + 1, updated_at: now }; await this.store.saveRelationship(next); const project = await this.requireProject(projectId); await this.store.saveProject({ ...project, identity_status: state === 'disputed' ? 'disputed' : project.identity_status, version: project.version + 1, last_reviewed_at: now, updated_at: now }); await this.log(projectId, `contract_relationship_${state}`, reviewer, input.reason, { relationship_id: relationshipId }); return next; }
  private async makeReceipt(projectId: string, verdict: RhChainProjectVerdict, input: z.infer<typeof receiptInputSchema>, state: 'draft' | 'published') { const [project, claims, evidence, observations] = await Promise.all([this.requireProject(projectId), this.store.claims(projectId), this.store.evidence(projectId), this.store.observations(projectId)]); const now = this.at(); const base: RhChainIntelligenceReceipt = { receipt_id: `rhir_${this.uuid()}`, receipt_type: input.receipt_type, project_id: projectId, chain: 'robinhood', exact_contract_identity: project.primary_contract, canonical_project_name: project.canonical_display_name, publication_timestamp: state === 'published' ? now : null, observation_window: input.observation_window, verdict: verdict.verdict_statement, verdict_confidence: verdict.confidence, claim_inventory: claims.map((item) => item.claim_id), claim_states: Object.fromEntries(claims.map((item) => [item.claim_id, item.claim_status])), observation_inventory: observations.map((item) => item.observation_id), evidence_inventory: evidence.map((item) => item.evidence_id), reviewed_classification_reference: project.reviewed_classification_reference, market_snapshot_references: evidence.flatMap((item) => item.market_snapshot_id ? [item.market_snapshot_id] : []), attention_quality_reference: evidence.find((item) => item.attention_quality_assessment_id)?.attention_quality_assessment_id ?? null, inclusion_totals: verdict.supported_claim_ids.length + verdict.partially_supported_claim_ids.length, exclusion_totals: verdict.contradicted_claim_ids.length, unknowns: verdict.unknown_claim_ids, disputes: verdict.disputed_claim_ids, stale_sources: evidence.filter((item) => item.freshness === 'stale').map((item) => item.evidence_id), methodology_version: verdict.methodology_version, reviewer_publication_state: state, rejection_reason: null, rejected_at: null, correction_history: [], superseded_receipt_id: null, replacement_receipt_id: null, integrity_hash: null, not_financial_advice: true, schema_version: 1, version: 1, created_at: now, updated_at: now }; return state === 'published' ? { ...base, integrity_hash: hash(base) } : base; }
  private async evidenceTarget(projectId: string, type: z.infer<typeof evidenceAttachmentSchema>['target_type'], targetId: string) { if (type === 'project_identity') return this.requireProject(projectId); if (type === 'contract_relationship') return this.requireRelationship(projectId, targetId); if (type === 'claim') { const claim = (await this.store.claims(projectId)).find((item) => item.claim_id === targetId); if (!claim) throw new RhChainProjectClaimsError('rh_chain_claim_not_found'); return claim; } if (type === 'observation') { const observation = (await this.store.observations(projectId)).find((item) => item.observation_id === targetId); if (!observation) throw new RhChainProjectClaimsError('rh_chain_observation_not_found'); return observation; } if (type === 'verdict') return this.requireVerdict(projectId, targetId); return this.requireReceipt(projectId, targetId); }
  private async bumpEvidenceTarget(projectId: string, type: z.infer<typeof evidenceAttachmentSchema>['target_type'], target: { version: number }, evidenceId: string, now: string) { if (type === 'project_identity') { const project = target as RhChainProject; await this.store.saveProject({ ...project, version: project.version + 1, updated_at: now }); return; } if (type === 'contract_relationship') { const relation = target as RhChainContractRelationship; await this.store.saveRelationship({ ...relation, evidence_references: unique([...relation.evidence_references, evidenceId]), version: relation.version + 1, updated_at: now }); return; } if (type === 'claim') { const claim = target as RhChainProjectClaim; await this.store.saveClaim({ ...claim, evidence_references: unique([...claim.evidence_references, evidenceId]), version: claim.version + 1 }); return; } if (type === 'observation') { const observation = target as RhChainProjectObservation; await this.store.saveObservation({ ...observation, evidence_references: unique([...observation.evidence_references, evidenceId]), version: observation.version + 1 }); return; } if (type === 'verdict') { const verdict = target as RhChainProjectVerdict; await this.store.saveVerdict({ ...verdict, evidence_inventory: unique([...verdict.evidence_inventory, evidenceId]), version: verdict.version + 1 }); return; } const receipt = target as RhChainIntelligenceReceipt; await this.store.saveReceipt({ ...receipt, evidence_inventory: unique([...receipt.evidence_inventory, evidenceId]), version: receipt.version + 1, updated_at: now }); }
  private projectSubmittedEvidence(projectId: string, claimId: string, exactContract: string, value: string, now: string): RhChainProjectEvidence { return { evidence_id: `rhevidence_${this.uuid()}`, project_id: projectId, claim_id: claimId, target_type: 'claim', target_id: claimId, evidence_type: 'source_document', source_class: 'project_submitted', url: value, transaction_hash: null, block_number: null, contract: exactContract, wallet: null, document_reference: null, market_snapshot_id: null, attention_quality_assessment_id: null, reviewed_classification_id: null, receipt_id: null, submitted_at: now, observed_at: null, fetched_at: null, freshness: 'unknown', confidence: null, content_hash: null, evidence_status: 'submitted', public_summary: null, reviewer_notes: null, provenance: 'project_submitted', schema_version: 1, version: 1, superseded_at: null, superseded_by_evidence_id: null }; }
  private async requireProject(projectId: string) { const project = await this.store.getProject(projectId); if (!project) throw new RhChainProjectClaimsError('rh_chain_project_not_found'); return project; }
  private async requireRelationship(projectId: string, relationshipId: string) { const relationship = await this.store.getRelationship(relationshipId); if (!relationship || relationship.project_id !== projectId) throw new RhChainProjectClaimsError('rh_chain_contract_relationship_not_found'); return relationship; }
  private async requireVerdict(projectId: string, verdictId: string) { const verdict = await this.store.getVerdict(verdictId); if (!verdict || verdict.project_id !== projectId) throw new RhChainProjectClaimsError('rh_chain_verdict_not_found'); return verdict; }
  private async requireReceipt(projectId: string, receiptId: string) { const receipt = await this.store.getReceipt(receiptId); if (!receipt || receipt.project_id !== projectId) throw new RhChainProjectClaimsError('rh_chain_receipt_not_found'); return receipt; }
  private assertVersion(value: { version: number }, expected: number) { if (value.version !== expected) throw new RhChainProjectClaimsError('rh_chain_project_conflict'); }
  private at() { return this.now().toISOString(); }
  private async log(projectId: string, action: string, reviewerId: string | null, reason: string, payload: Record<string, unknown>) { await this.store.audit({ audit_id: this.uuid(), project_id: projectId, action, reviewer_id: reviewerId, at: this.at(), reason, payload }); }
}

const evidenceAttachmentSchema = z.object({ expected_version: version, target_type: z.enum(['project_identity', 'contract_relationship', 'claim', 'observation', 'verdict', 'receipt']), target_id: id, source_class: source, evidence_type: z.string().trim().min(1).max(120), url: url.optional(), transaction_hash: z.string().trim().min(1).max(256).optional(), block_number: z.string().trim().min(1).max(80).optional(), contract: contract.optional(), document_reference: z.string().trim().min(1).max(400).optional(), market_snapshot_id: id.optional(), reviewed_classification_id: id.optional(), attention_quality_assessment_id: id.optional(), existing_receipt_id: id.optional(), evidence_statement: text, observed_at: timestamp.optional(), fetched_at: timestamp.optional(), freshness: z.enum(['fresh', 'stale', 'unknown']).default('unknown'), confidence: confidence.nullable().optional(), public_summary: z.string().trim().min(1).max(1200), private_reviewer_notes: z.string().trim().max(4000).optional(), integrity_hash: z.string().trim().max(200).optional(), evidence_status: z.enum(RH_CHAIN_PROJECT_EVIDENCE_STATUSES).default('submitted') }).strict().superRefine((value, context) => { if (!value.url && !value.transaction_hash) context.addIssue({ code: 'custom', message: 'public_url_or_exact_chain_reference_required' }); });
const verdictSchema = z.object({ expected_version: version.optional(), verdict_type: z.string().trim().min(1).max(120), verdict_statement: text, supported_claim_ids: z.array(id).max(50).default([]), partially_supported_claim_ids: z.array(id).max(50).default([]), contradicted_claim_ids: z.array(id).max(50).default([]), unknown_claim_ids: z.array(id).max(50).default([]), disputed_claim_ids: z.array(id).max(50).default([]), evidence_inventory: z.array(id).max(100).default([]), observation_inventory: z.array(id).max(100).default([]), confidence, limitations: z.array(text).max(30).default([]), methodology_version: z.string().trim().min(1).max(120) }).strict();
const receiptInputSchema = z.object({ expected_version: version, receipt_type: z.enum(RH_CHAIN_PROJECT_RECEIPT_TYPES), observation_window: z.object({ start: timestamp.nullable(), end: timestamp.nullable() }).default({ start: null, end: null }) }).strict();
function activeRelationship(value: RhChainContractRelationship) { return value.verification_state === 'reviewed' || value.verification_state === 'verified'; }
function claimTransitionAllowed(from: RhChainProjectClaim['claim_status'], to: RhChainProjectClaim['claim_status']) { const allowed: Partial<Record<RhChainProjectClaim['claim_status'], RhChainProjectClaim['claim_status'][]>> = { submitted: ['queued'], queued: ['under_review', 'evidence_required', 'partially_supported', 'supported', 'contradicted', 'rejected', 'disputed'], under_review: ['evidence_required', 'partially_supported', 'supported', 'contradicted', 'disputed', 'rejected'], evidence_required: ['under_review', 'expired', 'rejected', 'disputed'], partially_supported: ['under_review', 'superseded', 'disputed'], supported: ['under_review', 'superseded', 'disputed'], contradicted: ['under_review', 'superseded', 'disputed'], disputed: ['under_review', 'superseded'], rejected: ['superseded'], expired: ['under_review', 'superseded'] }; return allowed[from]?.includes(to) ?? false; }
function normalize(value: string) { return contract.parse(value); }
function clone<T>(value: T | undefined): T | null { return value === undefined ? null : structuredClone(value); }
function replace<T extends Record<string, unknown>, K extends keyof T>(values: T[], value: T, key: K) { return [...values.filter((item) => item[key] !== value[key]), structuredClone(value)]; }
function parse<T>(value: unknown): T { if (!value || typeof value !== 'object') throw new RhChainProjectClaimsError('rh_chain_project_stored_payload_invalid'); return value as T; }
function unique(values: string[]) { return [...new Set(values)]; }
function slug(value: string) { return value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 80) || 'project'; }
function hash(value: Record<string, unknown>) { const canonical = JSON.stringify({ ...value, integrity_hash: undefined, updated_at: undefined }); return `sha256:${createHash('sha256').update(canonical).digest('hex')}`; }
export function publicEvidence(value: RhChainProjectEvidence) { const { reviewer_notes, ...safe } = value; return safe; }
export function internalEvidence(value: RhChainProjectEvidence) { return value; }
export function publicRelationship(value: RhChainContractRelationship) { const { rejection_reason, ...safe } = value; return safe; }
export function publicReceipt(value: RhChainIntelligenceReceipt) { const { rejection_reason, rejected_at, ...safe } = value; return { ...safe, canonical_url: `/rh-chain-signal-desk/intelligence-receipts/${encodeURIComponent(value.receipt_id)}` }; }
