import pg from 'pg';
import { getRhChain4663Index, getRhChainReviewQueue, type RhChainCloneRadarPayload, type RhChainReviewItem } from '../data/rhChain';
import { resolvePostgresPool, RetryablePostgresSchema, type PostgresPoolSource } from '../persistence/retryablePostgresSchema';
import { assembleRhChainCloneRadar } from './rhChainCloneRadarService';
import { asRhChainPersistedReviewItem, type RhChainSubmissionStore } from './rhChainSignalVault';
import { isRhChainIdentityContract } from './rhChainTruthGuards';

export type RhChainRiskCorrelationSnapshotItem = { correlation_id: string; correlation_type: string; suspected_correlation: string; related_records: Array<{ review_id: string; ticker: string; token_contract: string; review_state: string }>; evidence_summary: string; confidence_level: 'low' | 'medium' | 'high'; review_status: 'requires_review'; recommended_next_review_step: string; observed_at: string };
export type RhChainRiskCorrelationSnapshot = { snapshot_id: string; observed_at: string; freshness_state: 'fresh' | 'aging' | 'stale'; suspected_correlations: RhChainRiskCorrelationSnapshotItem[]; sources: string[]; radar: RhChainCloneRadarPayload };
export interface RhChainRiskCorrelationSnapshotStore { readonly adapter: 'memory' | 'postgres'; readonly durable: boolean; save(snapshot: RhChainRiskCorrelationSnapshot): Promise<void>; latest(): Promise<RhChainRiskCorrelationSnapshot | null>; close?(): Promise<void>; }
export class InMemoryRhChainRiskCorrelationSnapshotStore implements RhChainRiskCorrelationSnapshotStore { readonly adapter = 'memory' as const; readonly durable = false; private current: RhChainRiskCorrelationSnapshot | null = null; async save(snapshot: RhChainRiskCorrelationSnapshot) { this.current = structuredClone(snapshot); } async latest() { return this.current ? structuredClone(this.current) : null; } }
export class PostgresRhChainRiskCorrelationSnapshotStore implements RhChainRiskCorrelationSnapshotStore { readonly adapter = 'postgres' as const; readonly durable = true; private readonly pool: pg.Pool; private readonly ownsPool: boolean; private readonly schema = new RetryablePostgresSchema('rh_chain_risk_correlation_store'); constructor(source: PostgresPoolSource) { const resolved = resolvePostgresPool(source); this.pool = resolved.pool; this.ownsPool = resolved.ownsPool; } async save(snapshot: RhChainRiskCorrelationSnapshot) { await this.ready(); await this.pool.query('insert into rh_chain_risk_correlation_snapshots (snapshot_id, observed_at, payload) values ($1,$2,$3::jsonb)', [snapshot.snapshot_id, snapshot.observed_at, JSON.stringify(snapshot)]); await this.pool.query("delete from rh_chain_risk_correlation_snapshots where snapshot_id in (select snapshot_id from (select snapshot_id, row_number() over (order by observed_at desc) as row_number, observed_at from rh_chain_risk_correlation_snapshots) retained where retained.observed_at < now() - interval '7 days' or retained.row_number > 300)"); } async latest() { await this.ready(); const result = await this.pool.query<{ payload: RhChainRiskCorrelationSnapshot }>('select payload from rh_chain_risk_correlation_snapshots order by observed_at desc limit 1'); return result.rows[0]?.payload ?? null; } async close() { if (this.ownsPool) await this.pool.end(); } private ready() { return this.schema.ensure(this.pool, 'create table if not exists rh_chain_risk_correlation_snapshots (snapshot_id text primary key, observed_at timestamptz not null, payload jsonb not null); create index if not exists rh_chain_risk_correlation_snapshots_observed_at_idx on rh_chain_risk_correlation_snapshots (observed_at desc);'); } }

/** Read-only correlation sweep. It creates review prompts, never decisions. */
export class RhChainRiskCorrelationSweepService {
  private readonly now: () => Date;
  constructor(private readonly store: RhChainRiskCorrelationSnapshotStore, private readonly submissions: Pick<RhChainSubmissionStore, 'list'>, now?: () => Date) { this.now = now ?? (() => new Date()); }
  async getLatest() { const snapshot = await this.store.latest(); if (!snapshot) return null; const age = Math.max(0, this.now().getTime() - Date.parse(snapshot.observed_at)); const freshness_state = age <= 36 * 60 * 60 * 1000 ? 'fresh' : age <= 72 * 60 * 60 * 1000 ? 'aging' : 'stale'; return { ...snapshot, freshness_state }; }
  async sweep() {
    const observed_at = this.now().toISOString(); const submissions = await this.submissions.list(); const reviews = [...getRhChainReviewQueue().items, ...submissions.map(asRhChainPersistedReviewItem)]; const radar = assembleRhChainCloneRadar(reviews);
    const base = (radar.correlations ?? []).map((correlation) => ({ ...correlation, observed_at }));
    const pattern = radar.vampire_copycat_watch.map((item) => ({ correlation_id: `sweep:${item.risk_pattern_id}`, correlation_type: item.risk_category, suspected_correlation: `Suspected ${item.risk_category.replaceAll('_', ' ')}. Requires review.`, related_records: reviews.filter((review) => review.review_id === item.risk_pattern_id.split(':').at(-1)).map(publicRecord), evidence_summary: item.evidence_summary, confidence_level: item.confidence_level, review_status: 'requires_review' as const, recommended_next_review_step: item.next_review_step, observed_at }));
    const placeholders = reviews.filter((review) => !isRhChainIdentityContract(review.token_contract)).map((review) => ({ correlation_id: `sweep:placeholder:${review.review_id}`, correlation_type: 'placeholder_source_required_contract', suspected_correlation: 'Source-required or placeholder contract blocks identity correlation. Requires review.', related_records: [publicRecord(review)], evidence_summary: 'No identity inference is made from a ticker or placeholder contract.', confidence_level: 'low' as const, review_status: 'requires_review' as const, recommended_next_review_step: 'Obtain an exact non-placeholder contract and source-linked receipt.', observed_at }));
    const highAttentionMissingVerification = getRhChain4663Index().assets.filter((asset) => !isRhChainIdentityContract(asset.token_contract)).map((asset) => ({ correlation_id: `sweep:missing-verification:${asset.ticker}`, correlation_type: 'missing_verification_high_attention', suspected_correlation: 'High-attention asset lacks an exact identity contract. Requires review.', related_records: [], evidence_summary: `${asset.ticker} remains source-required; attention does not establish identity or safety.`, confidence_level: 'low' as const, review_status: 'requires_review' as const, recommended_next_review_step: 'Attach an exact contract and reviewed source receipts before any identity linkage.', observed_at }));
    const suspected_correlations = [...base, ...pattern, ...placeholders, ...highAttentionMissingVerification].map((item) => ({ ...item, related_records: item.related_records.map((record) => ({ review_id: record.review_id, ticker: record.ticker, token_contract: record.token_contract, review_state: record.review_state })) }));
    const snapshot: RhChainRiskCorrelationSnapshot = { snapshot_id: `rh-risk-sweep-${observed_at.replace(/[^0-9]/g, '')}-${Math.random().toString(36).slice(2, 8)}`, observed_at, freshness_state: 'fresh', suspected_correlations, sources: ['Vault submissions', 'Review Queue', 'Token Dossiers', 'Launchpad Observatory', 'Clone Radar', 'Provider snapshots'], radar };
    await this.store.save(snapshot); return snapshot;
  }
}
function publicRecord(item: RhChainReviewItem) { return { review_id: item.review_id, ticker: item.ticker, token_contract: item.token_contract, review_state: item.review_state }; }
