import { createHash, randomUUID } from 'node:crypto';
import pg from 'pg';
import type { RhChainLayerClassification } from './rhChainMarketStructureService';
import type { RhChainMarketSnapshot } from './rhChainMarketSnapshotService';
import type { RhChainReviewedClassification } from './rhChainReviewedClassificationService';
import { resolvePostgresPool, type PostgresPoolSource } from '../persistence/retryablePostgresSchema';

/**
 * Deterministic, snapshot-only Attention Quality methodology.  This service is
 * deliberately unable to call a provider: capture is the only place provider
 * context enters the system.
 */
export const RH_CHAIN_ATTENTION_QUALITY_METHODOLOGY = 'rh_chain_attention_quality_v2';
export type RhChainAttentionAssessmentState = 'insufficient_data' | 'baseline_forming' | 'promotion_detected' | 'post_promotion_observing' | 'measurable' | 'stale' | 'unavailable' | 'disputed';
export type RhChainAttentionWindow = '24h' | '7d' | '30d';
export type RhChainAttentionComponent = {
  key: string; raw_value: number | null; normalized_value: number | null; weight: number; evidence_window: string; confidence: 'low' | 'medium' | 'high'; source: string[]; caveat: string | null; missing_data_state: 'available' | 'unknown' | 'insufficient_history' | 'not_applicable';
};
export type RhChainAttentionAssessment = {
  assessment_id: string; chain: 'robinhood'; contract: string; canonical_pair: string | null; reviewed_project_identity: string | null; primary_layer: string | null; secondary_layers: string[]; classification_provenance: 'curated_reviewed_memory' | 'durable_approved_reviewed_classification' | 'unknown'; classification_version: number | null; assessment_state: RhChainAttentionAssessmentState; attention_quality_score: number | null; verdict: string; evidence_confidence: 'low' | 'medium' | 'high'; data_completeness: number; methodology_version: typeof RH_CHAIN_ATTENTION_QUALITY_METHODOLOGY; observation_window: WindowCoverage; baseline_window: WindowCoverage; promotion_window: WindowCoverage; post_promotion_window: WindowCoverage; captured_at: string | null; freshness: 'fresh' | 'stale' | 'unavailable'; warnings: string[]; source_inventory: string[]; components: RhChainAttentionComponent[]; paid_attention: PaidAttention; receipt_id: string | null; provider_requests_in_path: 0;
};
export type WindowCoverage = { label: string; start_at: string | null; end_at: string | null; observations: number; coverage: number; sufficient: boolean };
export type PaidAttention = { detected: boolean; active_boost_observations: number; paid_order_observations: number; first_promotion_at: string | null; last_promotion_at: string | null; promotion_duration_ms: number | null; promotion_intensity: number | null; signals: string[] };
export type RhChainAttentionReceipt = { receipt_id: string; status: 'draft' | 'published' | 'rejected'; assessment: RhChainAttentionAssessment; schema_version: 1; created_at: string; published_at: string | null; rejected_at: string | null; reviewer_id: string | null; supersedes_receipt_id: string | null; superseded_at: string | null; correction_history: Array<{ at: string; action: 'superseded' | 'published' | 'rejected'; by: string }> };

export interface RhChainAttentionReceiptStore {
  readonly adapter: 'memory' | 'postgres'; readonly durable: boolean;
  create(receipt: RhChainAttentionReceipt): Promise<RhChainAttentionReceipt>;
  get(id: string): Promise<RhChainAttentionReceipt | null>;
  list(contract?: string): Promise<RhChainAttentionReceipt[]>;
  transition(id: string, action: 'publish' | 'reject' | 'supersede', reviewer: string, supersededAt?: string): Promise<RhChainAttentionReceipt | null>;
}
export class InMemoryRhChainAttentionReceiptStore implements RhChainAttentionReceiptStore {
  readonly adapter = 'memory' as const; readonly durable = false; private readonly records = new Map<string, RhChainAttentionReceipt>();
  async create(receipt: RhChainAttentionReceipt) { const current = this.records.get(receipt.receipt_id); if (current) return structuredClone(current); this.records.set(receipt.receipt_id, structuredClone(receipt)); return structuredClone(receipt); }
  async get(id: string) { const item = this.records.get(id); return item ? structuredClone(item) : null; }
  async list(contract?: string): Promise<RhChainAttentionReceipt[]> { return [...this.records.values()].filter((item) => !contract || item.assessment.contract === normalize(contract)).sort((a, b) => b.created_at.localeCompare(a.created_at)).map((item) => structuredClone(item)); }
  async transition(id: string, action: 'publish' | 'reject' | 'supersede', reviewer: string, supersededAt?: string) { const current = this.records.get(id); if (!current) return null; if (current.status !== 'draft' && action !== 'supersede') return structuredClone(current); const at = supersededAt ?? new Date().toISOString(); const next: RhChainAttentionReceipt = { ...current, status: action === 'publish' ? 'published' : action === 'reject' ? 'rejected' : current.status, published_at: action === 'publish' ? at : current.published_at, rejected_at: action === 'reject' ? at : current.rejected_at, reviewer_id: action === 'supersede' ? current.reviewer_id : reviewer, superseded_at: action === 'supersede' ? at : current.superseded_at, correction_history: [...current.correction_history, { at, action: action === 'publish' ? 'published' : action === 'reject' ? 'rejected' : 'superseded', by: reviewer }] }; this.records.set(id, next); return structuredClone(next); }
}
export class PostgresRhChainAttentionReceiptStore implements RhChainAttentionReceiptStore {
  readonly adapter = 'postgres' as const; readonly durable = true; private readonly pool: pg.Pool; private readonly ownsPool: boolean;
  constructor(source: PostgresPoolSource) { const resolved = resolvePostgresPool(source); this.pool = resolved.pool; this.ownsPool = resolved.ownsPool; }
  async create(receipt: RhChainAttentionReceipt) { const result = await this.pool.query<{ payload: RhChainAttentionReceipt }>('insert into rh_chain_attention_receipts (receipt_id, contract, methodology_version, status, created_at, payload) values ($1,$2,$3,$4,$5,$6::jsonb) on conflict (receipt_id) do nothing returning payload', [receipt.receipt_id, receipt.assessment.contract, receipt.assessment.methodology_version, receipt.status, receipt.created_at, JSON.stringify(receipt)]); if (result.rows[0]) return result.rows[0].payload; return (await this.get(receipt.receipt_id))!; }
  async get(id: string) { const result = await this.pool.query<{ payload: RhChainAttentionReceipt }>('select payload from rh_chain_attention_receipts where receipt_id=$1', [id]); return result.rows[0]?.payload ?? null; }
  async list(contract?: string) { const result = await this.pool.query<{ payload: RhChainAttentionReceipt }>(contract ? 'select payload from rh_chain_attention_receipts where contract=$1 order by created_at desc limit 100' : 'select payload from rh_chain_attention_receipts order by created_at desc limit 100', contract ? [normalize(contract)] : []); return result.rows.map((row) => row.payload); }
  async transition(id: string, action: 'publish' | 'reject' | 'supersede', reviewer: string, supersededAt?: string) { const current = await this.get(id); if (!current || (current.status !== 'draft' && action !== 'supersede')) return current; const at = supersededAt ?? new Date().toISOString(); const next: RhChainAttentionReceipt = { ...current, status: action === 'publish' ? 'published' : action === 'reject' ? 'rejected' : current.status, published_at: action === 'publish' ? at : current.published_at, rejected_at: action === 'reject' ? at : current.rejected_at, reviewer_id: action === 'supersede' ? current.reviewer_id : reviewer, superseded_at: action === 'supersede' ? at : current.superseded_at, correction_history: [...current.correction_history, { at, action: action === 'publish' ? 'published' : action === 'reject' ? 'rejected' : 'superseded', by: reviewer }] }; await this.pool.query('update rh_chain_attention_receipts set status=$2, superseded_at=$3, payload=$4::jsonb where receipt_id=$1', [id, next.status, next.superseded_at, JSON.stringify(next)]); return next; }
  async close() { if (this.ownsPool) await this.pool.end(); }
}

export type RhChainAttentionQualityOptions = { snapshots: (contract: string) => Promise<RhChainMarketSnapshot[]>; curated: (contract: string) => RhChainLayerClassification | null; durable: (contract: string) => Promise<RhChainReviewedClassification | null>; receipts: RhChainAttentionReceiptStore; now?: () => Date; maxStaleMs?: number };
export class RhChainAttentionQualityService {
  private readonly now: () => Date; private readonly maxStaleMs: number;
  constructor(private readonly options: RhChainAttentionQualityOptions) { this.now = options.now ?? (() => new Date()); this.maxStaleMs = options.maxStaleMs ?? 6 * 60 * 60 * 1_000; }
  async assess(contractInput: string, requested: RhChainAttentionWindow = '7d'): Promise<RhChainAttentionAssessment> {
    const contract = normalize(contractInput); const all = (await this.options.snapshots(contract)).sort((a, b) => a.captured_at.localeCompare(b.captured_at)).slice(-300); const now = this.now();
    const cutoff = now.getTime() - windowMs(requested); const snapshots = all.filter((item) => Date.parse(item.captured_at) >= cutoff); const curated = this.options.curated(contract); const durable = await this.options.durable(contract);
    const conflict = Boolean(curated && durable && (curated.primary_layer !== durable.primary_layer || !sameSet(curated.secondary_layers, durable.secondary_layers)));
    const classification = curated ? { identity: curated.display_name ?? curated.ticker ?? 'Reviewed exact contract', primary: curated.primary_layer, secondary: curated.secondary_layers, provenance: 'curated_reviewed_memory' as const, version: null } : durable && durable.review_status === 'approved' && durable.effective_at && !durable.superseded_at ? { identity: 'Reviewed exact contract', primary: durable.primary_layer, secondary: durable.secondary_layers, provenance: 'durable_approved_reviewed_classification' as const, version: durable.classification_version } : null;
    const latest = snapshots.at(-1) ?? all.at(-1) ?? null; const freshness = !latest ? 'unavailable' as const : now.getTime() - Date.parse(latest.captured_at) > this.maxStaleMs ? 'stale' as const : 'fresh' as const;
    const paid = paidAttention(snapshots); const windows = splitWindows(snapshots, paid, requested); const completeness = dataCompleteness(snapshots); const components = makeComponents(windows, paid, completeness, requested);
    let state: RhChainAttentionAssessmentState = 'measurable'; const warnings: string[] = [];
    if (!snapshots.length) state = 'unavailable';
    else if (freshness === 'stale') state = 'stale';
    else if (conflict) { state = 'disputed'; warnings.push('Curated and durable reviewed classifications disagree. Curated memory remains authoritative; scoring is withheld.'); }
    else if (!classification) { state = 'insufficient_data'; warnings.push('An exact contract has market observations, but no curated or approved active reviewed classification establishes public identity.'); }
    else if (!windows.baseline.sufficient) { state = 'baseline_forming'; warnings.push('Minimum pre-promotion baseline history is still forming.'); }
    else if (!paid.detected) { state = 'baseline_forming'; warnings.push('No persisted paid-attention event is available; paid-versus-organic retention cannot be assessed.'); }
    else if (windows.promotion.observations < 1) { state = 'promotion_detected'; warnings.push('Paid attention is observed but its promotion window is not yet bounded.'); }
    else if (!windows.post.sufficient) { state = paid.last_promotion_at === latest?.captured_at ? 'promotion_detected' : 'post_promotion_observing'; warnings.push('Post-promotion observations are not yet sufficient for a durable retention conclusion.'); }
    else if (completeness < 80) { state = 'insufficient_data'; warnings.push('Required market-field coverage is below the published 80% threshold.'); }
    if (freshness === 'stale') warnings.push('Latest persisted market observation is beyond the maximum Attention Quality freshness age.');
    const score = state === 'measurable' ? Math.round(components.reduce((sum, item) => sum + (item.normalized_value ?? 0) * item.weight / 100, 0)) : null;
    const confidence = confidenceFor(state, completeness, windows); const verdict = verdictFor(state, score, paid);
    const assessment: RhChainAttentionAssessment = { assessment_id: identity(contract, requested, snapshots, classification?.version ?? null), chain: 'robinhood', contract, canonical_pair: latest?.pair_address ?? null, reviewed_project_identity: classification?.identity ?? null, primary_layer: classification?.primary ?? null, secondary_layers: classification?.secondary ?? [], classification_provenance: classification?.provenance ?? 'unknown', classification_version: classification?.version ?? null, assessment_state: state, attention_quality_score: score, verdict, evidence_confidence: confidence, data_completeness: completeness, methodology_version: RH_CHAIN_ATTENTION_QUALITY_METHODOLOGY, observation_window: coverage(`Last ${requested}`, snapshots, requested), baseline_window: windows.baseline, promotion_window: windows.promotion, post_promotion_window: windows.post, captured_at: latest?.captured_at ?? null, freshness, warnings, source_inventory: ['infopunks:reviewed-memory', 'infopunks:market-snapshot-memory', 'dexscreener:captured-context'], components, paid_attention: paid, receipt_id: null, provider_requests_in_path: 0 };
    const published = (await this.options.receipts.list(contract)).find((item) => item.status === 'published' && item.assessment.assessment_id === assessment.assessment_id);
    return { ...assessment, receipt_id: published?.receipt_id ?? null };
  }
  async listAssessments() { const receipts = await this.options.receipts.list(); const contracts = [...new Set(receipts.map((item) => item.assessment.contract))].slice(0, 100); return Promise.all(contracts.map((contract) => this.assess(contract))); }
  async createReceipt(contract: string, window: RhChainAttentionWindow, reviewer: string) { const assessment = await this.assess(contract, window); const existing = (await this.options.receipts.list(assessment.contract)).find((item) => item.assessment.assessment_id === assessment.assessment_id); if (existing) return existing; const prior = (await this.options.receipts.list(assessment.contract)).find((item) => item.status === 'published' && !item.superseded_at); const now = this.now().toISOString(); if (prior) await this.options.receipts.transition(prior.receipt_id, 'supersede', reviewer, now); const receipt: RhChainAttentionReceipt = { receipt_id: `rhaq_${createHash('sha256').update(`${assessment.assessment_id}|${now}`).digest('hex').slice(0, 24)}`, status: 'draft', assessment, schema_version: 1, created_at: now, published_at: null, rejected_at: null, reviewer_id: null, supersedes_receipt_id: prior?.receipt_id ?? null, superseded_at: null, correction_history: [] }; return this.options.receipts.create(receipt); }
  async publishReceipt(id: string, reviewer: string) { return this.options.receipts.transition(id, 'publish', reviewer); }
  async rejectReceipt(id: string, reviewer: string) { return this.options.receipts.transition(id, 'reject', reviewer); }
  async publicReceipt(id: string) { const receipt = await this.options.receipts.get(id); return receipt?.status === 'published' ? receipt : null; }
}

function normalize(value: string) { return value.trim().toLowerCase(); }
function windowMs(value: RhChainAttentionWindow) { return value === '24h' ? 86_400_000 : value === '7d' ? 604_800_000 : 2_592_000_000; }
function sameSet(a: readonly string[], b: readonly string[]) { return a.length === b.length && a.every((item) => b.includes(item)); }
function coverage(label: string, snapshots: RhChainMarketSnapshot[], requested: RhChainAttentionWindow): WindowCoverage { const first = snapshots[0]?.captured_at ?? null; const last = snapshots.at(-1)?.captured_at ?? null; const span = first && last ? Date.parse(last) - Date.parse(first) : 0; return { label, start_at: first, end_at: last, observations: snapshots.length, coverage: Math.min(1, span / windowMs(requested)), sufficient: snapshots.length >= 3 && span >= Math.min(windowMs(requested) / 2, 12 * 60 * 60 * 1_000) }; }
function paidSnapshot(item: RhChainMarketSnapshot) { return item.active_boosts > 0 || item.paid_order_types.length > 0; }
function paidAttention(snapshots: RhChainMarketSnapshot[]): PaidAttention { const matches = snapshots.filter(paidSnapshot); const signals = [...new Set(matches.flatMap((item) => [item.active_boosts > 0 ? 'active_dexscreener_boost' : null, ...item.paid_order_types.map((type) => `paid_order:${type}`)]).filter((item): item is string => Boolean(item)))]; return { detected: matches.length > 0, active_boost_observations: matches.filter((item) => item.active_boosts > 0).length, paid_order_observations: matches.filter((item) => item.paid_order_types.length > 0).length, first_promotion_at: matches[0]?.captured_at ?? null, last_promotion_at: matches.at(-1)?.captured_at ?? null, promotion_duration_ms: matches.length > 1 ? Date.parse(matches.at(-1)!.captured_at) - Date.parse(matches[0].captured_at) : null, promotion_intensity: matches.length ? round(matches.reduce((sum, item) => sum + item.active_boosts + item.paid_order_types.length, 0) / matches.length) : null, signals }; }
function splitWindows(snapshots: RhChainMarketSnapshot[], paid: PaidAttention, requested: RhChainAttentionWindow) { const first = paid.first_promotion_at ? Date.parse(paid.first_promotion_at) : Infinity; const last = paid.last_promotion_at ? Date.parse(paid.last_promotion_at) : -Infinity; const baselineItems = snapshots.filter((item) => Date.parse(item.captured_at) < first); const promotionItems = snapshots.filter((item) => Date.parse(item.captured_at) >= first && Date.parse(item.captured_at) <= last); const postItems = snapshots.filter((item) => Date.parse(item.captured_at) > last); return { baseline: coverage('Pre-promotion baseline', baselineItems, requested), promotion: coverage('Active promotion', promotionItems, requested), post: coverage('Post-promotion', postItems, requested), baselineItems, promotionItems, postItems }; }
function dataCompleteness(items: RhChainMarketSnapshot[]) { if (!items.length) return 0; const values = items.flatMap((item) => [item.volume_h24, item.liquidity_usd, item.txns_h24_buys, item.txns_h24_sells]); return round(values.filter((item) => item !== null).length / values.length * 100); }
function ratio(after: number | null, before: number | null) { return after === null || before === null || before <= 0 ? null : after / before; }
function avg(items: RhChainMarketSnapshot[], getter: (item: RhChainMarketSnapshot) => number | null) { const values = items.map(getter).filter((item): item is number => item !== null); return values.length ? values.reduce((a, b) => a + b, 0) / values.length : null; }
function makeComponents(windows: ReturnType<typeof splitWindows>, paid: PaidAttention, completeness: number, requested: RhChainAttentionWindow): RhChainAttentionComponent[] {
  const base = windows.baselineItems; const post = windows.postItems; const pro = windows.promotionItems; const source = ['rh_chain_market_snapshots']; const metric = (key: string, raw: number | null, weight: number, caveat: string | null = null): RhChainAttentionComponent => ({ key, raw_value: raw === null ? null : round(raw), normalized_value: raw === null ? null : round(Math.max(0, Math.min(1, raw)) * 100), weight, evidence_window: requested, confidence: raw === null ? 'low' : base.length >= 3 && post.length >= 3 ? 'high' : 'medium', source, caveat, missing_data_state: raw === null ? 'insufficient_history' : 'available' });
  const tx = (items: RhChainMarketSnapshot[]) => avg(items, (item) => item.txns_h24_buys === null && item.txns_h24_sells === null ? null : (item.txns_h24_buys ?? 0) + (item.txns_h24_sells ?? 0));
  const boostRaw = paid.detected ? 1 - (post.filter(paidSnapshot).length / Math.max(1, post.length)) : null; const orderRaw = paid.paid_order_observations ? 1 - (post.filter((item) => item.paid_order_types.length > 0).length / Math.max(1, post.length)) : null;
  const pairs = new Set([...base, ...post].map((item) => item.pair_address).filter(Boolean)); const pairRaw = pairs.size ? 1 / pairs.size : null;
  return [metric('organic_volume_retention', ratio(avg(post, (item) => item.volume_h24), avg(base, (item) => item.volume_h24)), 20), metric('liquidity_persistence', ratio(avg(post, (item) => item.liquidity_usd), avg(base, (item) => item.liquidity_usd)), 20), metric('transaction_persistence', ratio(tx(post), tx(base)), 15, 'Transaction counts are not wallet or holder retention.'), metric('post_promotion_continuity', post.length / Math.max(1, pro.length), 15), metric('boost_dependence', boostRaw, 10), metric('paid_order_dependence', orderRaw, 5), metric('pair_stability', pairRaw, 5), { key: 'market_data_completeness', raw_value: completeness, normalized_value: completeness, weight: 10, evidence_window: requested, confidence: completeness >= 80 ? 'high' : 'low', source, caveat: null, missing_data_state: completeness ? 'available' : 'unknown' }, { key: 'narrative_persistence', raw_value: null, normalized_value: null, weight: 0, evidence_window: requested, confidence: 'low', source: ['reviewed-memory'], caveat: 'No reviewed narrative-persistence evidence is currently attached to this methodology.', missing_data_state: 'not_applicable' }];
}
function confidenceFor(state: RhChainAttentionAssessmentState, completeness: number, windows: ReturnType<typeof splitWindows>) { if (state !== 'measurable') return 'low' as const; return completeness >= 90 && windows.post.observations >= 5 ? 'high' as const : 'medium' as const; }
function verdictFor(state: RhChainAttentionAssessmentState, score: number | null, paid: PaidAttention) { if (state === 'measurable') return score! >= 75 ? 'Durable attention persistence' : score! >= 55 ? 'Organic retention measurable' : score! >= 35 ? 'Early organic retention forming' : 'Paid attention dominant'; if (state === 'promotion_detected') return 'Promotion detected; post-promotion evidence pending'; if (state === 'post_promotion_observing') return 'Post-promotion observation in progress'; if (state === 'baseline_forming') return paid.detected ? 'Insufficient pre-promotion history' : 'Baseline forming'; if (state === 'disputed') return 'Classification dispute prevents a confident conclusion'; if (state === 'stale') return 'Persisted evidence is stale'; return 'Insufficient evidence to judge attention retention'; }
function identity(contract: string, window: string, snapshots: RhChainMarketSnapshot[], classificationVersion: number | null) { return `rhaqa_${createHash('sha256').update([contract, window, RH_CHAIN_ATTENTION_QUALITY_METHODOLOGY, classificationVersion ?? 'curated', ...snapshots.map((item) => item.snapshot_id)].join('|')).digest('hex').slice(0, 28)}`; }
function round(value: number) { return Number(value.toFixed(2)); }
