import { createRhChainDailyReceiptXPost, getRhChainDailyReceipts, getRhChainLaunchSurfaces, getRhChainPayload, rhChainDailyReceiptRoute, type RhChainDistributionPackPayload, type RhChainDistributionPacket } from '../data/rhChain';

const DOCTRINE = 'External data gives context. Infopunks gives judgment. Receipts create memory.' as const;
const DISCLAIMER = 'Public intelligence distribution only. Do not spam, coordinate raids, harass people, imply affiliation, or treat any packet as trading advice.';
const BASE = '/rh-chain-signal-desk';

/** Writes source-linked sharing packets; copy carries the caveat instead of separating it from the claim. */
export function assembleRhChainDistributionPack(): RhChainDistributionPackPayload {
  const receipt = getRhChainDailyReceipts().latest_receipt;
  const desk = getRhChainPayload();
  const packets: RhChainDistributionPacket[] = [
    { id: 'daily-receipt', title: 'Daily Receipt post', intended_surface: 'x', copy_text: createRhChainDailyReceiptXPost(receipt), link: `${BASE}${rhChainDailyReceiptRoute(receipt.receipt_id)}`, risk_disclaimer: 'Receipt memory is not a token recommendation or safety claim.', last_updated: receipt.generated_at, source_artifact: 'Daily Receipts' },
    { id: 'meme-pulse', title: 'Meme Pulse post', intended_surface: 'telegram', copy_text: `Most see noise.\nInfopunks reads the pulse.\n\nWhat’s moving. What’s risky. What the market is trying to say.\n\nExternal data gives context. Infopunks gives judgment.`, link: `${BASE}/meme-pulse`, risk_disclaimer: 'Attention is context, not an instruction to trade or promote a token.', last_updated: desk.last_updated, source_artifact: 'RH Meme Pulse' },
    { id: 'clone-radar', title: 'Clone Radar warning post', intended_surface: 'x', copy_text: `Copies move faster than memory.\n\nClone & Impersonator Radar tracks suspected, unverified risk patterns across RH Chain.\n\nVerify the exact contract. Read the receipts.\nNo pile-ons. No certainty without evidence.`, link: `${BASE}/clone-radar`, risk_disclaimer: 'Entries are suspected patterns requiring review, not definitive misconduct findings.', last_updated: desk.last_updated, source_artifact: 'Clone & Impersonator Radar' },
    { id: 'token-dossier', title: 'Token Dossier share post', intended_surface: 'discord', copy_text: `A ticker is not an identity.\n\nOpen the Infopunks token dossier for the exact contract: desk memory, receipts, launch context, and external context—kept separate.\n\nInclusion is not endorsement.`, link: `${BASE}/tokens/:contract`, risk_disclaimer: 'Use the exact contract route. A dossier does not call a token safe or add it to the index.', last_updated: desk.last_updated, source_artifact: 'Token Dossiers' },
    { id: 'submit-signal', title: 'Submit Signal call-to-action', intended_surface: 'generic', copy_text: `Got a contract, pair, launch source, deployer trail, or risk receipt?\n\nSubmit it to the RH Chain Signal Vault.\n\nManual review. No auto-approval. No receipt, no signal.`, link: `${BASE}/submit`, risk_disclaimer: 'Submission is not endorsement, listing, partnership, or financial advice.', last_updated: desk.generated_at, source_artifact: 'Signal Vault' },
    { id: 'scout-agent', title: 'Scout Agent demo post', intended_surface: 'telegram', copy_text: `The market forgets in public.\nScout remembers the desk.\n\nAsk about risk memory, launch context, narrative mutation, or a token contract.\n\nRead-only intelligence. Never trades.`, link: `${BASE}/scout`, risk_disclaimer: 'Scout summarizes existing memory; it does not verify identity or make recommendations.', last_updated: desk.last_updated, source_artifact: 'Scout Agent' },
    { id: 'launch-surface', title: 'Launch Surface Watch post', intended_surface: 'discord', copy_text: `Infopunks does not launch the token.\nInfopunks remembers the launch.\n\nLaunch source, pair, LP claim, deployer, and timestamp—context before narrative.`, link: `${BASE}/launch-surfaces`, risk_disclaimer: `${getRhChainLaunchSurfaces().disclaimer} A launch label is never an approval.`, last_updated: getRhChainLaunchSurfaces().generated_at, source_artifact: 'Launch Surface Watch' }
  ];
  return { title: 'RH Chain Distribution Pack', subtitle: 'Copy the receipt. Keep the caveat.', generated_at: receipt.generated_at, doctrine: DOCTRINE, disclaimer: DISCLAIMER, packets };
}
