import { createHash } from 'node:crypto';
import pg from 'pg';
import { resolvePostgresPool, RetryablePostgresSchema, type PostgresPoolSource } from '../persistence/retryablePostgresSchema';
import { REFLEXIVE_CHAIN_ID, type CanonicalStockAsset, type Evidence, type ReflexiveSnapshot } from './rhChainReflexiveRadarService';

/** Breadth is deliberately separate from the AI/NVDA depth observation stream. */
export const RMM_CENSUS_METHOD_VERSION = 'RMM_CATEGORY_CENSUS_V0_1';
export const ACTIVE_CANONICAL_STOCK_TOKEN_METHOD_VERSION = 'ACTIVE_CANONICAL_STOCK_TOKEN_V1';
export const RMM_ACTIVITY_METHOD_VERSION = 'RMM_ACTIVITY_V1';
export type CensusVerificationState = 'CLAIMED' | 'VERIFIED_DIRECT_STOCK_QUOTE' | 'VERIFIED_POOL_QUOTE_UNRESOLVED' | 'DISCOVERED_UNVERIFIED' | 'MISSION_TOKEN_UNRESOLVED' | 'NONCANONICAL_STOCK_ASSET' | 'INACTIVE' | 'NOT_REPRODUCIBLE' | 'DUPLICATE_CLAIM' | 'INSUFFICIENT_DATA';
export type RmmActivityState = 'ACTIVE' | 'LOW_ACTIVITY' | 'INACTIVE' | 'UNKNOWN';
export type RmmVenue = 'LONG' | 'DOPPLER' | 'PAIR' | 'PONS' | 'BANKR' | 'UNISWAP_DIRECT' | 'OTHER' | 'UNKNOWN';
export type RmmCategory = 'SEMICONDUCTORS' | 'AI_SOFTWARE' | 'HEALTHCARE' | 'SPACE' | 'CRYPTO_FINANCIAL' | 'CONSUMER_TECH' | 'INDEX_ETF' | 'COMMODITY_GOLD_EXPOSURE' | 'OTHER';
export type ClaimedRmmPair = { claimed_stock_symbol: string; claimed_mission_symbol: string; source_reference: string };
export type RmmCensusPairRecord = {
  object_type: 'RMM_CENSUS_PAIR_RECORD'; record_id: string; claimed_stock_symbol: string; claimed_mission_symbol: string;
  canonical_stock_asset_id: string | null; canonical_stock_contract: string | null; mission_contract: string | null; pool_id: string | null; pool_address: string | null;
  venue: RmmVenue; quote_direction: 'MISSION_QUOTED_IN_CANONICAL_STOCK' | 'UNRESOLVED'; verification_state: CensusVerificationState; current_activity_state: RmmActivityState;
  inventory_accounting_capability: 'AVAILABLE' | 'UNAVAILABLE'; first_seen: string | null; last_observed: string | null; category: RmmCategory | null; evidence: Evidence[]; gaps: string[]; immutable: true;
};
export type RmmCategoryCensus = {
  object_type: 'RMM_CATEGORY_CENSUS'; census_id: string; observed_at: string; methodology_version: typeof RMM_CENSUS_METHOD_VERSION; immutable: true;
  canonical_stock_token_universe: { qualification: 'ACTIVE_CANONICAL_STOCK_TOKEN'; methodology_version: typeof ACTIVE_CANONICAL_STOCK_TOKEN_METHOD_VERSION; asset_count: number; registry_observed_at: string | null; registry_fetched_at: string | null; assets: Array<Pick<CanonicalStockAsset, 'asset_id' | 'ticker' | 'canonical_contract' | 'current_multiplier' | 'status'>> };
  source_claims: { watch_case_id: 'RH_STOCK_MEME_MAP_20260903'; claimed_canonical_stock_tokens: 216; claimed_pair_count: 27; claimed_distinct_stock_tickers: 22; parsed_pair_count: number; parsed_distinct_stock_tickers: number; count_reconciliation_state: 'MATCH' | 'SOURCE_COUNT_MISMATCH' | 'INCOMPLETE_SOURCE' | 'DUPLICATE_FOUND'; source_note: string };
  pairs: RmmCensusPairRecord[];
  claimed_pair_count: number; verified_pair_count: number; distinct_claimed_stock_tickers: number; distinct_verified_stock_tickers: number; unverified_pair_count: number; inactive_pair_count: number; not_reproducible_count: number; noncanonical_pair_count: number; quote_direction_unresolved_count: number;
  rmm_penetration: { numerator: number; denominator: number; percentage: number | null; qualifying_stock_asset_ids: string[]; methodology_version: string; observed_at: string };
  rmm_pair_density: { verified_rmm_pair_count: number; activated_stock_token_tickers: number; value: number | null };
  persistent_rmm_penetration: { status: 'UNAVAILABLE' | 'PARTIAL' | 'AVAILABLE'; numerator: number | null; denominator: number; percentage: number | null; persistence_coverage: { eligible_for_d7: number; evaluated: number }; note: string };
  verification_coverage: { claim_coverage: string; identity_coverage: string; pool_coverage: string; quote_direction_coverage: string; persistence_coverage: string; inventory_coverage: string; percentage: number };
  category_breadth: { categories: RmmCategory[]; count: number }; concentration: { top_stock_token: string | null; top_3_stock_tokens: string[]; top_3_pair_share_pct: number | null };
  category_evidence: { breadth_state: 'ANECDOTAL' | 'EARLY_MULTI_ASSET' | 'CROSS_CATEGORY' | 'INSUFFICIENT_DATA'; persistence_state: 'PERSISTENCE_UNPROVEN' | 'PERSISTENT_MULTI_ASSET' | 'UNAVAILABLE'; ra1_impact: 'BREADTH_SUPPORT_ONLY_NOT_CONFIRMED' };
  data_gaps: string[]; next_deep_audit_candidates: Array<{ stock_symbol: string; mission_symbol: string; reason: string }>; research_tree: { root: 'RWA ACTIVATION'; depth: string[]; breadth: string[]; feeds: 'CATEGORY EVIDENCE'; then: 'RA1' };
};

export interface RmmCategoryCensusStore { readonly adapter: 'memory' | 'postgres'; readonly durable: boolean; latest(): Promise<RmmCategoryCensus | null>; append(census: RmmCategoryCensus): Promise<void>; }
export class InMemoryRmmCategoryCensusStore implements RmmCategoryCensusStore { readonly adapter = 'memory' as const; readonly durable = false; private records: RmmCategoryCensus[] = []; async latest() { return structuredClone(this.records.at(-1) ?? null); } async append(census: RmmCategoryCensus) { if (!this.records.some((item) => item.census_id === census.census_id)) this.records.push(structuredClone(census)); } }
export class PostgresRmmCategoryCensusStore implements RmmCategoryCensusStore {
  readonly adapter = 'postgres' as const; readonly durable = true; private readonly pool: pg.Pool; private readonly ownsPool: boolean; private readonly schema = new RetryablePostgresSchema('rmm_category_census_store');
  constructor(source: PostgresPoolSource) { const resolved = resolvePostgresPool(source); this.pool = resolved.pool; this.ownsPool = resolved.ownsPool; }
  async latest() { await this.ensure(); const result = await this.pool.query<{ payload: RmmCategoryCensus }>('select payload from rmm_category_censuses order by observed_at desc limit 1'); return result.rows[0] ? structuredClone(result.rows[0].payload) : null; }
  async append(census: RmmCategoryCensus) { await this.ensure(); await this.pool.query('insert into rmm_category_censuses (census_id, observed_at, payload) values ($1,$2,$3::jsonb) on conflict (census_id) do nothing', [census.census_id, census.observed_at, JSON.stringify(census)]); }
  async close() { if (this.ownsPool) await this.pool.end(); }
  private ensure() { return this.schema.ensure(this.pool, 'create table if not exists rmm_category_censuses (census_id text primary key, observed_at timestamptz not null, payload jsonb not null); create index if not exists rmm_category_censuses_observed_at_idx on rmm_category_censuses (observed_at desc);'); }
}

// The supplied list has 25 visible records over 21 tickers. The missing two pairs and one ticker are intentionally not invented.
export const WATCH_RMM_CLAIMS: readonly ClaimedRmmPair[] = [
  ['NVDA','AI'], ['MU','MOO'], ['HIMS','BONER'], ['SPCX','SPACEHOOD'], ['SPCX','SPACETIME'], ['QUBT','QC'], ['QUBT','QCAT'], ['WYFI','RABBIT'], ['ASML','ORG'], ['PLTR','HI'], ['MSTR','SAYLORMOON'], ['COIN','PANDA'], ['AAPL','BELIEVE'], ['GLD','ROCK'], ['AMZN','CRIME'], ['SNDK','CACHE'], ['GMEB','MEMESTOCK'], ['LLY','RETA'], ['TSM','AU'], ['TSM','TAIWAN'], ['SPY','PAIR'], ['SPY','STARTUP'], ['RBLX','ROBUX'], ['FIGMA','LIGMA'], ['MRNA','PHARMA']
].map(([claimed_stock_symbol, claimed_mission_symbol]) => ({ claimed_stock_symbol, claimed_mission_symbol, source_reference: 'RH_STOCK_MEME_MAP_20260903' }));

export class RmmCategoryCensusService {
  constructor(private readonly snapshot: () => Promise<ReflexiveSnapshot>, private readonly store: RmmCategoryCensusStore, private readonly now = () => new Date()) {}
  async refresh() { const prior = await this.store.latest(); const requested = this.now(); const at = prior && Date.parse(prior.observed_at) >= requested.getTime() ? new Date(Date.parse(prior.observed_at) + 1) : requested; const census = buildRmmCategoryCensus(await this.snapshot(), at); await this.store.append(census); return census; }
  async latest() { return this.store.latest(); }
  async pairs() { return (await this.latest())?.pairs ?? []; }
  async stock(symbol: string) { const latest = await this.latest(); if (!latest) return null; return { stock: latest.canonical_stock_token_universe.assets.find((asset) => asset.ticker.toUpperCase() === symbol.toUpperCase()) ?? null, pairs: latest.pairs.filter((pair) => pair.claimed_stock_symbol.toUpperCase() === symbol.toUpperCase()), census_id: latest.census_id }; }
}

export function activeCanonicalStockTokens(assets: readonly CanonicalStockAsset[]) { const seen = new Set<string>(); return assets.filter((asset) => asset.chain_id === REFLEXIVE_CHAIN_ID && asset.status === 'ASSET_STATUS_ACTIVE' && /^0x[a-f0-9]{40}$/i.test(asset.canonical_contract) && !isExcludedAsset(asset) && !seen.has(asset.canonical_contract.toLowerCase()) && (seen.add(asset.canonical_contract.toLowerCase()) || true)); }
export function buildRmmCategoryCensus(snapshot: ReflexiveSnapshot, at = new Date()): RmmCategoryCensus {
  const observed_at = at.toISOString(); const assets = activeCanonicalStockTokens(snapshot.assets); const byTicker = new Map(assets.map((asset) => [asset.ticker.toUpperCase(), asset]));
  const seenClaims = new Set<string>(); const records: RmmCensusPairRecord[] = WATCH_RMM_CLAIMS.map((claim) => {
    const key = `${claim.claimed_stock_symbol}|${claim.claimed_mission_symbol}`; const duplicate = seenClaims.has(key); seenClaims.add(key); const asset = byTicker.get(claim.claimed_stock_symbol);
    const pair = asset ? snapshot.pairs.find((item) => item.stock_asset_id === asset.asset_id && item.mission_symbol.toUpperCase() === claim.claimed_mission_symbol.toUpperCase() && item.canonicality === 'verified' && item.verification.verification_status === 'VERIFIED') : undefined;
    const latest = pair ? snapshot.observations.filter((item) => item.pair_id === pair.pair_id).sort((a,b) => b.observed_at.localeCompare(a.observed_at))[0] : undefined;
    const inventory = pair ? snapshot.inventory_observations.some((item) => item.mission_pair_id === pair.pair_id && item.status === 'AVAILABLE') : false;
    const verification_state: CensusVerificationState = duplicate ? 'DUPLICATE_CLAIM' : !asset ? 'NONCANONICAL_STOCK_ASSET' : pair ? 'VERIFIED_DIRECT_STOCK_QUOTE' : 'MISSION_TOKEN_UNRESOLVED';
    const activity = pair ? classifyActivity(latest) : 'UNKNOWN';
    return frozen<RmmCensusPairRecord>({ object_type: 'RMM_CENSUS_PAIR_RECORD', record_id: id('rmm-census-pair', key), claimed_stock_symbol: claim.claimed_stock_symbol, claimed_mission_symbol: claim.claimed_mission_symbol, canonical_stock_asset_id: asset?.asset_id ?? null, canonical_stock_contract: asset?.canonical_contract ?? null, mission_contract: pair?.mission_contract ?? null, pool_id: pair?.pool_id ?? null, pool_address: pair?.pool_address ?? null, venue: venue(pair?.venue), quote_direction: pair ? 'MISSION_QUOTED_IN_CANONICAL_STOCK' : 'UNRESOLVED', verification_state, current_activity_state: activity, inventory_accounting_capability: inventory ? 'AVAILABLE' : 'UNAVAILABLE', first_seen: pair?.launched_at ?? null, last_observed: latest?.observed_at ?? null, category: asset ? category(asset.ticker) : null, evidence: pair?.evidence ?? [], gaps: gaps(asset, pair, latest), immutable: true });
  });
  const verified = records.filter((record) => record.verification_state === 'VERIFIED_DIRECT_STOCK_QUOTE'); const activated = [...new Set(verified.map((record) => record.canonical_stock_asset_id!))]; const count = (test: (item: RmmCensusPairRecord) => boolean) => records.filter(test).length;
  const grouped = new Map<string, number>(); for (const record of verified) grouped.set(record.claimed_stock_symbol, (grouped.get(record.claimed_stock_symbol) ?? 0) + 1); const ranked = [...grouped.entries()].sort((a,b) => b[1] - a[1] || a[0].localeCompare(b[0])); const top3 = ranked.slice(0, 3);
  const recordPair = (record: RmmCensusPairRecord) => snapshot.pairs.find((pair) => pair.mission_contract === record.mission_contract && pair.stock_asset_id === record.canonical_stock_asset_id);
  const d7EligibleRecords = verified.filter((record) => { const pair = recordPair(record); return Boolean(pair && Date.parse(pair.launched_at) <= at.getTime() - 7 * 86_400_000); });
  const persistenceEvaluatedRecords = d7EligibleRecords.filter((record) => {
    const pair = recordPair(record)!;
    const lifecycleObserved = snapshot.lifecycle.some((item) => item.pair_id === pair.pair_id && item.checkpoint === 'D7' && item.state === 'OBSERVED');
    const aiD7 = record.claimed_stock_symbol === 'NVDA' && record.claimed_mission_symbol === 'AI' && snapshot.long_inventory_history.some((item) => Date.parse(item.observed_at) >= Date.parse(pair.launched_at) + 7 * 86_400_000);
    return lifecycleObserved || aiD7;
  });
  const persistentAssetIds = [...new Set(persistenceEvaluatedRecords.map((record) => record.canonical_stock_asset_id!))];
  const categories = [...new Set(verified.map((record) => record.category).filter((item): item is RmmCategory => Boolean(item)))]; const percentage = assets.length ? activated.length / assets.length * 100 : null;
  const identityCount = records.filter((record) => record.mission_contract).length; const poolCount = records.filter((record) => record.pool_id).length; const directionCount = records.filter((record) => record.quote_direction !== 'UNRESOLVED').length; const inventoryCount = records.filter((record) => record.inventory_accounting_capability === 'AVAILABLE').length;
  const categoryEvidence = categories.length >= 3 ? 'CROSS_CATEGORY' as const : activated.length >= 2 ? 'EARLY_MULTI_ASSET' as const : verified.length ? 'ANECDOTAL' as const : 'INSUFFICIENT_DATA' as const;
  return frozen({ object_type: 'RMM_CATEGORY_CENSUS', census_id: id('rmm-category-census', observed_at, snapshot.refreshed_at), observed_at, methodology_version: RMM_CENSUS_METHOD_VERSION, immutable: true as const,
    canonical_stock_token_universe: { qualification: 'ACTIVE_CANONICAL_STOCK_TOKEN', methodology_version: ACTIVE_CANONICAL_STOCK_TOKEN_METHOD_VERSION, asset_count: assets.length, registry_observed_at: latestDate(assets.map((asset) => asset.observed_at)), registry_fetched_at: latestDate(assets.map((asset) => asset.fetched_at)), assets: assets.map(({ asset_id, ticker, canonical_contract, current_multiplier, status }) => ({ asset_id, ticker, canonical_contract, current_multiplier, status })) },
    source_claims: { watch_case_id: 'RH_STOCK_MEME_MAP_20260903', claimed_canonical_stock_tokens: 216, claimed_pair_count: 27, claimed_distinct_stock_tickers: 22, parsed_pair_count: records.length, parsed_distinct_stock_tickers: new Set(records.map((record) => record.claimed_stock_symbol)).size, count_reconciliation_state: records.length === 27 && new Set(records.map((record) => record.claimed_stock_symbol)).size === 22 ? 'MATCH' : 'SOURCE_COUNT_MISMATCH', source_note: 'The supplied human-readable examples contain 25 pairs across 21 tickers; two pairs and one ticker required by the headline are absent.' },
    pairs: records, claimed_pair_count: 27, verified_pair_count: verified.length, distinct_claimed_stock_tickers: 22, distinct_verified_stock_tickers: activated.length, unverified_pair_count: 27 - verified.length, inactive_pair_count: count((record) => record.current_activity_state === 'INACTIVE'), not_reproducible_count: count((record) => record.verification_state === 'NOT_REPRODUCIBLE'), noncanonical_pair_count: count((record) => record.verification_state === 'NONCANONICAL_STOCK_ASSET'), quote_direction_unresolved_count: count((record) => record.quote_direction === 'UNRESOLVED'),
    rmm_penetration: { numerator: activated.length, denominator: assets.length, percentage, qualifying_stock_asset_ids: activated, methodology_version: RMM_CENSUS_METHOD_VERSION, observed_at }, rmm_pair_density: { verified_rmm_pair_count: verified.length, activated_stock_token_tickers: activated.length, value: activated.length ? verified.length / activated.length : null },
    persistent_rmm_penetration: { status: persistenceEvaluatedRecords.length === d7EligibleRecords.length && d7EligibleRecords.length ? 'AVAILABLE' : persistenceEvaluatedRecords.length ? 'PARTIAL' : 'UNAVAILABLE', numerator: persistenceEvaluatedRecords.length ? persistentAssetIds.length : null, denominator: assets.length, percentage: persistenceEvaluatedRecords.length && assets.length ? persistentAssetIds.length / assets.length * 100 : null, persistence_coverage: { eligible_for_d7: d7EligibleRecords.length, evaluated: persistenceEvaluatedRecords.length }, note: 'Only a verified direct pair with an observed D7 lifecycle or the existing AI/NVDA D7 evidence can contribute; no recent launch is presumed persistent.' }, verification_coverage: { claim_coverage: `${records.length}/27`, identity_coverage: `${identityCount}/${records.length}`, pool_coverage: `${poolCount}/${records.length}`, quote_direction_coverage: `${directionCount}/${records.length}`, persistence_coverage: `${persistenceEvaluatedRecords.length}/${records.length}`, inventory_coverage: `${inventoryCount}/${records.length}`, percentage: records.length / 27 * 100 }, category_breadth: { categories, count: categories.length }, concentration: { top_stock_token: ranked[0]?.[0] ?? null, top_3_stock_tokens: top3.map(([ticker]) => ticker), top_3_pair_share_pct: verified.length ? top3.reduce((sum, [, value]) => sum + value, 0) / verified.length * 100 : null }, category_evidence: { breadth_state: categoryEvidence, persistence_state: persistentAssetIds.length >= 2 ? 'PERSISTENT_MULTI_ASSET' : assets.length ? 'PERSISTENCE_UNPROVEN' : 'UNAVAILABLE', ra1_impact: 'BREADTH_SUPPORT_ONLY_NOT_CONFIRMED' }, data_gaps: ['Watch headline does not reconcile to supplied pair examples.', 'No inferred mission contract, pool, or quote direction is accepted.', 'D7 persistence is unavailable until a direct pair has genuine lifecycle evidence.'], next_deep_audit_candidates: deepQueue(records), research_tree: { root: 'RWA ACTIVATION', depth: ['AI/NVDA', 'T0 → D1 → D3 → D7 → D30', 'does capital persist?'], breadth: ['RMM CATEGORY CENSUS', 'claimed → verified → persistent', 'does the market convention spread?'], feeds: 'CATEGORY EVIDENCE', then: 'RA1' } });
}

function isExcludedAsset(asset: CanonicalStockAsset) { return /deprecated|leveraged|3x|2x|inverse|mission|synthetic/i.test(`${asset.ticker} ${asset.name}`); }
function classifyActivity(observation: ReflexiveSnapshot['observations'][number] | undefined): RmmActivityState { if (!observation || !observation.fresh) return 'UNKNOWN'; const liquidity = observation.liquidity_usd ?? 0; const volume = observation.volume_24h_usd ?? 0; return volume > 0 ? 'ACTIVE' : liquidity > 0 ? 'LOW_ACTIVITY' : observation.active_liquidity && observation.active_liquidity !== '0' ? 'LOW_ACTIVITY' : 'INACTIVE'; }
function venue(value?: string): RmmVenue { const v = (value ?? '').toUpperCase(); return v.includes('LONG') ? 'LONG' : v.includes('DOPPLER') ? 'DOPPLER' : v.includes('PAIR') ? 'PAIR' : v.includes('PONS') ? 'PONS' : v.includes('BANKR') ? 'BANKR' : v.includes('UNISWAP') ? 'UNISWAP_DIRECT' : v ? 'OTHER' : 'UNKNOWN'; }
function category(ticker: string): RmmCategory { if (['NVDA','MU','ASML','QUBT','TSM','SNDK'].includes(ticker)) return 'SEMICONDUCTORS'; if (['AAPL','AMZN','RBLX','FIGMA'].includes(ticker)) return 'CONSUMER_TECH'; if (['HIMS','LLY','MRNA'].includes(ticker)) return 'HEALTHCARE'; if (ticker === 'SPCX') return 'SPACE'; if (['MSTR','COIN'].includes(ticker)) return 'CRYPTO_FINANCIAL'; if (ticker === 'SPY') return 'INDEX_ETF'; if (ticker === 'GLD') return 'COMMODITY_GOLD_EXPOSURE'; return 'OTHER'; }
function gaps(asset: CanonicalStockAsset | undefined, pair: ReflexiveSnapshot['pairs'][number] | undefined, observation: ReflexiveSnapshot['observations'][number] | undefined) { const gaps: string[] = []; if (!asset) gaps.push('Canonical active Stock Token is unresolved.'); if (!pair) gaps.push('Mission identity, exact pool identity, and deterministic quote direction are unresolved.'); if (pair && !observation) gaps.push('Current activity observation unavailable.'); return gaps; }
function deepQueue(records: RmmCensusPairRecord[]) { const priority = ['PLTR','HIMS','NVDA']; return priority.map((ticker) => records.find((record) => record.claimed_stock_symbol === ticker)).filter((record): record is RmmCensusPairRecord => Boolean(record)).map((record) => ({ stock_symbol: record.claimed_stock_symbol, mission_symbol: record.claimed_mission_symbol, reason: record.claimed_stock_symbol === 'PLTR' ? 'PLTR relevance; census-only, no shadow or preflight mutation.' : record.claimed_stock_symbol === 'HIMS' ? 'Historical falsification and dead-market preservation.' : 'Existing Radar adapter and D7 evidence availability.' })); }
function latestDate(values: string[]) { return values.length ? values.sort().at(-1)! : null; }
function id(...values: string[]) { return createHash('sha256').update(values.join('|')).digest('hex').slice(0, 32); }
function frozen<T>(value: T): T { const freeze = (item: any): any => { if (item && typeof item === 'object' && !Object.isFrozen(item)) { Object.freeze(item); for (const child of Object.values(item)) freeze(child); } return item; }; return freeze(value); }
