import { describe, expect, it } from 'vitest';
import { createApp } from '../src/api/app';
import { emptyIntelligenceStore } from '../src/services/intelligenceStore';

describe('openapi discovery', () => {
  it('serves valid OpenAPI JSON from /openapi.json', async () => {
    const app = await createApp(emptyIntelligenceStore());
    const response = await app.inject({ method: 'GET', url: '/openapi.json' });

    expect(response.statusCode).toBe(200);
    expect(response.headers['content-type']).toContain('application/json');

    const spec = response.json();
    expect(spec.openapi).toBe('3.1.0');
    expect(spec.info.title).toContain('Infopunks Pay.sh Radar');
    expect(spec.components.schemas.ErrorEnvelope).toBeTruthy();

    await app.close();
  });

  it('documents agent preflight, batch preflight, CSV, risk, history, and readiness routes', async () => {
    const app = await createApp(emptyIntelligenceStore());
    const spec = (await app.inject({ method: 'GET', url: '/openapi.json' })).json();

    expect(spec.paths['/v1/radar/preflight']?.post).toBeTruthy();
    expect(spec.paths['/v1/radar/preflight/batch']?.post).toBeTruthy();
    expect(spec.paths['/v1/radar/export/providers.csv']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/export/endpoints.csv']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/export/route-candidates.csv']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/export/degradations.csv']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/risk/providers/{provider_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/risk/endpoints/{endpoint_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/risk/ecosystem']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/history/providers/{provider_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/history/endpoints/{endpoint_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/history/ecosystem']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/mappings']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/mapping-targets']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmark-readiness']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmark-summary']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/evidence-ledger']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/evidence-ledger/brief']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/agent-readiness']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/agent-readiness/{provider_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/bundles']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/bundles/{bundle_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/bundles/{bundle_id}/runs']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/bundles/{bundle_id}/runs/{run_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/bundles/{bundle_id}/plan']?.post).toBeTruthy();
    expect(spec.paths['/v1/radar/superiority-readiness']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmarks/finance-data-token-search']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmarks/finance-data-token-metadata']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmarks/communications-email-delivery']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmarks/solana-infra-account-balance']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmarks/social-data-reddit-post-search']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmarks/audio-speech-transcription']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmarks/document-ocr-text-extraction']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmarks/finance-data-sol-price/history']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmark-history']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmark-history/{benchmark_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmark-history/{benchmark_id}/routes']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmark-history/{benchmark_id}/routes/{route_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmark-artifacts']?.get).toBeTruthy();
    expect(spec.paths['/v1/radar/benchmark-artifacts/{artifact_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/pre-spend/check']?.post).toBeTruthy();
    expect(spec.paths['/v1/pre-spend/providers']?.get).toBeTruthy();
    expect(spec.paths['/v1/pre-spend/providers/{provider_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/routes']?.get).toBeTruthy();
    expect(spec.paths['/v1/routes/{route_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/services']?.get).toBeTruthy();
    expect(spec.paths['/v1/services/{service_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/receipts']?.get).toBeTruthy();
    expect(spec.paths['/v1/receipts/{event_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/validation/submit']?.post).toBeTruthy();
    expect(spec.paths['/v1/check']?.post).toBeTruthy();
    expect(spec.paths['/v1/checks']?.get).toBeTruthy();
    expect(spec.paths['/v1/checks/{check_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/narratives']?.get).toBeTruthy();
    expect(spec.paths['/v1/attention-market-watch']?.get).toBeTruthy();
    expect(spec.paths['/v1/attention-market-watch/{slug}']?.get).toBeTruthy();
    expect(spec.paths['/v1/attention-market-watch/intake']?.post).toBeTruthy();
    expect(spec.paths['/v1/attention-market-watch/intake/requirements']?.get).toBeTruthy();
    expect(spec.paths['/v1/signal-desk']?.get).toBeTruthy();
    expect(spec.paths['/v1/signal-desk/candidates']?.get).toBeTruthy();
    expect(spec.paths['/v1/signal-desk/candidates/{candidateId}']?.get).toBeTruthy();
    expect(spec.paths['/v1/signal-hunt']?.get).toBeTruthy();
    expect(spec.paths['/v1/signal-hunt/{signalId}']?.get).toBeTruthy();
    expect(spec.paths['/v1/signal-hunt/submit']?.post).toBeTruthy();
    expect(spec.paths['/v1/signal-hunt/{signalId}/verify']?.post).toBeTruthy();
    expect(spec.paths['/v1/unicorn-radar']?.get).toBeTruthy();
    expect(spec.paths['/v1/unicorn-radar/candidates']?.get).toBeTruthy();
    expect(spec.paths['/v1/unicorn-radar/candidates/{candidateId}']?.get).toBeTruthy();
    expect(spec.paths['/v1/unicorn-radar/submit']?.post).toBeTruthy();
    expect(spec.paths['/v1/unicorn-radar/request-evaluation']?.post).toBeTruthy();
    expect(spec.paths['/v1/evaluation-request']?.post).toBeTruthy();
    expect(spec.paths['/v1/unicorn-radar/revenue-receipts']?.get).toEqual(expect.objectContaining({
      deprecated: true,
      description: expect.stringContaining('Compatibility route'),
      summary: 'List Unicorn Radar revenue receipts'
    }));
    expect(spec.paths['/v1/revenue-receipts']?.get).toBeTruthy();
    expect(spec.paths['/v1/revenue-receipts/{receiptId}']?.get).toBeTruthy();
    expect(spec.paths['/v1/narratives/{slug}']?.get).toBeTruthy();
    expect(spec.paths['/v1/signals']?.get).toBeTruthy();
    expect(spec.paths['/v1/signals/{slug}']?.get).toBeTruthy();
    expect(spec.paths['/v1/signals/{slug}/updates']?.get).toBeTruthy();
    expect(spec.paths['/v1/signals/{slug}/updates/{updateId}']?.get).toBeTruthy();
    expect(spec.paths['/v1/loops']?.get).toBeTruthy();
    expect(spec.paths['/v1/loops/{loop_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/loops/check']?.post).toBeTruthy();
    expect(spec.paths['/v1/graph']?.get).toBeTruthy();
    expect(spec.paths['/v1/graph/clusters']?.get).toBeTruthy();
    expect(spec.paths['/v1/graph/clusters/{cluster_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/graph/nodes/{node_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/graph/entities/{entity_type}/{entity_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/graph/ripples']?.get).toBeTruthy();
    expect(spec.paths['/v1/graph/check']?.post).toBeTruthy();
    expect(spec.paths['/v1/hermes/skill-pack']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/spend-policy']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/spend-policy/example']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/spend-policy/check']?.post).toBeTruthy();
    expect(spec.paths['/v1/hermes/spend-policy/check/{check_id}/receipt-preview']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/spend-policy/check/{check_id}/receipt']?.post).toBeTruthy();
    expect(spec.paths['/v1/hermes/spend-policy/check/{check_id}/reconciliation-preview']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/spend-policy/check/{check_id}/outcome']?.post).toBeTruthy();
    expect(spec.paths['/v1/hermes/skill-pack/skills']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/skill-pack/skills/{skill_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/reputation-ledger']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/reputation-ledger/providers']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/reputation-ledger/routes']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/wallet-audit-trail']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/wallet-audit-trail/{trail_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/wallet-risk-score']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/wallet-risk-score/{score_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/wallet-safety/check']?.post).toBeTruthy();
    expect(spec.paths['/v1/hermes/wallet-safety/example']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/wallet-safety/integrations']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/wallet-safety/integrations/{integration_id}/readiness']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/wallet-safety/integrations/{integration_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/pre-spend-decision']?.post).toBeTruthy();
    expect(spec.paths['/v1/hermes/pre-spend-decision/example']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/pre-spend-decision/{decision_id}/receipt']?.post).toBeTruthy();
    expect(spec.paths['/v1/hermes/pre-spend-decision/{decision_id}/outcome']?.post).toBeTruthy();
    expect(spec.paths['/v1/hermes/reputation-ledger/{target_type}/{target_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/runs/{run_id}/receipt']?.post).toBeTruthy();
    expect(spec.paths['/v1/hermes/runs/{run_id}/receipt-preview']?.get).toBeTruthy();
    expect(spec.paths['/v1/hermes/runs/{run_id}/claim/promote']?.post).toBeTruthy();
    expect(spec.paths['/v1/hermes/runs/{run_id}/claim/promotion-preview']?.get).toBeTruthy();
    expect(spec.paths['/v1/claims']?.get).toBeTruthy();
    expect(spec.paths['/v1/claims']?.post).toBeTruthy();
    expect(spec.paths['/v1/claims/{claim_id}']?.get).toBeTruthy();
    expect(spec.paths['/v1/claims/{claim_id}/challenges']?.get).toBeTruthy();
    expect(spec.paths['/v1/claims/{claim_id}/challenges']?.post).toBeTruthy();
    expect(spec.components.schemas.RouteIntelligence).toBeTruthy();
    expect(spec.components.schemas.BuilderProviderIntelligence).toBeTruthy();
    expect(spec.components.schemas.ServiceDossier).toBeTruthy();
    expect(spec.components.schemas.PreSpendReceipt).toBeTruthy();
    expect(spec.components.schemas.PreSpendCheckRequest).toBeTruthy();
    expect(spec.components.schemas.PreSpendCheckResponse).toBeTruthy();
    expect(spec.components.schemas.HumanValidationSubmission).toBeTruthy();
    expect(spec.components.schemas.Claim).toBeTruthy();
    expect(spec.components.schemas.ClaimDetail).toBeTruthy();
    expect(spec.components.schemas.ProofCheckInput).toBeTruthy();
    expect(spec.components.schemas.ProofCheckResult).toBeTruthy();
    expect(spec.components.schemas.Loop).toBeTruthy();
    expect(spec.components.schemas.LoopDetail).toBeTruthy();
    expect(spec.components.schemas.LoopRun).toBeTruthy();
    expect(spec.components.schemas.LoopCheckInput).toBeTruthy();
    expect(spec.components.schemas.UnicornRadarCandidate).toBeTruthy();
    expect(spec.components.schemas.UnicornRadarSummary).toBeTruthy();
    expect(spec.components.schemas.UnicornRadarSubmissionInput).toBeTruthy();
    expect(spec.components.schemas.UnicornRadarEvaluationRequestInput).toBeTruthy();
    expect(spec.components.schemas.EvaluationRequestInput).toBeTruthy();
    expect(spec.components.schemas.EvaluationRequestResponse).toBeTruthy();
    expect(spec.components.schemas.UnicornRadarRevenueReceipt).toBeTruthy();
    expect(spec.components.schemas.RevenueReceipt).toBeTruthy();
    expect(spec.components.schemas.RevenueReceiptList).toBeTruthy();
    expect(spec.components.schemas.RevenueReceiptSummary).toBeTruthy();
    expect(spec.components.schemas.HermesSkillPack).toBeTruthy();
    expect(spec.components.schemas.HermesSkill).toBeTruthy();
    expect(spec.components.schemas.HermesRunReceipt).toBeTruthy();
    expect(spec.components.schemas.HermesWalletAuditTrail).toBeTruthy();
    expect(spec.components.schemas.HermesWalletAuditEvent).toBeTruthy();
    expect(spec.components.schemas.HermesWalletAuditEventKind).toBeTruthy();
    expect(spec.components.schemas.HermesWalletAuditEventState).toBeTruthy();
    expect(spec.components.schemas.HermesWalletAuditSummary).toBeTruthy();
    expect(spec.components.schemas.HermesWalletAuditSignal).toBeTruthy();
    expect(spec.components.schemas.HermesWalletAuditReference).toBeTruthy();
    expect(spec.components.schemas.HermesWalletAuditRiskPosture).toBeTruthy();
    expect(spec.components.schemas.HermesWalletRiskScore).toBeTruthy();
    expect(spec.components.schemas.HermesWalletSafetyRating).toBeTruthy();
    expect(spec.components.schemas.HermesWalletRequiredNextAction).toBeTruthy();
    expect(spec.components.schemas.HermesWalletRiskFactor).toBeTruthy();
    expect(spec.components.schemas.HermesWalletPositiveControl).toBeTruthy();
    expect(spec.components.schemas.HermesWalletRiskScoreInput).toBeTruthy();
    expect(spec.components.schemas.HermesWalletRiskScoreSummary).toBeTruthy();
    expect(spec.components.schemas.HermesWalletSafetyCheckInput).toBeTruthy();
    expect(spec.components.schemas.HermesWalletSafetyCheckResult).toBeTruthy();
    expect(spec.components.schemas.HermesWalletFinalRecommendation).toBeTruthy();
    expect(spec.components.schemas.HermesWalletSafetyDecision).toBeTruthy();
    expect(spec.components.schemas.HermesWalletSafetyReference).toBeTruthy();
    expect(spec.components.schemas.HermesWalletSafetyBundleSummary).toBeTruthy();
    expect(spec.components.schemas.WalletSafetyIntegrationReadinessState).toBeTruthy();
    expect(spec.components.schemas.WalletSafetyIntegrationRequirementStatus).toBeTruthy();
    expect(spec.components.schemas.WalletSafetyIntegrationProofItemSource).toBeTruthy();
    expect(spec.components.schemas.WalletSafetyIntegrationProfile).toBeTruthy();
    expect(spec.components.schemas.WalletSafetyIntegrationRequirement).toBeTruthy();
    expect(spec.components.schemas.WalletSafetyIntegrationProofItem).toBeTruthy();
    expect(spec.components.schemas.WalletSafetyIntegrationRegistrySummary).toBeTruthy();
    expect(spec.components.schemas.WalletSafetyIntegrationReadinessReport).toBeTruthy();
    expect(spec.components.schemas.HermesClaimCandidate).toBeTruthy();
    expect(spec.components.schemas.HermesRunReceiptConversion).toBeTruthy();
    expect(spec.components.schemas.HermesClaimReviewState).toBeTruthy();
    expect(spec.components.schemas.HermesPromotedClaim).toBeTruthy();
    expect(spec.components.schemas.HermesClaimPromotionResult).toBeTruthy();
    expect(spec.components.schemas.HermesReputationImpact).toBeTruthy();
    expect(spec.components.schemas.HermesReputationLedgerSummary).toBeTruthy();
    expect(spec.components.schemas.HermesReputationLedgerEntry).toBeTruthy();
    expect(spec.components.schemas.HermesReputationLedgerEvent).toBeTruthy();
    expect(spec.components.schemas.HermesReputationState).toBeTruthy();
    expect(spec.components.schemas.HermesReputationDirection).toBeTruthy();
    expect(spec.components.schemas.HermesPreSpendDecisionInput).toBeTruthy();
    expect(spec.components.schemas.HermesPreSpendDecision).toBeTruthy();
    expect(spec.components.schemas.HermesPreSpendDecisionState).toBeTruthy();
    expect(spec.components.schemas.HermesPreSpendRequiredAction).toBeTruthy();
    expect(spec.components.schemas.HermesPreSpendRiskFactor).toBeTruthy();
    expect(spec.components.schemas.HermesPreSpendDecisionInputReference).toBeTruthy();
    expect(spec.components.schemas.HermesSpendPolicy).toBeTruthy();
    expect(spec.components.schemas.HermesSpendPolicyCheckInput).toBeTruthy();
    expect(spec.components.schemas.HermesSpendPolicyCheckResult).toBeTruthy();
    expect(spec.components.schemas.HermesSpendPolicyDecision).toBeTruthy();
    expect(spec.components.schemas.HermesSpendPolicyRule).toBeTruthy();
    expect(spec.components.schemas.HermesSpendPolicyViolation).toBeTruthy();
    expect(spec.components.schemas.HermesSpendPolicyReference).toBeTruthy();
    expect(spec.components.schemas.HermesPolicyDecisionReceipt).toBeTruthy();
    expect(spec.components.schemas.HermesPolicyDecisionReceiptConversion).toBeTruthy();
    expect(spec.components.schemas.HermesPolicyAuditTrail).toBeTruthy();
    expect(spec.components.schemas.HermesPolicyAuditTrailEvent).toBeTruthy();
    expect(spec.components.schemas.HermesPolicyReceiptRiskSummary).toBeTruthy();
    expect(spec.components.schemas.HermesDecisionReceipt).toBeTruthy();
    expect(spec.components.schemas.HermesDecisionOutcome).toBeTruthy();
    expect(spec.components.schemas.HermesDecisionOutcomeState).toBeTruthy();
    expect(spec.components.schemas.HermesDecisionOutcomeImpact).toBeTruthy();
    expect(spec.components.schemas.HermesDecisionFeedbackResult).toBeTruthy();
    expect(spec.components.schemas.HermesDecisionReceiptConversion).toBeTruthy();
    expect(spec.components.schemas.SignalGraphResponse).toBeTruthy();
    expect(spec.components.schemas.SignalGraphCluster).toBeTruthy();
    expect(spec.components.schemas.SignalGraphNode).toBeTruthy();
    expect(spec.components.schemas.SignalGraphEdge).toBeTruthy();
    expect(spec.components.schemas.SignalGraphRipple).toBeTruthy();
    expect(spec.components.schemas.SignalGraphEntityType).toBeTruthy();
    expect(spec.components.schemas.SignalGraphEntityLookupResponse).toBeTruthy();
    expect(spec.components.schemas.SignalGraphCheckInput).toBeTruthy();
    expect(spec.components.schemas.SignalGraphCheckResponse).toBeTruthy();
    expect(spec.components.schemas.NarrativeAssetResponse).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketSignal).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketCategory).toBeTruthy();
    expect(spec.components.schemas.AttentionSourceType).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketVerdict).toBeTruthy();
    expect(spec.components.schemas.NarrativeEvolutionStage).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketEvolutionStage).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketEvolutionStageDefinition).toBeTruthy();
    expect(spec.components.schemas.MovementStatus).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketWatchListResponse).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketWatchDetailResponse).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketIntakeRequest).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketIntakeSubmission).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketIntakeSubmissionResponse).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketIntakeRequirementsResponse).toBeTruthy();
    expect(spec.components.schemas.NarrativeSignalSurfaceResponse).toBeTruthy();
    expect(spec.components.schemas.SignalDeskIndex).toBeTruthy();
    expect(spec.components.schemas.SignalRiskFacet).toBeTruthy();
    expect(spec.components.schemas.CandidateSignal).toBeTruthy();
    expect(spec.components.schemas.CandidateSignalCategory).toBeTruthy();
    expect(spec.components.schemas.CandidateSignalStatus).toBeTruthy();
    expect(spec.components.schemas.CandidateSignalPriority).toBeTruthy();
    expect(spec.components.schemas.CandidateSignalRiskLevel).toBeTruthy();
    expect(spec.components.schemas.SignalHuntProofState).toBeTruthy();
    expect(spec.components.schemas.SignalHuntHuntState).toBeTruthy();
    expect(spec.components.schemas.SignalHuntDecisionState).toBeTruthy();
    expect(spec.components.schemas.SignalHuntCandidate).toBeTruthy();
    expect(spec.components.schemas.SignalHuntSummary).toBeTruthy();
    expect(spec.components.schemas.SignalHuntSubmissionInput).toBeTruthy();
    expect(spec.components.schemas.SignalHuntVerifyInput).toBeTruthy();
    expect(spec.components.schemas.SignalDeskReportCard).toBeTruthy();
    expect(spec.components.schemas.SignalDeskDispatchCard).toBeTruthy();
    expect(spec.components.schemas.SignalDeskActivityItem).toBeTruthy();
    expect(spec.components.schemas.SignalEvidenceUpdateType).toBeTruthy();
    expect(spec.components.schemas.SignalEvidenceUpdate).toBeTruthy();
    expect(spec.components.schemas.SignalEvidenceUpdateListResponse).toBeTruthy();
    expect(spec.components.schemas.SignalEvidenceUpdateDetailResponse).toBeTruthy();
    expect(spec.components.schemas.ClaimCreateRequest).toBeTruthy();
    expect(spec.components.schemas.ClaimChallenge).toBeTruthy();
    expect(spec.components.schemas.ClaimChallengeCreateRequest).toBeTruthy();
    expect(spec.components.schemas.PreSpendRouteDetailResponse).toBeTruthy();
    expect(spec.components.schemas.PreSpendProviderDetailResponse).toBeTruthy();
    expect(spec.components.schemas.PreSpendProviderSummary).toBeTruthy();
    expect(spec.components.schemas.PreSpendProviderListResponse).toBeTruthy();
    expect(spec.components.schemas.PreSpendServiceDetailResponse).toBeTruthy();
    expect(spec.components.schemas.PreSpendReceiptDetailResponse).toBeTruthy();
    expect(spec.components.schemas.RouteTrustSummary).toBeTruthy();
    expect(spec.components.schemas.ProviderTrustProfile).toBeTruthy();
    expect(spec.components.schemas.ServiceDecisionMap).toBeTruthy();
    expect(spec.components.schemas.ReceiptImpact).toBeTruthy();
    expect(spec.components.schemas.PreSpendRouteDetailResponse.properties.validation_state).toBeTruthy();
    expect(spec.components.schemas.PreSpendProviderDetailResponse.properties.trust_profile.$ref).toBe('#/components/schemas/ProviderTrustProfile');
    expect(spec.components.schemas.PreSpendProviderListResponse.properties.providers.items.$ref).toBe('#/components/schemas/PreSpendProviderSummary');
    expect(spec.components.schemas.PreSpendServiceDetailResponse.properties.best_route_decision_map.$ref).toBe('#/components/schemas/ServiceDecisionMap');
    expect(spec.components.schemas.PreSpendReceiptDetailResponse.properties.impact.$ref).toBe('#/components/schemas/ReceiptImpact');
    expect(JSON.stringify(spec.paths['/v1/pre-spend/providers'])).toContain('canonical pre-spend');
    expect(JSON.stringify(spec.paths['/v1/pre-spend/providers/{provider_id}'])).toContain('provider_not_found');
    expect(JSON.stringify(spec.paths['/v1/routes/{route_id}'])).toContain('route trust summary');
    expect(JSON.stringify(spec.paths['/v1/services/{service_id}'])).toContain('best route decision map');
    expect(JSON.stringify(spec.paths['/v1/receipts/{event_id}'])).toContain('pre-spend receipt detail');
    expect(JSON.stringify(spec.paths['/v1/check'])).toContain('Infopunks Receipt Check');
    expect(JSON.stringify(spec.paths['/v1/checks/{check_id}'])).toContain('proof_check_not_found');
    expect(JSON.stringify(spec.paths['/v1/loops'])).toContain('proof states');
    expect(JSON.stringify(spec.paths['/v1/loops/{loop_id}'])).toContain('loop_not_found');
    expect(JSON.stringify(spec.paths['/v1/graph'])).toContain('Stop scrolling the feed. Read the graph.');
    expect(JSON.stringify(spec.paths['/v1/graph/clusters/{cluster_id}'])).toContain('signal_graph_cluster_not_found');
    expect(JSON.stringify(spec.paths['/v1/graph/nodes/{node_id}'])).toContain('signal_graph_node_not_found');
    expect(JSON.stringify(spec.paths['/v1/graph/entities/{entity_type}/{entity_id}'])).toContain('unsupported_signal_graph_entity_type');
    expect(JSON.stringify(spec.paths['/v1/hermes/skill-pack'])).toContain('Infopunks Pre-Spend Skill Pack');
    expect(JSON.stringify(spec.paths['/v1/hermes/spend-policy'])).toContain('seeded spend policies');
    expect(JSON.stringify(spec.paths['/v1/hermes/spend-policy/check'])).toContain('allow, test, review, or block decision');
    expect(JSON.stringify(spec.paths['/v1/hermes/spend-policy/check/{check_id}/receipt-preview'])).toContain('hermes_spend_policy_check_not_found');
    expect(JSON.stringify(spec.paths['/v1/hermes/spend-policy/check/{check_id}/receipt'])).toContain('hermes_spend_policy_check_not_found');
    expect(JSON.stringify(spec.paths['/v1/hermes/spend-policy/check/{check_id}/reconciliation-preview'])).toContain('deterministic preview reconciliation');
    expect(JSON.stringify(spec.paths['/v1/hermes/spend-policy/check/{check_id}/outcome'])).toContain('wallet obeyed the safety gate');
    expect(JSON.stringify(spec.paths['/v1/hermes/reputation-ledger'])).toContain('stateless and does not require a live Hermes sidecar');
    expect(JSON.stringify(spec.paths['/v1/hermes/wallet-audit-trail'])).toContain('stitches spend intent, pre-spend decision, receipts, policy check, wallet outcome, reconciliation, and feedback into one timeline');
    expect(JSON.stringify(spec.paths['/v1/hermes/wallet-audit-trail/{trail_id}'])).toContain('hermes_wallet_audit_trail_not_found');
    expect(JSON.stringify(spec.paths['/v1/hermes/wallet-risk-score'])).toContain('wallet risk score summary derived from the Autonomous Wallet Audit Trail');
    expect(JSON.stringify(spec.paths['/v1/hermes/wallet-risk-score/{score_id}'])).toContain('hermes_wallet_risk_score_not_found');
    expect(JSON.stringify(spec.paths['/v1/hermes/wallet-safety/check'])).toContain('Agents should not stitch safety together');
    expect(JSON.stringify(spec.paths['/v1/hermes/wallet-safety/example'])).toContain('deterministic example Wallet Safety API Bundle');
    expect(JSON.stringify(spec.paths['/v1/hermes/pre-spend-decision'])).toContain('deterministic spend recommendation');
    expect(JSON.stringify(spec.paths['/v1/hermes/pre-spend-decision/example'])).toContain('deterministic example pre-spend decision');
    expect(JSON.stringify(spec.paths['/v1/hermes/pre-spend-decision/{decision_id}/receipt'])).toContain('stateless, deterministic');
    expect(JSON.stringify(spec.paths['/v1/hermes/pre-spend-decision/{decision_id}/outcome'])).toContain('does not mutate receipts, claims, or reputation ledger entries persistently');
    expect(JSON.stringify(spec.paths['/v1/hermes/reputation-ledger/{target_type}/{target_id}'])).toContain('hermes_reputation_entry_not_found');
    expect(JSON.stringify(spec.paths['/v1/hermes/runs/{run_id}/receipt'])).toContain('does not mutate existing receipts or claims');
    expect(JSON.stringify(spec.paths['/v1/hermes/runs/{run_id}/claim/promote'])).toContain('does not mutate persistent claims or reputation records');
    expect(JSON.stringify(spec.paths['/v1/claims'])).toContain('No claim without evidence');
    expect(JSON.stringify(spec.paths['/v1/claims/{claim_id}/challenges'])).toContain('Claims are not token markets yet');
    expect(JSON.stringify(spec.paths['/v1/signals/{slug}/updates'])).toContain('watching the narratives that become markets');
    expect(JSON.stringify(spec.paths['/v1/signal-desk'])).toContain('featured report');
    expect(JSON.stringify(spec.paths['/v1/signal-desk/candidates'])).toContain('seeded candidate queue');
    expect(JSON.stringify(spec.paths['/v1/signal-desk/candidates/{candidateId}'])).toContain('candidate_signal_not_found');
    expect(JSON.stringify(spec.paths['/v1/signal-hunt'])).toContain('cultural intake layer');
    expect(JSON.stringify(spec.paths['/v1/signal-hunt/{signalId}'])).toContain('signal_hunt_not_found');
    expect(JSON.stringify(spec.paths['/v1/signal-hunt/submit'])).toContain('not a financial promise');
    expect(JSON.stringify(spec.paths['/v1/attention-market-watch/{slug}'])).toContain('attention_market_signal_not_found');
    expect(JSON.stringify(spec.paths['/v1/attention-market-watch/intake'])).toContain('not an endorsement');
    expect(spec.components.schemas.SignalRiskFacet.enum).toEqual(['high_reflexivity', 'power_concentration', 'unproven_sovereignty', 'kol_dependency', 'thin_evidence', 'narrative_fatigue', 'live_watch']);
    expect(spec.components.schemas.AttentionMarketVerdict.enum).toEqual(['attention_arbitrage', 'extraction_risk', 'cult_sludge', 're_index_watch', 'movement_candidate', 'signal_market_candidate', 'supportive_watch']);
    expect(spec.components.schemas.AttentionMarketIntakeSubmission.properties.status.$ref).toBe('#/components/schemas/AttentionMarketIntakeStatus');
    expect(JSON.stringify(spec.paths['/v1/signals/{slug}/updates/{updateId}'])).toContain('signal_update_not_found');
    expect(spec.components.schemas.CandidateSignal.properties.category.$ref).toBe('#/components/schemas/CandidateSignalCategory');
    expect(spec.components.schemas.CandidateSignal.properties.status.$ref).toBe('#/components/schemas/CandidateSignalStatus');
    expect(spec.components.schemas.CandidateSignal.properties.risk_facets.items.$ref).toBe('#/components/schemas/SignalRiskFacet');
    expect(spec.components.schemas.SignalDeskReportCard.properties.risk_facets.items.$ref).toBe('#/components/schemas/SignalRiskFacet');
    expect(spec.components.schemas.SignalDeskDispatchCard.properties.risk_facets.items.$ref).toBe('#/components/schemas/SignalRiskFacet');
    expect(spec.components.schemas.SignalDeskIndex.properties.candidate_signals.items.$ref).toBe('#/components/schemas/CandidateSignal');
    expect(spec.components.schemas.SignalEvidenceUpdateType.enum).toEqual(['attention_shift', 'holder_shift', 'myth_shift', 'risk_shift', 'verdict_change']);
    expect(spec.components.schemas.SignalEvidenceUpdate.properties.update_type.$ref).toBe('#/components/schemas/SignalEvidenceUpdateType');
    expect(spec.components.schemas.NarrativeSignalSurfaceResponse.properties.infopunk_verdict).toBeTruthy();
    expect(spec.components.schemas.NarrativeSignalSurfaceResponse.properties.verdict_label).toBeTruthy();
    expect(spec.components.schemas.NarrativeSignalSurfaceResponse.properties.verdict_state).toBeTruthy();
    expect(spec.components.schemas.NarrativeSignalSurfaceResponse.properties.current_evolution_stage.$ref).toBe('#/components/schemas/NarrativeEvolutionStage');
    expect(spec.components.schemas.NarrativeSignalSurfaceResponse.properties.current_evolution_label).toBeTruthy();
    expect(spec.components.schemas.NarrativeSignalSurfaceResponse.properties.movement_status.$ref).toBe('#/components/schemas/MovementStatus');
    expect(spec.components.schemas.NarrativeSignalSurfaceResponse.properties.movement_status_label).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketSignal.properties.current_evolution_label).toBeTruthy();
    expect(spec.components.schemas.AttentionMarketSignal.properties.current_evolution_stage.$ref).toBe('#/components/schemas/AttentionMarketEvolutionStage');
    expect(spec.components.schemas.AttentionMarketWatchListResponse.properties.evolution_stages.items.$ref).toBe('#/components/schemas/AttentionMarketEvolutionStageDefinition');
    expect(spec.components.schemas.NarrativeSignalCard.properties.decision_state.enum).toContain('durable_re_index');
    expect(spec.components.schemas.NarrativeSignalSurfaceResponse.properties.verdict_state.enum).toContain('durable_re_index');
    expect(spec.components.schemas.NarrativeSignalSurfaceResponse.properties.verdict_copy).toBeTruthy();
    expect(spec.components.schemas.BenchmarkRouteMetric.properties.status_code).toBeTruthy();
    expect(spec.components.schemas.BenchmarkRouteMetric.properties.status_evidence).toBeTruthy();
    expect(spec.components.schemas.BenchmarkRouteMetric.properties.execution_transport).toBeTruthy();
    expect(spec.components.schemas.BenchmarkSummaryResponse).toBeTruthy();
    expect(spec.components.schemas.EvidenceLedgerResponse).toBeTruthy();
    expect(spec.components.schemas.EvidenceLedgerBriefResponse).toBeTruthy();
    expect(spec.components.schemas.AgentReadinessListResponse).toBeTruthy();
    expect(spec.components.schemas.AgentReadinessCard).toBeTruthy();
    expect(spec.components.schemas.AgentReadinessState.enum).toContain('recorded_evidence');
    expect(spec.components.schemas.AgentSpendReadiness.enum).toContain('ready_for_inspection');
    expect(spec.components.schemas.AgentReadinessCard.properties.what_this_means).toBeTruthy();
    expect(spec.components.schemas.AgentReadinessCard.properties.agent_readiness_summary.$ref).toBe('#/components/schemas/BundleRunAgentReadinessSummary');
    expect(JSON.stringify(spec.paths['/v1/radar/agent-readiness'])).toContain('what_this_means');
    expect(JSON.stringify(spec.paths['/v1/radar/agent-readiness/{provider_id}'])).toContain('Artifact-backed route evidence exists. Agents should still inspect caveats before spend.');
    expect(spec.components.schemas.BundleRegistryResponse).toBeTruthy();
    expect(spec.components.schemas.BundleResponse).toBeTruthy();
    expect(spec.components.schemas.BundlePlanRequest).toBeTruthy();
    expect(spec.components.schemas.BundlePlanResponse).toBeTruthy();
    expect(spec.components.schemas.BundleRunSummary).toBeTruthy();
    expect(spec.components.schemas.BundleRunDetail).toBeTruthy();
    expect(spec.components.schemas.BundleRunListResponse).toBeTruthy();
    expect(spec.components.schemas.BundleRunAgentReadinessSummary).toBeTruthy();
    expect(spec.components.schemas.BundleRunListResponse.properties.agent_readiness_summary.$ref).toBe('#/components/schemas/BundleRunAgentReadinessSummary');
    expect(JSON.stringify(spec.paths['/v1/radar/bundles/{bundle_id}/runs'])).toContain('agent_readiness_summary');
    expect(JSON.stringify(spec.paths['/v1/radar/bundles/{bundle_id}/runs'])).toContain('review_ready_caveated');
    expect(spec.components.schemas.BundleStep.properties.execution_boundary.$ref).toBe('#/components/schemas/BundleExecutionBoundary');
    expect(spec.components.schemas.EvidenceLedgerBriefRecordedLane.properties.latest_artifact_recorded_runs).toBeTruthy();
    expect(spec.components.schemas.EvidenceLedgerBriefRecordedLane.properties.total_recorded_runs).toBeTruthy();
    expect(spec.components.schemas.BenchmarkHistoryV2AggregateResponse).toBeTruthy();
    expect(spec.components.schemas.BenchmarkHistoryV2DetailResponse).toBeTruthy();
    expect(spec.components.schemas.BenchmarkRouteHistoryAggregateResponse).toBeTruthy();
    expect(spec.components.schemas.BenchmarkRouteHistoryDetailResponse).toBeTruthy();
    expect(spec.components.schemas.EvidenceHealth).toEqual({ type: 'string', enum: ['recorded', 'caveated', 'stale', 'degraded', 'unverified', 'scaffold'] });
    expect(spec.components.schemas.BenchmarkRouteHistorySummary.properties.evidence_health.$ref).toBe('#/components/schemas/EvidenceHealth');
    expect(spec.components.schemas.BenchmarkRouteHistoryTimelineEntry.properties.evidence_health.$ref).toBe('#/components/schemas/EvidenceHealth');
    expect(spec.components.schemas.BenchmarkRouteHistoryDetailResponse.properties.evidence_health.$ref).toBe('#/components/schemas/EvidenceHealth');
    expect(spec.components.schemas.BenchmarkSummaryResponse.properties.benchmarks.items.$ref).toBe('#/components/schemas/BenchmarkSummaryRow');
    expect(spec.components.schemas.BenchmarkSummaryResponse.properties.total_artifacts).toBeTruthy();
    expect(spec.components.schemas.BenchmarkSummaryResponse.properties.latest_recorded_at).toBeTruthy();
    expect(spec.components.schemas.BenchmarkSummaryRow.properties.description).toBeTruthy();
    expect(JSON.stringify(spec.paths['/v1/radar/benchmark-summary'])).toContain('compact agent benchmark summary');
    expect(JSON.stringify(spec.paths['/v1/radar/benchmark-summary'])).toContain('Use full benchmark endpoints for route-level metrics.');
    expect(JSON.stringify(spec.paths['/v1/radar/benchmark-summary'])).toContain('"label":"Web Search Results"');
    expect(JSON.stringify(spec.paths['/v1/radar/benchmark-summary'])).toContain('"label":"Document OCR Text Extraction"');
    expect(JSON.stringify(spec.paths['/v1/radar/benchmark-summary'])).toContain('"recorded_runs":10');
    expect(JSON.stringify(spec.paths['/v1/radar/benchmark-summary'])).toContain('Search the web for the same query and return normalized search results.');
    expect(JSON.stringify(spec.paths['/v1/radar/benchmark-summary'])).toContain('Extract text from the same simple document/image fixture.');
    expect(JSON.stringify(spec.paths['/v1/radar/superiority-readiness'])).toContain('Get comparison readiness');
    expect(JSON.stringify(spec.paths['/v1/radar/superiority-readiness'])).not.toContain('Superiority Proof');
    expect(JSON.stringify(spec)).not.toContain('Get superiority proof readiness');

    await app.close();
  });

  it('documents the full RH Chain public intelligence route family', async () => {
    const app = await createApp(emptyIntelligenceStore());
    const spec = (await app.inject({ method: 'GET', url: '/openapi.json' })).json();
    const expectedRoutes: Array<[string, 'get' | 'post']> = [
      ['/v1/rh-chain', 'get'], ['/v1/rh-chain/memes', 'get'], ['/v1/rh-chain/signals', 'get'],
      ['/v1/rh-chain/receipts', 'get'], ['/v1/rh-chain/4663-index', 'get'], ['/v1/rh-chain/daily-receipts', 'get'],
      ['/v1/rh-chain/meme-pulse', 'get'], ['/v1/rh-chain/launch-surfaces', 'get'], ['/v1/rh-chain/live-snapshot', 'get'],
      ['/v1/rh-chain/live-snapshot/token/{contract}', 'get'], ['/v1/rh-chain/classifications', 'get'], ['/v1/rh-chain/tokens/{contract}/dossier', 'get'],
      ['/v1/rh-chain/review-queue', 'get'], ['/v1/rh-chain/clone-radar', 'get'], ['/v1/rh-chain/scouts', 'get'],
      ['/v1/rh-chain/distribution-pack', 'get'], ['/v1/rh-chain/signals/submissions', 'get'],
      ['/v1/rh-chain/signals/submit', 'post'], ['/v1/rh-chain/scout/query', 'post']
    ];

    for (const [route, method] of expectedRoutes) {
      const operation = spec.paths[route]?.[method];
      expect(operation).toBeTruthy();
      expect(operation.description).toContain('Public intelligence only');
      expect(operation.description).toContain('never overrides human-reviewed receipts');
      expect(operation.responses['200'].content['application/json'].schema.allOf[0].$ref).toBe('#/components/schemas/RhChainResponseEnvelope');
    }

    expect(spec.components.schemas.RhChainResponseEnvelope.required).toEqual(expect.arrayContaining(['data', 'meta', 'sources', 'generated_at', 'data_mode', 'disclaimer']));
    expect(spec.paths['/v1/rh-chain/signals/submit'].post.requestBody).toBeTruthy();
    expect(spec.paths['/v1/rh-chain/scout/query'].post.requestBody).toBeTruthy();
    expect(spec.components.schemas.RhChainErrorEnvelope.required).toEqual(expect.arrayContaining(['data', 'error', 'meta', 'sources', 'generated_at', 'data_mode', 'disclaimer']));
    expect(spec.paths['/internal/rh-chain/review-console/submissions'].get.security).toEqual([{ bearerAuth: [] }]);
    expect(spec.paths['/internal/rh-chain/review-console/submissions/{submissionId}'].patch.description).toContain('optimistic concurrency');
    const classificationRoutes = [
      ['/internal/rh-chain/classifications', 'get'],
      ['/internal/rh-chain/classifications', 'post'],
      ['/internal/rh-chain/classifications/{contract}', 'get'],
      ['/internal/rh-chain/classifications/{contract}/approve', 'post'],
      ['/internal/rh-chain/classifications/{contract}/reject', 'post'],
      ['/internal/rh-chain/classifications/{contract}/supersede', 'post'],
      ['/internal/rh-chain/classifications/{contract}/audit', 'get'],
      ['/internal/rh-chain/market-structure/cross-layer/conflicts', 'get']
    ] as const;
    for (const [route, method] of classificationRoutes) {
      expect(spec.paths[route]?.[method]).toBeTruthy();
      expect(spec.paths[route][method].security).toEqual([{ bearerAuth: [] }]);
    }
    expect(spec.paths['/internal/rh-chain/classifications/{contract}/approve'].post.description).toContain('optimistic concurrency');
    expect(spec.paths['/internal/rh-chain/classifications'].post.description).toContain('cannot approve, promote, or publish');
    expect(spec.paths['/v1/rh-chain/classifications'].get.description).toContain('only active approved records');
    expect(spec.paths['/v1/rh-chain/market-structure/cross-layer'].get.description).toContain('no provider request');
    expect(spec.paths['/internal/rh-chain/market-structure/cross-layer/conflicts'].get.description).toContain('Read-only reviewer surface');
    expect(spec.components.schemas.RhChainCrossLayerPayload.properties.classification_coverage).toBeTruthy();
    expect(spec.components.schemas.RhChainCrossLayerPayload.properties.bounded_universe).toBeTruthy();
    expect(spec.components.schemas.RhChainCrossLayerConflictPayload.additionalProperties).toBe(false);
    expect(spec.components.schemas.RhChainClassificationProposalRequest.properties.primary_layer.enum).toContain('consumer');
    expect(spec.components.schemas.RhChainClassificationProposalRequest.properties.secondary_layers.items.enum).toContain('ai-narrative');
    expect(spec.components.schemas.RhChainReviewedClassification.additionalProperties).toBe(false);
    expect(spec.components.schemas.RhChainClassificationProposalRequest.additionalProperties).toBe(false);
    expect(spec.components.schemas.RhChainPublicClassification.properties.reviewer_audit).toBeUndefined();
    await app.close();
  });

  it('documents machine execution receipt ingest and BigQuery fixture endpoints with strict caveats', async () => {
    const app = await createApp(emptyIntelligenceStore());
    const spec = (await app.inject({ method: 'GET', url: '/openapi.json' })).json();

    const ingest = spec.paths['/v1/machine-execution/receipts/ingest']?.post;
    const fixtureSample = spec.paths['/v1/machine-execution/bigquery/fixtures/bounded-query']?.get;
    const fixtureIngest = spec.paths['/v1/machine-execution/bigquery/fixtures/ingest']?.post;
    const liveRun = spec.paths['/v1/machine-execution/bigquery/run-bounded-query']?.post;
    const repeatabilityPack = spec.paths['/v1/machine-execution/repeatability/{service_id}']?.get;
    const machineBenchmarkReadiness = spec.paths['/v1/machine-execution/benchmark-readiness']?.get;
    const machineComparableRoutes = spec.paths['/v1/machine-execution/comparable-routes']?.get;
    const machineBenchmarkMethodology = spec.paths['/v1/machine-execution/benchmark-methodology']?.get;
    const machineBenchmarkGate = spec.paths['/v1/machine-execution/benchmark-gate']?.get;
    const stableuploadFixtureSample = spec.paths['/v1/machine-execution/stableupload/fixtures/tiny-fixture']?.get;
    const stableuploadFixtureIngest = spec.paths['/v1/machine-execution/stableupload/fixtures/ingest']?.post;
    const naverFixtureSample = spec.paths['/v1/machine-execution/naver/fixtures/geocode']?.get;
    const naverFixtureIngest = spec.paths['/v1/machine-execution/naver/fixtures/geocode/ingest']?.post;
    const cloudFixtureSample = spec.paths['/v1/machine-execution/cloud-translation/fixtures/safe-phrase']?.get;
    const cloudFixtureIngest = spec.paths['/v1/machine-execution/cloud-translation/fixtures/safe-phrase/ingest']?.post;

    expect(ingest).toBeTruthy();
    expect(fixtureSample).toBeTruthy();
    expect(fixtureIngest).toBeTruthy();
    expect(liveRun).toBeTruthy();
    expect(repeatabilityPack).toBeTruthy();
    expect(machineBenchmarkReadiness).toBeTruthy();
    expect(machineComparableRoutes).toBeTruthy();
    expect(machineBenchmarkMethodology).toBeTruthy();
    expect(machineBenchmarkGate).toBeTruthy();
    expect(stableuploadFixtureSample).toBeTruthy();
    expect(stableuploadFixtureIngest).toBeTruthy();
    expect(naverFixtureSample).toBeTruthy();
    expect(naverFixtureIngest).toBeTruthy();
    expect(cloudFixtureSample).toBeTruthy();
    expect(cloudFixtureIngest).toBeTruthy();
    expect(spec.components.securitySchemes.bearerAuth).toBeTruthy();
    expect(spec.components.securitySchemes.bearerAuth.type).toBe('http');
    expect(spec.components.securitySchemes.bearerAuth.scheme).toBe('bearer');
    expect(ingest.security).toEqual([{ bearerAuth: [] }]);
    expect(fixtureIngest.security).toEqual([{ bearerAuth: [] }]);
    expect(liveRun.security).toEqual([{ bearerAuth: [] }]);
    expect(stableuploadFixtureIngest.security).toEqual([{ bearerAuth: [] }]);
    expect(naverFixtureIngest.security).toEqual([{ bearerAuth: [] }]);
    expect(cloudFixtureIngest.security).toEqual([{ bearerAuth: [] }]);
    expect(fixtureSample.security).toBeUndefined();
    expect(stableuploadFixtureSample.security).toBeUndefined();
    expect(naverFixtureSample.security).toBeUndefined();
    expect(cloudFixtureSample.security).toBeUndefined();

    expect(String(ingest.description)).toContain('Admin token required');
    expect(JSON.stringify(ingest.responses)).toContain('admin_token_required');
    expect(JSON.stringify(ingest)).toContain('service-specific execution receipt only');
    expect(JSON.stringify(ingest)).toContain('not market-wide proof');
    expect(JSON.stringify(ingest)).toContain('not payment proof unless payment evidence exists');
    expect(JSON.stringify(ingest)).toContain('not benchmark proof');
    expect(JSON.stringify(ingest)).toContain('not winner proof');

    expect(String(fixtureSample.description)).toContain('Fixture-only route');
    expect(String(fixtureSample.description)).toContain('does not execute live BigQuery');
    expect(String(fixtureSample.description)).toContain('does not require translated_text_preview');
    expect(String(fixtureSample.description)).toContain('payment_status remains not_confirmed unless payment evidence exists');
    expect(String(fixtureSample.description)).toContain('bounded public/synthetic query');
    expect(JSON.stringify(fixtureSample)).not.toContain('live BigQuery execution');

    expect(String(fixtureIngest.description)).toContain('Fixture-only ingest path');
    expect(String(fixtureIngest.description)).toContain('Does not execute live BigQuery');
    expect(String(fixtureIngest.description)).toContain('not benchmark proof');
    expect(String(fixtureIngest.description)).toContain('not winner proof');
    expect(JSON.stringify(fixtureIngest.responses)).toContain('admin_token_required');
    expect(String(liveRun.description)).toContain('never falls back to fixture routes');
    expect(String(liveRun.description)).toContain('Admin bearer auth required');
    expect(JSON.stringify(liveRun.responses)).toContain('live_harness_not_configured');
    expect(JSON.stringify(liveRun.responses)).toContain('admin_token_required');
    expect(String(repeatabilityPack.description)).toContain('Route-specific repeatability only');
    expect(String(repeatabilityPack.description)).toContain('not benchmark proof');
    expect(String(repeatabilityPack.description)).toContain('not winner proof');
    expect(String(repeatabilityPack.description)).toContain('not market-wide proof');
    expect(String(repeatabilityPack.description)).toContain('not payment proof unless payment evidence exists');
    expect(String(machineBenchmarkReadiness.description)).toContain('Returns benchmark readiness state only');
    expect(String(machineBenchmarkReadiness.description)).toContain('Does not run benchmarks');
    expect(String(machineBenchmarkReadiness.description)).toContain('or claim winners');
    expect(String(machineComparableRoutes?.description)).toContain('comparable-route discovery and methodology contracts');
    expect(String(machineComparableRoutes?.description)).toContain('Does not run benchmarks');
    expect(String(machineComparableRoutes?.description)).toContain('or claim winners');
    expect(String(machineBenchmarkMethodology?.description)).toContain('methodology schema artifacts only');
    expect(String(machineBenchmarkMethodology?.description)).toContain('not benchmark execution');
    expect(String(machineBenchmarkMethodology?.description)).toContain('not benchmark evidence');
    expect(String(machineBenchmarkMethodology?.description)).toContain('does not claim winners');
    expect(String(machineBenchmarkMethodology?.description)).toContain('does not record benchmark artifacts');
    expect(String(machineBenchmarkGate?.description)).toContain('does not run benchmarks');
    expect(String(machineBenchmarkGate?.description)).toContain('does not create benchmark artifacts');
    expect(String(machineBenchmarkGate?.description)).toContain('does not claim benchmark execution');
    expect(String(machineBenchmarkGate?.description)).toContain('does not claim winners');

    expect(String(stableuploadFixtureSample.description)).toContain('Fixture-only route');
    expect(String(stableuploadFixtureSample.description)).toContain('does not execute live Stableupload');
    expect(String(stableuploadFixtureSample.description)).toContain('tiny non-sensitive upload evidence');
    expect(String(stableuploadFixtureIngest.description)).toContain('Fixture-only ingest path');
    expect(String(stableuploadFixtureIngest.description)).toContain('Does not execute live Stableupload');
    expect(String(stableuploadFixtureIngest.description)).toContain('not benchmark proof');
    expect(String(stableuploadFixtureIngest.description)).toContain('not winner proof');
    expect(JSON.stringify(stableuploadFixtureIngest.responses)).toContain('admin_token_required');

    expect(String(naverFixtureSample.description)).toContain('Fixture-only route');
    expect(String(naverFixtureSample.description)).toContain('does not execute live NAVER Maps');
    expect(String(naverFixtureSample.description)).toContain('non-operational geocode lookup evidence');
    expect(String(naverFixtureIngest.description)).toContain('Fixture-only ingest path');
    expect(String(naverFixtureIngest.description)).toContain('Does not execute live NAVER Maps');
    expect(String(naverFixtureIngest.description)).toContain('no robot command');
    expect(String(naverFixtureIngest.description)).toContain('no physical movement');
    expect(JSON.stringify(naverFixtureIngest.responses)).toContain('admin_token_required');
    expect(String(cloudFixtureSample.description)).toContain('Fixture-only route');
    expect(String(cloudFixtureSample.description)).toContain('does not execute live Cloud Translation');
    expect(String(cloudFixtureSample.description)).toContain('safe phrase translation evidence');
    expect(String(cloudFixtureIngest.description)).toContain('Fixture-only ingest path');
    expect(String(cloudFixtureIngest.description)).toContain('Does not execute live Cloud Translation');
    expect(String(cloudFixtureIngest.description)).toContain('not benchmark proof');
    expect(String(cloudFixtureIngest.description)).toContain('not winner proof');
    expect(JSON.stringify(cloudFixtureIngest.responses)).toContain('admin_token_required');

    await app.close();
  });
});
