import type { LockedInventoryObservation, MissionPair, MissionStockFootprint, TrackedStockInventoryAggregate } from '../services/rhChainReflexiveRadarService';
import type { QuotePersistenceObservation } from '../services/rhChainQuotePersistenceService';

/** Birth cards use immutable pair identity/launch-time fields only. No current metric is baked into a historical card. */
export function renderReflexiveBirthCardSvg(pair: MissionPair, ticker: string, format: 'landscape' | 'portrait' = 'landscape') {
  const width = format === 'landscape' ? 1200 : 1080; const height = format === 'landscape' ? 630 : 1350; const titleSize = format === 'landscape' ? 88 : 110;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="New mission pair ${xml(pair.mission_symbol)} ${xml(ticker)}"><style>text{font-family:IBM Plex Mono,monospace;fill:#edf0eb}.micro{font-size:22px;letter-spacing:3px;fill:#7dfa9b}.title{font-size:${titleSize}px;font-weight:700;letter-spacing:-5px}.meta{font-size:21px;letter-spacing:2px;fill:#a7afa7}.footer{font-size:18px;letter-spacing:2px;fill:#a7afa7}</style><rect width="100%" height="100%" fill="#070908"/><rect width="14" height="100%" fill="#7dfa9b"/><text x="72" y="74" class="micro">NEW MISSION PAIR</text><text x="72" y="${format === 'landscape' ? 230 : 330}" class="title">${xml(pair.mission_symbol)} / ${xml(ticker)}</text><text x="72" y="${format === 'landscape' ? 320 : 470}" class="meta">CRYPTO-NATIVE ${xml(pair.mission_symbol)}</text><text x="72" y="${format === 'landscape' ? 356 : 510}" class="meta">PRICED IN ${xml(ticker)}</text><line x1="72" y1="${height - 120}" x2="${width - 72}" y2="${height - 120}" stroke="#262b27"/><text x="72" y="${height - 72}" class="footer">DETECTED BY INFOPUNKS REFLEXIVE RADAR</text><text x="${width - 72}" y="${height - 72}" text-anchor="end" class="footer">${xml(pair.launched_at)}</text></svg>`;
}
/** Inventory cards point at one immutable accounting observation, never current pool state. */
export function renderReflexiveInventoryCardSvg(pair: MissionPair, observation: LockedInventoryObservation, format: 'landscape' | 'portrait' = 'landscape') {
  const width = format === 'landscape' ? 1200 : 1080; const height = format === 'landscape' ? 630 : 1350; const amount = observation.stock_principal_units ?? 'UNAVAILABLE'; const pct = observation.absorption_pct ? `${observation.absorption_pct}%` : 'UNAVAILABLE';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${xml(pair.mission_symbol)} canonical locked ${xml(observation.stock_symbol)} inventory"><style>text{font-family:IBM Plex Mono,monospace;fill:#edf0eb}.micro{font-size:20px;letter-spacing:3px;fill:#7dfa9b}.title{font-size:${format === 'landscape' ? 68 : 94}px;font-weight:700;letter-spacing:-4px}.amount{font-size:${format === 'landscape' ? 88 : 110}px;font-weight:700}.meta{font-size:19px;letter-spacing:1.5px;fill:#a7afa7}.footer{font-size:17px;letter-spacing:2px;fill:#a7afa7}</style><rect width="100%" height="100%" fill="#070908"/><rect width="14" height="100%" fill="#7dfa9b"/><text x="72" y="74" class="micro">${xml(observation.stock_symbol)} IS BEING USED AS MONEY.</text><text x="72" y="${format === 'landscape' ? 160 : 260}" class="title">${xml(pair.mission_symbol)} / ${xml(observation.stock_symbol)}</text><text x="72" y="${format === 'landscape' ? 270 : 430}" class="amount">${xml(amount)} ${xml(observation.stock_symbol)}</text><text x="72" y="${format === 'landscape' ? 312 : 480}" class="meta">IN THE CANONICAL LOCKED POSITION</text><text x="72" y="${format === 'landscape' ? 385 : 560}" class="meta">${xml(pct)} OF ROBINHOOD ONCHAIN ${xml(observation.stock_symbol)} TOKEN SUPPLY</text><line x1="72" y1="${height - 120}" x2="${width - 72}" y2="${height - 120}" stroke="#262b27"/><text x="72" y="${height - 72}" class="footer">INFOPUNKS // REFLEXIVE RADAR</text><text x="${width - 72}" y="${height - 72}" text-anchor="end" class="footer">BLOCK ${xml(String(observation.observed_block ?? 'UNAVAILABLE'))}</text></svg>`;
}
/** Category card is keyed to an immutable, same-block aggregate observation. */
export function renderReflexiveStockMoneyCardSvg(aggregate: TrackedStockInventoryAggregate, format: 'landscape' | 'portrait' = 'landscape') {
  const width = format === 'landscape' ? 1200 : 1080; const height = format === 'landscape' ? 630 : 1350; const amount = aggregate.raw_stock_token_units ?? 'UNAVAILABLE'; const pct = aggregate.tracked_pair_locked_absorption_pct ? `${aggregate.tracked_pair_locked_absorption_pct}%` : 'UNAVAILABLE';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${xml(aggregate.stock_symbol)} tracked pair locked inventory"><style>text{font-family:IBM Plex Mono,monospace;fill:#edf0eb}.micro{font-size:20px;letter-spacing:3px;fill:#7dfa9b}.title{font-size:${format === 'landscape' ? 68 : 94}px;font-weight:700;letter-spacing:-4px}.amount{font-size:${format === 'landscape' ? 76 : 98}px;font-weight:700}.meta{font-size:19px;letter-spacing:1.5px;fill:#a7afa7}.footer{font-size:17px;letter-spacing:2px;fill:#a7afa7}</style><rect width="100%" height="100%" fill="#070908"/><rect width="14" height="100%" fill="#7dfa9b"/><text x="72" y="74" class="micro">${xml(aggregate.stock_symbol)} IS BEING USED AS MONEY.</text><text x="72" y="${format === 'landscape' ? 165 : 265}" class="title">${aggregate.position_count} VERIFIED PAIR MARKET${aggregate.position_count === 1 ? '' : 'S'}</text><text x="72" y="${format === 'landscape' ? 275 : 440}" class="amount">${xml(amount)} ${xml(aggregate.stock_symbol)}</text><text x="72" y="${format === 'landscape' ? 317 : 490}" class="meta">IN TRACKED CANONICAL LOCKED POSITIONS</text><text x="72" y="${format === 'landscape' ? 390 : 570}" class="meta">${xml(pct)} OF ROBINHOOD ONCHAIN ${xml(aggregate.stock_symbol)} TOKEN SUPPLY</text><line x1="72" y1="${height - 120}" x2="${width - 72}" y2="${height - 120}" stroke="#262b27"/><text x="72" y="${height - 72}" class="footer">INFOPUNKS // REFLEXIVE RADAR</text><text x="${width - 72}" y="${height - 72}" text-anchor="end" class="footer">OBSERVED AT BLOCK ${xml(String(aggregate.reference_block ?? 'UNAVAILABLE'))}</text></svg>`;
}
/** Immutable provider-context observation card. It cannot be rendered without aligned shares. */
export function renderCapitalVsFlowCardSvg(observation: QuotePersistenceObservation, format: 'landscape' | 'portrait' = 'landscape') {
  if (observation.stock_quote_liquidity_share === null || observation.stock_quote_volume_share === null) throw new Error('capital_flow_card_requires_aligned_observation'); const width = format === 'landscape' ? 1200 : 1080; const height = format === 'landscape' ? 630 : 1350; const capital = `${(observation.stock_quote_liquidity_share * 100).toFixed(2)}%`; const flow = `${(observation.stock_quote_volume_share * 100).toFixed(2)}%`;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${xml(observation.mission_symbol)} capital versus flow"><style>text{font-family:IBM Plex Mono,monospace;fill:#edf0eb}.micro{font-size:20px;letter-spacing:3px;fill:#7dfa9b}.title{font-size:${format === 'landscape' ? 68 : 94}px;font-weight:700;letter-spacing:-4px}.amount{font-size:${format === 'landscape' ? 56 : 76}px;font-weight:700}.meta{font-size:19px;letter-spacing:1.5px;fill:#a7afa7}.footer{font-size:17px;letter-spacing:2px;fill:#a7afa7}</style><rect width="100%" height="100%" fill="#070908"/><rect width="14" height="100%" fill="#7dfa9b"/><text x="72" y="74" class="micro">CAPITAL VS FLOW</text><text x="72" y="160" class="title">${xml(observation.mission_symbol)} / NVDA</text><text x="72" y="245" class="amount">NVDA HOLDS THE CAPITAL.</text><text x="72" y="320" class="meta">STOCK-QUOTE LIQUIDITY SHARE ${xml(capital)}</text><text x="72" y="360" class="meta">STOCK-QUOTE VOLUME SHARE ${xml(flow)}</text><text x="72" y="438" class="amount">${xml(observation.quote_regime.replaceAll('_', ' '))}</text><line x1="72" y1="${height - 120}" x2="${width - 72}" y2="${height - 120}" stroke="#262b27"/><text x="72" y="${height - 72}" class="footer">PROVIDER-INDEXED ROLLING 24H · ${xml(observation.methodology_version)}</text><text x="${width - 72}" y="${height - 72}" text-anchor="end" class="footer">${xml(observation.observed_at)}</text></svg>`;
}
/** Available only when its component scopes are explicit; it never calls the footprint backing. */
export function renderMissionFootprintCardSvg(footprint: MissionStockFootprint, format: 'landscape' | 'portrait' = 'landscape') {
  if (footprint.combined_units === null) throw new Error('footprint_card_requires_verified_component'); const width = format === 'landscape' ? 1200 : 1080; const height = format === 'landscape' ? 630 : 1350;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="AI NVDA mission stock footprint"><style>text{font-family:IBM Plex Mono,monospace;fill:#edf0eb}.micro{font-size:20px;letter-spacing:3px;fill:#7dfa9b}.title{font-size:${format === 'landscape' ? 68 : 94}px;font-weight:700;letter-spacing:-4px}.amount{font-size:${format === 'landscape' ? 56 : 76}px;font-weight:700}.meta{font-size:19px;letter-spacing:1.5px;fill:#a7afa7}.footer{font-size:17px;letter-spacing:2px;fill:#a7afa7}</style><rect width="100%" height="100%" fill="#070908"/><rect width="14" height="100%" fill="#7dfa9b"/><text x="72" y="74" class="micro">AI / NVDA · VERIFIED SCOPE</text><text x="72" y="160" class="title">MISSION STOCK FOOTPRINT</text><text x="72" y="245" class="amount">${xml(footprint.combined_units)} NVDA</text><text x="72" y="320" class="meta">LONG POSITIONS ${xml(footprint.lp_launch_position_units ?? 'UNAVAILABLE')} NVDA</text><text x="72" y="360" class="meta">COMMUNITY VAULT ${xml(footprint.vault_units ?? 'UNVERIFIED')} NVDA</text><text x="72" y="400" class="meta">${xml(footprint.scoped_footprint_pct ?? 'UNAVAILABLE')}% OF ROBINHOOD ONCHAIN NVDA</text><line x1="72" y1="${height - 120}" x2="${width - 72}" y2="${height - 120}" stroke="#262b27"/><text x="72" y="${height - 72}" class="footer">NOT BACKING · EXTERNAL LIQUIDITY ${xml(footprint.external_liquidity_included)}</text><text x="${width - 72}" y="${height - 72}" text-anchor="end" class="footer">BLOCK ${xml(String(footprint.observation_block ?? 'UNAVAILABLE'))}</text></svg>`;
}
function xml(value: string) { return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&apos;'); }
