import type { LockedInventoryObservation, MissionPair } from '../services/rhChainReflexiveRadarService';

/** Birth cards use immutable pair identity/launch-time fields only. No current metric is baked into a historical card. */
export function renderReflexiveBirthCardSvg(pair: MissionPair, ticker: string, format: 'landscape' | 'portrait' = 'landscape') {
  const width = format === 'landscape' ? 1200 : 1080; const height = format === 'landscape' ? 630 : 1350; const titleSize = format === 'landscape' ? 88 : 110;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="New mission pair ${xml(pair.mission_symbol)} ${xml(ticker)}"><style>text{font-family:IBM Plex Mono,monospace;fill:#edf0eb}.micro{font-size:22px;letter-spacing:3px;fill:#7dfa9b}.title{font-size:${titleSize}px;font-weight:700;letter-spacing:-5px}.meta{font-size:21px;letter-spacing:2px;fill:#a7afa7}.footer{font-size:18px;letter-spacing:2px;fill:#a7afa7}</style><rect width="100%" height="100%" fill="#070908"/><rect width="14" height="100%" fill="#7dfa9b"/><text x="72" y="74" class="micro">NEW MISSION PAIR</text><text x="72" y="${format === 'landscape' ? 230 : 330}" class="title">${xml(pair.mission_symbol)} / ${xml(ticker)}</text><text x="72" y="${format === 'landscape' ? 320 : 470}" class="meta">CRYPTO-NATIVE ${xml(pair.mission_symbol)}</text><text x="72" y="${format === 'landscape' ? 356 : 510}" class="meta">PRICED IN ${xml(ticker)}</text><line x1="72" y1="${height - 120}" x2="${width - 72}" y2="${height - 120}" stroke="#262b27"/><text x="72" y="${height - 72}" class="footer">DETECTED BY INFOPUNKS REFLEXIVE RADAR</text><text x="${width - 72}" y="${height - 72}" text-anchor="end" class="footer">${xml(pair.launched_at)}</text></svg>`;
}
/** Inventory cards point at one immutable accounting observation, never current pool state. */
export function renderReflexiveInventoryCardSvg(pair: MissionPair, observation: LockedInventoryObservation, format: 'landscape' | 'portrait' = 'landscape') {
  const width = format === 'landscape' ? 1200 : 1080; const height = format === 'landscape' ? 630 : 1350; const amount = observation.stock_principal_units ?? 'UNAVAILABLE'; const pct = observation.absorption_pct ? `${observation.absorption_pct}%` : 'UNAVAILABLE';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${xml(pair.mission_symbol)} canonical locked ${xml(observation.stock_symbol)} inventory"><style>text{font-family:IBM Plex Mono,monospace;fill:#edf0eb}.micro{font-size:20px;letter-spacing:3px;fill:#7dfa9b}.title{font-size:${format === 'landscape' ? 68 : 94}px;font-weight:700;letter-spacing:-4px}.amount{font-size:${format === 'landscape' ? 88 : 110}px;font-weight:700}.meta{font-size:19px;letter-spacing:1.5px;fill:#a7afa7}.footer{font-size:17px;letter-spacing:2px;fill:#a7afa7}</style><rect width="100%" height="100%" fill="#070908"/><rect width="14" height="100%" fill="#7dfa9b"/><text x="72" y="74" class="micro">${xml(observation.stock_symbol)} IS BEING USED AS MONEY.</text><text x="72" y="${format === 'landscape' ? 160 : 260}" class="title">${xml(pair.mission_symbol)} / ${xml(observation.stock_symbol)}</text><text x="72" y="${format === 'landscape' ? 270 : 430}" class="amount">${xml(amount)} ${xml(observation.stock_symbol)}</text><text x="72" y="${format === 'landscape' ? 312 : 480}" class="meta">IN THE CANONICAL LOCKED POSITION</text><text x="72" y="${format === 'landscape' ? 385 : 560}" class="meta">${xml(pct)} OF ROBINHOOD ONCHAIN ${xml(observation.stock_symbol)} TOKEN SUPPLY</text><line x1="72" y1="${height - 120}" x2="${width - 72}" y2="${height - 120}" stroke="#262b27"/><text x="72" y="${height - 72}" class="footer">INFOPUNKS // REFLEXIVE RADAR</text><text x="${width - 72}" y="${height - 72}" text-anchor="end" class="footer">BLOCK ${xml(String(observation.observed_block ?? 'UNAVAILABLE'))}</text></svg>`;
}
function xml(value: string) { return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&apos;'); }
