import React, { useEffect, useState } from 'react';
import type { RhChainDistributionPackPayload, RhChainDistributionPacket } from '../data/rhChain';
import { fetchRhChain, RhChainHero, type RhChainEnvelope, RhChainRouteState, RhChainSuiteNav } from './rhChainUi';

export function RhChainDistributionPackPage() {
  const [envelope, setEnvelope] = useState<RhChainEnvelope<RhChainDistributionPackPayload> | null>(null); const [error, setError] = useState<string | null>(null); const [copied, setCopied] = useState<string | null>(null);
  const load = () => { setError(null); return fetchRhChain<RhChainDistributionPackPayload>('/v1/rh-chain/distribution-pack').then(setEnvelope).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'distribution_pack_unavailable')); };
  useEffect(() => { document.title = 'RH Chain Distribution Pack | Infopunks'; void load(); }, []);
  const pack = envelope?.data ?? null;
  async function copy(packet: RhChainDistributionPacket) { await navigator.clipboard?.writeText(`${packet.copy_text}\n\n${window.location.origin}${packet.link}`); setCopied(packet.id); }
  return <div className="shell narrative-shell rh-chain-shell distribution-shell"><a className="skip-link" href="#distribution-content">Skip to content</a><header className="site-header"><RhChainSuiteNav current="/rh-chain-signal-desk/distribution-pack" /></header><main id="distribution-content" className="narrative-page rh-chain-page distribution-page">{error && <RhChainRouteState state="unavailable" detail={error} onRetry={() => void load()} />}{!pack && !error && <RhChainRouteState state="loading" />}{pack && envelope && <><RhChainHero eyebrow="Public intelligence distribution" title="RH Chain Distribution Pack" copy="Copy the receipt. Keep the caveat." line="Sharp enough to travel. Grounded enough to stay useful." envelope={envelope} doctrine={pack.doctrine} disclaimer={pack.disclaimer} primaryCta={{ href: '#share-packets', label: 'Open share packets' }} secondaryCta={{ href: '/rh-chain-signal-desk/daily-receipts', label: 'Read receipts' }} /><section id="share-packets" className="distribution-section"><div className="rh-chain-section-head"><div><p className="section-kicker">Share packets</p><h2>Public intelligence, ready to copy</h2></div><a className="methodology-trigger" href="/v1/rh-chain/distribution-pack">Pack JSON</a></div><div className="distribution-grid">{pack.packets.map((packet) => <article key={packet.id}><div className="distribution-card-head"><div><p className="section-kicker">{packet.intended_surface}</p><h3>{packet.title}</h3></div><button className="execute compact secondary" onClick={() => void copy(packet)}>{copied === packet.id ? 'Copied' : 'Copy post'}</button></div><pre>{packet.copy_text}</pre><a className="distribution-link" href={packet.link}>{packet.link}</a><p className="distribution-caveat">{packet.risk_disclaimer}</p><p className="panel-caption">Source: {packet.source_artifact} · Updated {packet.last_updated}</p></article>)}</div></section><section className="panel distribution-guardrail"><p className="section-kicker">Distribution guardrail</p><h2>Do not spam. Do not coordinate raids.</h2><p>Share source-linked public intelligence where it is relevant. Do not use these packets for harassment, fake urgency, group pressure, or promotion of a token.</p></section></>}</main></div>;
}
