import React, { useEffect, useState } from 'react';
import { buildRhChainProjectClaimShare, buildRhChainProjectReceiptShare } from '../services/rhChainShareService';
import { RhChainShareControls, RhChainShareSummary } from './rhChainShareControls';
import { fetchRhChain, RhChainRouteState, RhChainSuiteNav } from './rhChainUi';

type ProjectView = { project: { project_id: string; canonical_display_name: string; primary_contract: string; identity_status: string; reviewed_classification_reference: string | null; last_reviewed_at: string | null }; project_submitted_claims: Array<{ claim_id: string; claim_text: string; claim_status: string; confidence: 'low' | 'medium' | 'high' | null }>; infopunks_observations: Array<{ observation_id: string; observation_statement: string; analyst_review_status: string; confidence: string }>; onchain_evidence: Array<{ evidence_id: string; evidence_type: string; evidence_status: string }>; reviewed_classification: string | null; published_verdicts: Array<{ verdict_id: string; verdict_statement: string; confidence: string }>; unknowns: string[]; disputes: string[]; receipts: Array<{ receipt_id: string; verdict: string; integrity_hash: string | null; canonical_url: string }>; freshness: { last_reviewed_at: string | null } };
type Directory = { items: ProjectView[] };

export function RhChainProjectClaimsPage({ mode, projectId, receiptId }: { mode: 'directory' | 'project' | 'claims' | 'receipts' | 'receipt' | 'submit'; projectId?: string; receiptId?: string }) {
  if (mode === 'submit') return <ClaimForm />;
  return <ClaimsReader mode={mode} projectId={projectId} receiptId={receiptId} />;
}
function ClaimsReader({ mode, projectId, receiptId }: Omit<Parameters<typeof RhChainProjectClaimsPage>[0], 'mode'> & { mode: Exclude<Parameters<typeof RhChainProjectClaimsPage>[0]['mode'], 'submit'> }) {
  const [data, setData] = useState<any>(); const [error, setError] = useState<string>();
  const path = mode === 'directory' ? '/v1/rh-chain/projects' : mode === 'receipt' ? `/v1/rh-chain/intelligence-receipts/${encodeURIComponent(receiptId ?? '')}` : `/v1/rh-chain/projects/${encodeURIComponent(projectId ?? '')}`;
  useEffect(() => { void fetchRhChain<any>(path).then((x) => setData(x.data)).catch((e) => setError(e instanceof Error ? e.message : 'unavailable')); }, [path]);
  return <div className="shell narrative-shell rh-chain-shell"><a className="skip-link" href="#project-claims">Skip to project intelligence</a><header className="site-header"><RhChainSuiteNav current="/rh-chain-signal-desk/projects" /></header><main id="project-claims" className="narrative-page rh-chain-page project-claims-page">{error && <RhChainRouteState state="unavailable" detail={error} />}{!data && !error && <RhChainRouteState state="loading" />}{data && (mode === 'directory' ? <Directory data={data as Directory} /> : mode === 'receipt' ? <Receipt receipt={data.receipt} /> : <Project project={data as ProjectView} showClaims={mode === 'claims'} showReceipts={mode === 'receipts'} />)}</main></div>;
}
function Directory({ data }: { data: Directory }) { return <><section className="panel"><p className="section-kicker">RH Chain Signal Desk</p><h1>Project Claims</h1><p>Exact-contract project records. This is a directory, not a leaderboard.</p><a className="execute" href="/rh-chain-signal-desk/projects/claim">Submit a project claim</a></section><section className="project-directory" aria-label="Project directory">{data.items.length ? data.items.map((item) => <article className="panel" key={item.project.project_id}><p className="section-kicker">{item.project.identity_status}</p><h2><a href={`/rh-chain-signal-desk/projects/${item.project.project_id}`}>{item.project.canonical_display_name}</a></h2><code>{item.project.primary_contract}</code><p>{item.published_verdicts[0]?.verdict_statement ?? 'No published Infopunks verdict.'}</p></article>) : <RhChainRouteState state="source_required" detail="No reviewed project records are public yet." />}</section></> }
function Project({ project, showClaims, showReceipts }: { project: ProjectView; showClaims: boolean; showReceipts: boolean }) { const p=project.project; return <><section className="panel"><p className="section-kicker">Project intelligence · {p.identity_status}</p><h1>{p.canonical_display_name}</h1><code>robinhood:{p.primary_contract}</code><p>Last reviewed: {p.last_reviewed_at ?? 'Not reviewed'}</p><p><a href={`/rh-chain-signal-desk/tokens/${p.primary_contract}`}>Open existing token dossier</a> · <a href="/evaluation-request">Request an independent Infopunks evaluation</a></p></section>{!showReceipts && <EvidenceSection title="Project Says" className="project-says" items={project.project_submitted_claims} render={(x) => { const share = buildRhChainProjectClaimShare({ ...x, project_id: p.project_id, project_name: p.canonical_display_name, exact_contract_context: p.primary_contract, effective_period: { start: null, end: null }, canonical_url: `/rh-chain-signal-desk/projects/${p.project_id}`, verdict: x.claim_status.replaceAll('_', ' '), caveat: 'Project-submitted claims and Infopunks conclusions remain separate; inspect the published record before repeating this claim.' }); return <><strong>{x.claim_status}</strong><p>{x.claim_text}</p><small>PROJECT SAYS · confidence {x.confidence ?? 'not assessed'}</small>{share && <RhChainShareControls share={share} />}</>; }} />}{!showReceipts && <EvidenceSection title="Infopunks Observed" className="infopunks-observed" items={project.infopunks_observations} render={(x) => <><strong>{x.analyst_review_status}</strong><p>{x.observation_statement}</p><small>Independent observation · confidence {x.confidence}</small></>} />}{!showClaims && !showReceipts && <EvidenceSection title="On-chain Evidence" className="onchain-evidence" items={project.onchain_evidence} render={(x) => <><strong>{x.evidence_type}</strong><p>{x.evidence_status}</p><small>On-chain evidence only</small></>} />}{!showClaims && !showReceipts && <section className="panel reviewed-classification"><h2>Reviewed Classification</h2><p>{project.reviewed_classification ?? 'No approved classification is attached.'}</p></section>}{!showClaims && <EvidenceSection title="Verdict" className="published-verdict" items={project.published_verdicts} render={(x) => <><strong>{x.confidence} confidence</strong><p>{x.verdict_statement}</p><small>Published Infopunks conclusion</small></>} />}{!showClaims && <section className="panel open-questions"><h2>Open Questions</h2><p>Unknown: {project.unknowns.length} · disputed: {project.disputes.length}</p></section>}{!showClaims && <EvidenceSection title="Immutable Intelligence Receipts" className="intelligence-receipts" items={project.receipts} render={(x) => <><a href={x.canonical_url}>{x.receipt_id}</a><p>{x.verdict}</p><small>{x.integrity_hash}</small></>} />}</> }
function EvidenceSection<T>({ title, className, items, render }: { title: string; className: string; items: T[]; render: (item: T) => React.ReactNode }) { return <section className={`project-evidence-section ${className}`}><h2>{title}</h2>{items.length ? items.map((x, i) => <article className="panel" key={i}>{render(x)}</article>) : <p>No public record in this evidence class.</p>}</section> }
function Receipt({ receipt }: { receipt: any }) { const share = buildRhChainProjectReceiptShare(receipt); return <section className="panel intelligence-receipt-card"><p className="section-kicker">Immutable Intelligence Receipt</p><h1>{receipt.canonical_project_name}</h1><code>{receipt.exact_contract_identity}</code><p><strong>{receipt.verdict}</strong></p><p>Receipt {receipt.receipt_id} · {receipt.integrity_hash}</p><p>Unknowns: {receipt.unknowns?.length ?? 0} · disputes: {receipt.disputes?.length ?? 0}</p><RhChainShareControls share={share} /><RhChainShareSummary share={share} /></section> }
function ClaimForm() { const [status,setStatus]=useState<string>(); const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const response=await fetchRhChain<any>('/v1/rh-chain/projects/claims',{method:'POST',body:JSON.stringify({project_name:f.get('name'),chain:'robinhood',exact_contract:f.get('contract'),contact:f.get('contact'),claim_category:f.get('category'),claim_statement:f.get('claim'),supporting_evidence:String(f.get('evidence')).split('\n').filter(Boolean),disclosure_accepted:f.get('disclosure')==='on',authority_to_submit_confirmed:f.get('authority')==='on',privacy_consent:f.get('privacy')==='on'}),headers:{'Content-Type':'application/json'}});setStatus(`Queued for review: ${response.data.submission_id}. No endorsement, automatic publication, or automatic classification.`)}catch(err){setStatus(err instanceof Error?err.message:'Submission unavailable')}};return <div className="shell narrative-shell rh-chain-shell"><header className="site-header"><RhChainSuiteNav current="/rh-chain-signal-desk/projects/claim" /></header><main className="narrative-page rh-chain-page"><section className="panel"><p className="section-kicker">Project Claim Intake</p><h1>State the claim. Attach the evidence.</h1><p>Submission only creates queued intake. It is not an endorsement and never becomes reviewed truth automatically.</p><form className="project-claim-form" onSubmit={submit}><label>Project name<input name="name" required /></label><label>Exact Robinhood Chain contract<input name="contract" pattern="0x[a-fA-F0-9]{40}" required /></label><label>Contact email or approved contact method<input name="contact" required /></label><label>Claim category<select name="category"><option value="identity">Identity</option><option value="product_live">Product live</option><option value="revenue">Revenue</option><option value="other">Other</option></select></label><label>Claim statement<textarea name="claim" required /></label><label>Supporting HTTPS evidence, one per line<textarea name="evidence" required /></label><label><input type="checkbox" name="disclosure" required /> I accept the disclosure.</label><label><input type="checkbox" name="authority" required /> I have authority to submit.</label><label><input type="checkbox" name="privacy" /> I consent to necessary privacy handling.</label><button className="execute">Queue claim for review</button></form>{status && <p role="status">{status}</p>}<p>Payment may purchase analysis work, never verification, publication, or a favorable conclusion.</p></section></main></div> }
