import React, { useEffect, useState } from 'react';
import { getNarrativeMetadataForPath, NARRATIVE_PUBLIC_HOST } from '../shared/narrativeMetadata';
import { fetchRhChain, RhChainHero, type RhChainEnvelope, RhChainRouteState, RhChainSuiteNav } from './rhChainUi';

type Layer = { layer: string; volume_24h: number | null; percentage: number | null; label: string; caveat: string };
type Structure = {
  title: string; statement: string; market_pulse: { chain_volume_24h: number | null; observed_transaction_count: number | null; tracked_dexes: string[]; tracked_pair_count: number; classified_market_coverage: number | null; unclassified_market_coverage: number | null; observed_at: string; source_notes: string[]; freshness: string; methodology_caveat: string };
  market_composition: Layer[]; layer_leaders: Array<{ layer: string; assets: Array<{ contract: string; ticker: string | null; display_name: string | null; dexscreener_pair: string | null; canonical_pair: { dex: string | null; quote_token: string | null; volume_24h: number | null } | null; classification_confidence: string; classification_source: string; evidence_state: string; caveat: string | null }> }>;
  observed_coverage: { tracked_exact_contracts: number; classified_exact_contracts: number; canonical_pair_only: boolean }; latest_related_receipts: Array<{ receipt_id: string; timestamp: string; summary: string }>;
};
type CrossLayerMarket = { available: boolean; canonical_pair: { pair_address: string | null } | null; dex: string | null; price_usd: number | null; liquidity_usd: number | null; market_cap_usd: number | null; volume: { h24: number | null; h6: number | null; h1: number | null }; transactions: { h24: { buys: number | null; sells: number | null } }; pair_age_days: number | null; active_boosts: number | null; paid_order_context: { types: string[]; statuses: string[] }; snapshot_timestamp: string | null; freshness: string; provider: string; source_url: string | null };
type CrossLayerEntry = { category: string; chain?: string; contract: string; display_name: string | null; ticker?: string | null; dexscreener_pair: string | null; primary_layer: string; secondary_layers: string[]; explanation: string; evidence_state: string; attention_quality_state: string; missing_evidence: string[]; caveat: string | null; classification_confidence?: 'high' | 'medium' | 'low'; classification_evidence_summary?: string[]; classification_version?: number | null; classification_source?: string; effective_at?: string | null; reviewed_at?: string | null; market_data_timestamp?: string | null; freshness?: string; conflict_state?: string; warnings?: string[]; market_data?: CrossLayerMarket };
type CrossLayer = { title: string; integration_enabled?: boolean; headline?: string; observation_window?: { label: string; captured_at: string }; entries: CrossLayerEntry[]; categories: string[]; observed_at: string; captured_at?: string; intersection_count?: number; reviewed_project_count?: number; intersection_counts?: Array<{ category: string; project_count: number }>; tracked_liquidity_by_intersection?: Array<{ category: string; liquidity_usd: number }>; tracked_volume_by_intersection?: Array<{ category: string; volume_h24_usd: number }>; concentration?: { top_three_liquidity_share: number | null; top_three_volume_share: number | null; scope: string }; classification_coverage?: { reviewed_exact_contracts: number; cross_layer_eligible_exact_contracts: number; unknown_exact_contracts: number; percentage: number; bounded_limit: number; complete: boolean }; market_data_coverage?: { eligible_exact_contracts: number; with_persisted_market_data: number; percentage: number; provider_requests_in_path: number }; conflict_count?: number; source_required_count?: number; unknown_count?: number; freshness?: 'fresh' | 'stale' | 'partial' | 'unavailable'; confidence?: 'high' | 'medium' | 'low'; warnings?: string[]; provider_provenance?: { provider: string; chain_id: string; role: string; external_requests_in_path: boolean; snapshot_count: number }; classification_provenance?: { precedence: readonly string[]; curated_reviewed_records: number; durable_approved_records: number; exact_contract_only: boolean }; bounded_universe?: string; methodology_version?: string; caveats?: string[] };
type Attention = { title: string; observations: Array<{ contract: string; boost_amount: number | null; total_boost_amount: number | null; paid_order_types: string[]; observed_at: string; pair_metrics: { dexId: string | null; volume: { h24: number | null }; liquidityUsd: number | null } | null }>; attention_quality: Array<{ contract: string; state: string; score: number | null; caveats: string[] }>; contract_intelligence: Array<{ contract: string; source: string; display_name: string | null; review_status: string; claim_status: string }> };
type AttentionHistory = { contract: string; latest_snapshot_at: string | null; snapshot_count: number; paid_attention_context: { active_boosts: number; paid_order_types: string[]; paid_order_statuses: string[] } | null; state: string; score: number | null; caveats: string[] };
type View = 'main' | 'cross-layer' | 'attention-quality';

const fmt = (value: number | null) => value === null ? 'Source required' : new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 }).format(value);

export function RhChainMarketStructurePage({ view = 'main' }: { view?: View }) {
  const path = view === 'cross-layer' ? '/v1/rh-chain/market-structure/cross-layer' : view === 'attention-quality' ? '/v1/rh-chain/market-structure/attention-quality' : '/v1/rh-chain/market-structure';
  const [envelope, setEnvelope] = useState<RhChainEnvelope<Structure | CrossLayer | Attention> | null>(null);
  const [error, setError] = useState<string | null>(null);
  const load = () => { setError(null); return fetchRhChain<Structure | CrossLayer | Attention>(path).then(setEnvelope).catch((reason: unknown) => setError(view === 'cross-layer' ? 'Cross-Layer Intersections is temporarily unavailable. Reviewed memory has not been replaced.' : reason instanceof Error ? reason.message : 'market_structure_unavailable')); };
  useEffect(() => { if (view === 'cross-layer') syncCrossLayerMetadata(); else document.title = view === 'main' ? '4663 Market Structure | Infopunks' : 'Paid Attention Watch | Infopunks'; void load(); }, [path]);
  const data = envelope?.data;
  return <div className="shell narrative-shell rh-chain-shell market-structure-shell"><a className="skip-link" href="#market-structure-content">Skip to market structure</a><header className="site-header"><RhChainSuiteNav current="/rh-chain-signal-desk/market-structure" /></header><main id="market-structure-content" className="narrative-page rh-chain-page market-structure-page">
    {error && <RhChainRouteState state="unavailable" detail={error} onRetry={() => void load()} />}
    {!data && !error && (view === 'cross-layer' ? <CrossLayerSkeleton /> : <RhChainRouteState state="loading" />)}
    {data && envelope && <>{view === 'main' && <StructureView payload={data as Structure} envelope={envelope as RhChainEnvelope<Structure>} />}{view === 'cross-layer' && <CrossLayerView payload={data as CrossLayer} envelope={envelope as RhChainEnvelope<CrossLayer>} />}{view === 'attention-quality' && <AttentionView payload={data as Attention} envelope={envelope as RhChainEnvelope<Attention>} />}</>}
  </main></div>;
}

function StructureView({ payload, envelope }: { payload: Structure; envelope: RhChainEnvelope<Structure> }) { return <>
  <RhChainHero eyebrow="RH Chain Signal Desk" title="4663 Market Structure" copy={payload.statement} line="Exact contract. Canonical pair. Reviewed judgment." envelope={envelope} doctrine="Provider data is context only. Infopunks classifications are review-gated." disclaimer="No trading, launch, or endorsement flow. Provider observations never alter reviewed classifications." primaryCta={{ href: '#market-composition', label: 'Read composition' }} secondaryCta={{ href: '/rh-chain-signal-desk/market-structure/attention-quality', label: 'Open attention watch' }} />
  <section id="market-composition" className="meme-pulse-section"><Head kicker="Market composition" title="Observed coverage, not a complete market claim" /><div className="meme-pulse-snapshot-grid">{[['Chain volume (24h)', fmt(payload.market_pulse.chain_volume_24h)], ['Observed transactions', fmt(payload.market_pulse.observed_transaction_count)], ['Tracked canonical pairs', String(payload.market_pulse.tracked_pair_count)], ['Classified coverage', payload.market_pulse.classified_market_coverage === null ? 'Source required' : `${payload.market_pulse.classified_market_coverage}%`]].map(([label, value]) => <article className="meme-pulse-snapshot" key={label}><p>{label}</p><strong>{value}</strong></article>)}</div><p className="rh-chain-disclaimer">{payload.market_pulse.methodology_caveat}</p></section>
  <section className="meme-pulse-section"><Head kicker="Layer leaders" title="Canonical pair context" action="/v1/rh-chain/market-structure" /><div className="meme-pulse-assets">{payload.layer_leaders.map((group) => <article className="meme-pulse-asset" key={group.layer}><p className="section-kicker">{group.layer}</p><h3>{group.assets.length ? `${group.assets.length} observed assets` : 'No reviewed coverage'}</h3>{group.assets.map((asset) => <p key={asset.contract}>{asset.display_name && <><strong>{asset.display_name}</strong> · </>}<code>{asset.contract}</code> · {asset.canonical_pair?.dex ?? (asset.dexscreener_pair ? 'Reviewed pair link' : 'Pair source required')} · {fmt(asset.canonical_pair?.volume_24h ?? null)} 24h volume · {asset.dexscreener_pair && <a href={asset.dexscreener_pair} target="_blank" rel="noreferrer">DexScreener pair</a>} · <span className="meme-pulse-risk risk-source_required">{asset.classification_source === 'manual_review' ? 'reviewed intake' : 'auto-observed'} · {asset.evidence_state} · {asset.classification_confidence}</span>{asset.caveat && <> · <small>{asset.caveat}</small></>}</p>)}</article>)}</div></section>
  <section className="meme-pulse-section"><Head kicker="Cross-layer assets" title="More than one structural layer" /><p><a className="execute compact secondary" href="/rh-chain-signal-desk/market-structure/cross-layer">Open exact-contract cross-layer record</a></p></section>
  <section className="meme-pulse-section"><Head kicker="Paid Attention Watch" title="Visibility is context, not conviction" /><p><a className="execute compact secondary" href="/rh-chain-signal-desk/market-structure/attention-quality">Inspect documented boost and order observations</a></p></section>
  <section className="meme-pulse-section"><Head kicker="Methodology and coverage" title="Source policy" /><p>Tracked DEXes: {payload.market_pulse.tracked_dexes.join(', ') || 'Source required'} · observed {payload.market_pulse.observed_at} · freshness: {payload.market_pulse.freshness}.</p>{payload.market_pulse.source_notes.map((note) => <p className="rh-chain-disclaimer" key={note}>{note}</p>)}</section>
  <section className="meme-pulse-section"><Head kicker="Latest related receipts" title="Memory before momentum" />{payload.latest_related_receipts.length ? payload.latest_related_receipts.map((receipt) => <article className="meme-pulse-asset" key={receipt.receipt_id}><h3>{receipt.receipt_id}</h3><p>{receipt.summary}</p><small>{receipt.timestamp}</small></article>) : <RhChainRouteState state="source_required" detail="No related reviewed receipt is available for this market view." />}</section>
</>; }
function CrossLayerView({ payload, envelope }: { payload: CrossLayer; envelope: RhChainEnvelope<CrossLayer> }) {
  if (payload.integration_enabled !== true) return <LegacyCrossLayerView payload={payload} envelope={envelope} />;
  return <IntegratedCrossLayerView payload={payload} />;
}

function LegacyCrossLayerView({ payload, envelope }: { payload: CrossLayer; envelope: RhChainEnvelope<CrossLayer> }) { return <><RhChainHero eyebrow="4663 Market Structure" title="Cross-Layer Assets" copy="Structural overlap is review-gated and exact-contract only." envelope={envelope} disclaimer="Provider observations cannot create a cross-layer classification." primaryCta={{ href: '#cross-layer-assets', label: 'Read entries' }} secondaryCta={{ href: '/rh-chain-signal-desk/market-structure', label: 'Market structure' }} /><section id="cross-layer-assets" className="meme-pulse-section"><Head kicker="Cross-layer assets" title="Reviewed intersections" />{payload.entries.length ? <div className="meme-pulse-assets">{payload.entries.map((entry) => <article className="meme-pulse-asset" key={entry.contract}><p className="section-kicker">{crossLayerLabel(entry.category)}</p><h3>{entry.display_name ?? <code>{entry.contract}</code>}</h3><p><code>{entry.contract}</code>{entry.dexscreener_pair && <> · <a href={entry.dexscreener_pair} target="_blank" rel="noreferrer">DexScreener pair</a></>}</p><p>{entry.primary_layer} · {entry.secondary_layers.join(' · ')}</p><p>{entry.explanation}</p><p>Attention quality: {entry.attention_quality_state} · Evidence: {entry.evidence_state}</p>{entry.caveat && <p className="rh-chain-disclaimer">{entry.caveat}</p>}{entry.missing_evidence.map((item) => <small key={item}>{item}</small>)}</article>)}</div> : <RhChainRouteState state="source_required" detail="No exact-contract reviewed cross-layer classifications are available." />}</section></>; }

function IntegratedCrossLayerView({ payload }: { payload: CrossLayer }) {
  const [actionState, setActionState] = useState<'idle' | 'copied' | 'shared'>('idle');
  const capturedAt = payload.captured_at ?? payload.observed_at;
  const insight = `${payload.headline ?? 'Reviewed intersections are waiting for enough evidence.'} ${payload.reviewed_project_count ?? payload.entries.length} eligible exact-contract project${(payload.reviewed_project_count ?? payload.entries.length) === 1 ? '' : 's'} in the bounded set. — ${formatCrossLayerTime(capturedAt)} · Infopunks Radar`;
  const highConfidence = payload.entries.filter((entry) => entry.classification_confidence === 'high' && entry.conflict_state !== 'curated_durable_disagreement');
  const emerging = payload.entries.filter((entry) => !highConfidence.includes(entry));
  async function copyInsight() { if (await copyCrossLayerText(insight)) setActionState('copied'); }
  async function shareInsight() {
    if (navigator.share) {
      try { await navigator.share({ title: payload.title, text: insight, url: CROSS_LAYER_CANONICAL_URL }); setActionState('shared'); return; } catch { /* Cancelled native sharing leaves the page unchanged. */ }
    }
    await copyInsight();
  }

  return <>
    <section className="cross-layer-hero" aria-labelledby="cross-layer-title" data-social-card="cross-layer">
      <div className="cross-layer-hero-top"><p className="section-kicker">Infopunks Radar · Robinhood Chain</p><span className={`cross-layer-freshness state-${payload.freshness ?? 'unavailable'}`}>{humanizeCrossLayer(payload.freshness ?? 'unavailable')} · {payload.confidence ?? 'low'} confidence</span></div>
      <div className="cross-layer-hero-copy"><p className="cross-layer-product-name">Cross-Layer Intersections</p><h1 id="cross-layer-title">{payload.headline}</h1><p>Reviewed exact-contract evidence defines the intersection. Persisted market memory shows whether liquidity follows.</p></div>
      <div className="cross-layer-meta" aria-label="Observation details"><span>{payload.observation_window?.label ?? 'Latest reviewed observation'}</span><span>Captured {formatCrossLayerTime(capturedAt)}</span><span>{payload.reviewed_project_count ?? payload.entries.length} reviewed intersections</span></div>
      <div className="cross-layer-actions" role="group" aria-label="Share Cross-Layer insight"><button type="button" className="execute compact" onClick={() => void shareInsight()} aria-label="Share Cross-Layer insight">Share insight</button><button type="button" className="execute compact secondary" onClick={() => void copyInsight()} aria-label="Copy Cross-Layer insight">{actionState === 'copied' ? 'Insight copied' : 'Copy insight'}</button><a className="execute compact secondary" href="/rh-chain-signal-desk/market-structure">Market Structure</a></div>
      <p className="cross-layer-action-status" aria-live="polite">{actionState === 'shared' ? 'Share sheet opened.' : actionState === 'copied' ? 'Insight copied to clipboard.' : ''}</p>
    </section>

    {(payload.freshness !== 'fresh' || (payload.warnings?.length ?? 0) > 0) && <section className={`cross-layer-data-state state-${payload.freshness ?? 'unavailable'}`} role="status" aria-label="Cross-Layer data quality"><strong>{crossLayerStateTitle(payload.freshness)}</strong><span>{payload.warnings?.[0] ?? 'Review source and freshness detail before relying on this observation.'}</span></section>}

    <nav className="cross-layer-nav" aria-label="Intersection categories">{(payload.intersection_counts ?? []).filter((item) => item.project_count > 0).map((item) => { const first = payload.entries.find((entry) => entry.category === item.category); return <a key={item.category} href={first ? `#${crossLayerEntryAnchor(first)}` : '#high-confidence-intersections'}>{crossLayerLabel(item.category)} <span>{item.project_count}</span></a>; })}</nav>

    <section className="cross-layer-overview" aria-labelledby="cross-layer-overview-title"><div><p className="section-kicker">Bounded market structure</p><h2 id="cross-layer-overview-title">Proof before pattern</h2><p>{payload.bounded_universe}</p></div><dl><div><dt>Classification coverage</dt><dd>{formatCrossLayerPercent(payload.classification_coverage?.percentage)}</dd><small>{payload.classification_coverage?.cross_layer_eligible_exact_contracts ?? 0} of {payload.classification_coverage?.reviewed_exact_contracts ?? 0} reviewed exact contracts · {payload.unknown_count ?? 0} remain unknown</small></div><div><dt>Market-data coverage</dt><dd>{formatCrossLayerPercent(payload.market_data_coverage?.percentage)}</dd><small>Persisted snapshots only · zero provider requests</small></div><div><dt>Unresolved conflicts</dt><dd>{payload.conflict_count ?? 0}</dd><small>Curated memory remains in force</small></div><div><dt>Evidence incomplete</dt><dd>{payload.source_required_count ?? 0}</dd><small>Kept outside the public list</small></div></dl></section>

    <CrossLayerProjectSection id="high-confidence-intersections" kicker="High confidence" title="Reviewed intersections with the clearest evidence" entries={highConfidence} empty="No high-confidence intersection currently meets every public evidence condition." />
    <CrossLayerProjectSection id="emerging-intersections" kicker="Emerging" title="Reviewed overlap with visible limits" entries={emerging} empty="No emerging reviewed intersection is currently public." />

    <aside className="cross-layer-social-card" aria-label="Compact Cross-Layer social card"><p>Infopunks / Cross-Layer Intersections</p><strong>{payload.headline}</strong><span>{payload.observation_window?.label} · {formatCrossLayerTime(capturedAt)} · exact-contract reviewed memory</span></aside>

    <details className="cross-layer-methodology"><summary>Classification precedence, sources, and methodology</summary><div><ol>{(payload.classification_provenance?.precedence ?? []).map((source, index) => <li key={source}><strong>{index + 1}.</strong> {humanizeCrossLayer(source)}</li>)}</ol><dl><div><dt>Identity</dt><dd>Exact Robinhood Chain contract only</dd></div><div><dt>Classifier</dt><dd>{payload.methodology_version ?? 'cross_layer_intersections_v1'}</dd></div><div><dt>Market provider</dt><dd>{payload.provider_provenance?.provider ?? 'DEX Screener'} · persisted context only</dd></div><div><dt>Canonical URL</dt><dd><a href={CROSS_LAYER_CANONICAL_PATH}>{CROSS_LAYER_CANONICAL_URL}</a></dd></div></dl>{payload.caveats?.map((caveat) => <p key={caveat}>{caveat}</p>)}{(payload.warnings?.length ?? 0) > 0 && <ul>{payload.warnings?.map((warning) => <li key={warning}>{warning}</li>)}</ul>}<p><a href="/v1/rh-chain/market-structure/cross-layer">Open Cross-Layer JSON</a> · <a href="/rh-chain-signal-desk/market">Open Market Pulse</a> · <a href="/rh-chain-signal-desk/live-snapshot">Open Live Snapshot</a></p></div></details>
  </>;
}

function CrossLayerProjectSection({ id, kicker, title, entries, empty }: { id: string; kicker: string; title: string; entries: CrossLayerEntry[]; empty: string }) { return <section id={id} className="cross-layer-section" aria-labelledby={`${id}-title`}><div className="cross-layer-section-head"><div><p className="section-kicker">{kicker}</p><h2 id={`${id}-title`}>{title}</h2></div><p>Every public card requires reviewed layer evidence. Missing market data remains visible rather than inferred.</p></div>{entries.length ? <div className="cross-layer-projects">{entries.map((entry) => <CrossLayerProjectCard key={entry.contract} entry={entry} />)}</div> : <div className="cross-layer-empty"><strong>Nothing published here yet.</strong><p>{empty}</p></div>}</section>; }

function CrossLayerProjectCard({ entry }: { entry: CrossLayerEntry }) { const market = entry.market_data; return <article id={crossLayerEntryAnchor(entry)} className="cross-layer-project-card"><header><div><p className="section-kicker">{crossLayerLabel(entry.category)}</p><h3>{entry.display_name ?? entry.ticker ?? 'Reviewed exact contract'}</h3></div><span className={`cross-layer-confidence confidence-${entry.classification_confidence ?? 'low'}`}>{entry.classification_confidence ?? 'reviewed'}</span></header><code>{entry.chain ?? 'robinhood'}:{entry.contract}</code><p className="cross-layer-layers"><strong>{humanizeCrossLayer(entry.primary_layer)}</strong>{entry.secondary_layers.map((layer) => <span key={layer}>{humanizeCrossLayer(layer)}{layer === 'ai-narrative' ? ' · activity unverified' : ''}</span>)}</p><p className="cross-layer-explanation">{entry.explanation}</p><div className="cross-layer-evidence"><h4>Classification evidence</h4>{entry.classification_evidence_summary?.length ? <ul>{entry.classification_evidence_summary.map((evidence) => <li key={evidence}>{evidence}</li>)}</ul> : <p>Evidence summary is unavailable; the reviewed classification remains the source of authority.</p>}<small>{humanizeCrossLayer(entry.classification_source ?? 'reviewed_memory')} · version {entry.classification_version ?? 'curated'} · reviewed {formatCrossLayerTime(entry.reviewed_at)}</small></div>{entry.conflict_state === 'curated_durable_disagreement' && <p className="cross-layer-conflict" role="status"><strong>Classification conflict</strong> Curated memory remains authoritative while reviewers resolve the durable disagreement.</p>}<div className="cross-layer-market"><h4>Persisted market context</h4>{market?.available ? <dl><div><dt>Liquidity</dt><dd>{formatCrossLayerMoney(market.liquidity_usd)}</dd></div><div><dt>24h volume</dt><dd>{formatCrossLayerMoney(market.volume.h24)}</dd></div><div><dt>Market cap</dt><dd>{formatCrossLayerMoney(market.market_cap_usd)}</dd></div><div><dt>DEX</dt><dd>{market.dex ?? 'Unavailable'}</dd></div></dl> : <p className="cross-layer-unavailable"><strong>Market data unavailable.</strong> The reviewed classification is shown without inferred price, liquidity, or activity.</p>}<small>{market?.available ? `${humanizeCrossLayer(market.freshness)} · snapshot ${formatCrossLayerTime(market.snapshot_timestamp)}` : 'Reviewed evidence available · market enrichment unavailable'}</small></div>{(entry.warnings?.length ?? 0) > 0 && <details><summary>{entry.warnings?.length} data warning{entry.warnings?.length === 1 ? '' : 's'}</summary><ul>{entry.warnings?.map((warning) => <li key={warning}>{warning}</li>)}</ul></details>}</article>; }

function CrossLayerSkeleton() { return <section className="cross-layer-skeleton" role="status" aria-live="polite" aria-busy="true"><span className="sr-only">Loading Robinhood Chain Cross-Layer Intersections</span><div className="cross-layer-skeleton-line short" aria-hidden="true"/><div className="cross-layer-skeleton-line headline" aria-hidden="true"/><div className="cross-layer-skeleton-line medium" aria-hidden="true"/><div className="cross-layer-skeleton-grid" aria-hidden="true">{Array.from({ length: 4 }, (_, index) => <span key={index}/>)}</div></section>; }
function AttentionView({ payload, envelope }: { payload: Attention; envelope: RhChainEnvelope<Attention> }) {
  const [history, setHistory] = useState<Record<string, AttentionHistory>>({});
  useEffect(() => { void Promise.all(payload.observations.map((item) => fetchRhChain<AttentionHistory>(`/v1/rh-chain/market/attention-quality/${encodeURIComponent(item.contract)}`).then((response) => [item.contract, response.data] as const).catch(() => null))).then((results) => setHistory(Object.fromEntries(results.filter((result): result is readonly [string, AttentionHistory] => Boolean(result))))); }, [payload.observations]);
  return <><RhChainHero eyebrow="4663 Market Structure" title="Paid Attention Watch" copy="Paid visibility is observed without being mistaken for organic conviction." envelope={envelope} disclaimer="A paid boost is not misconduct. A boost rank is not organic demand." primaryCta={{ href: '#paid-attention', label: 'Read observations' }} secondaryCta={{ href: '/rh-chain-signal-desk/market-structure', label: 'Market structure' }} /><section id="paid-attention" className="meme-pulse-section"><Head kicker="Documented API observations" title="Boosts, orders, pair context" />{payload.observations.length ? <div className="meme-pulse-assets">{payload.observations.map((item) => { const intelligence = payload.contract_intelligence.find((entry) => entry.contract.toLowerCase() === item.contract.toLowerCase()); return <article className="meme-pulse-asset" key={item.contract}><h3>{intelligence?.display_name ?? <code>{item.contract}</code>}</h3><p><code>{item.contract}</code> · {intelligence?.source ?? 'unknown'} · {intelligence?.review_status ?? 'not reviewed'}</p><p>Boost: {fmt(item.boost_amount)} · Total boost: {fmt(item.total_boost_amount)}</p><p>Paid order types: {item.paid_order_types.join(', ') || 'None observed'}</p><p>Canonical pair: {item.pair_metrics?.dexId ?? 'Source required'} · volume {fmt(item.pair_metrics?.volume.h24 ?? null)} · liquidity {fmt(item.pair_metrics?.liquidityUsd ?? null)}</p><small>{item.observed_at}</small></article>; })}</div> : <RhChainRouteState state="source_required" detail="No current paid-attention observation is available from the public API." />}</section><section className="meme-pulse-section"><Head kicker="Attention quality" title="History-gated, never inferred" />{payload.observations.map((item) => <AttentionHistoryCard key={item.contract} fallback={payload.attention_quality.find((quality) => quality.contract === item.contract)} history={history[item.contract]} contract={item.contract} />)}</section></>;
}
function AttentionHistoryCard({ contract, history, fallback }: { contract: string; history?: AttentionHistory; fallback?: Attention['attention_quality'][number] }) { const value = history ?? fallback; return <article className="meme-pulse-asset"><h3><code>{contract}</code></h3><p>Latest snapshot: {history?.latest_snapshot_at ?? 'Source required'} · snapshots: {history?.snapshot_count ?? 0}</p><p>State: {value?.state ?? 'source_required'} · score {value?.score ?? 'Insufficient history'}</p>{history?.paid_attention_context && <p>Paid attention context: {history.paid_attention_context.active_boosts} active boosts · {history.paid_attention_context.paid_order_types.join(', ') || 'no paid order type observed'}</p>}{value?.caveats.map((caveat) => <small key={caveat}>{caveat}</small>)}</article>; }
function Head({ kicker, title, action }: { kicker: string; title: string; action?: string }) { return <div className="rh-chain-section-head"><div><p className="section-kicker">{kicker}</p><h2>{title}</h2></div>{action && <a className="methodology-trigger" href={action}>JSON</a>}</div>; }
const CROSS_LAYER_CANONICAL_PATH = '/rh-chain-signal-desk/market-structure/cross-layer';
const CROSS_LAYER_CANONICAL_URL = `${NARRATIVE_PUBLIC_HOST}${CROSS_LAYER_CANONICAL_PATH}`;
function crossLayerLabel(category: string) { return category === 'defi_x_rwa' ? 'DeFi × RWA' : category === 'agent_x_meme' ? 'Meme × Agent' : category === 'rwa_x_lending' ? 'RWA × Lending' : category === 'consumer_x_tokenized_finance' ? 'Consumer × Tokenized Finance' : category === 'meme_x_ai_narrative' ? 'Meme × AI Narrative (agent activity unverified)' : category.split('_x_').map(humanizeCrossLayer).join(' × '); }
function crossLayerEntryAnchor(entry: Pick<CrossLayerEntry, 'category' | 'contract'>) { return `intersection-${entry.category}-${entry.contract.replace(/[^a-zA-Z0-9]/g, '').slice(0, 12).toLowerCase()}`; }
function humanizeCrossLayer(value: string) { return value.replaceAll('_', ' ').replaceAll('-', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function formatCrossLayerPercent(value: number | null | undefined) { return typeof value === 'number' ? `${value.toFixed(1)}%` : 'Unavailable'; }
function formatCrossLayerMoney(value: number | null | undefined) { return typeof value === 'number' ? new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: value >= 1_000_000 ? 'compact' : 'standard', maximumFractionDigits: value >= 1_000 ? 0 : 2 }).format(value) : 'Unavailable'; }
function formatCrossLayerTime(value: string | null | undefined) { if (!value) return 'Timestamp unavailable'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Timestamp unavailable' : `${new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' }).format(date).replace(' at ', ' · ')} UTC`; }
function crossLayerStateTitle(freshness: CrossLayer['freshness']) { return freshness === 'stale' ? 'Persisted market context is stale.' : freshness === 'partial' ? 'Some reviewed intersections lack current market context.' : freshness === 'unavailable' ? 'Market context is unavailable; reviewed classifications remain visible.' : 'Review the data quality note.'; }
async function copyCrossLayerText(value: string) { if (!value) return false; try { await navigator.clipboard?.writeText(value); return Boolean(navigator.clipboard); } catch { return false; } }
function syncCrossLayerMetadata() {
  const metadata = getNarrativeMetadataForPath(CROSS_LAYER_CANONICAL_PATH);
  const title = metadata?.title ?? 'Cross-Layer Intersections | Infopunks Radar';
  const description = metadata?.description ?? 'Reviewed exact-contract intersections with persisted market evidence.';
  document.title = title;
  for (const [attribute, name, content] of [['name', 'description', description], ['property', 'og:title', title], ['property', 'og:description', description], ['property', 'og:url', CROSS_LAYER_CANONICAL_URL], ['name', 'twitter:card', metadata?.twitterCard ?? 'summary'], ['name', 'twitter:title', title], ['name', 'twitter:description', description]] as const) setCrossLayerMeta(attribute, name, content);
  if (metadata?.ogImageUrl) { setCrossLayerMeta('property', 'og:image', metadata.ogImageUrl); setCrossLayerMeta('name', 'twitter:image', metadata.ogImageUrl); }
  let canonical = document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]');
  if (!canonical) { canonical = document.createElement('link'); canonical.rel = 'canonical'; document.head.appendChild(canonical); }
  canonical.href = CROSS_LAYER_CANONICAL_URL;
}
function setCrossLayerMeta(attribute: 'name' | 'property', name: string, content: string) { let tag = document.head.querySelector<HTMLMetaElement>(`meta[${attribute}="${name}"]`); if (!tag) { tag = document.createElement('meta'); tag.setAttribute(attribute, name); document.head.appendChild(tag); } tag.content = content; }
