import React, { useEffect, useState } from 'react';
import type { RhChainDistributionPackPayload, RhChainDistributionPacket } from '../data/rhChain';
import { getApiBaseUrl, toApiUrl } from './apiBaseUrl';
const API_BASE_URL = getApiBaseUrl();

export function RhChainDistributionPackPage() {
  const [pack, setPack] = useState<RhChainDistributionPackPayload | null>(null); const [error, setError] = useState<string | null>(null); const [copied, setCopied] = useState<string | null>(null);
  useEffect(() => { document.title = 'RH Chain Distribution Pack | Infopunks'; fetch(toApiUrl(API_BASE_URL, '/v1/rh-chain/distribution-pack'), { headers: { Accept: 'application/json' } }).then(async (response) => { if (!response.ok) throw new Error(`distribution_pack ${response.status}`); return response.json() as Promise<{ data: RhChainDistributionPackPayload }>; }).then(({ data }) => setPack(data)).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'distribution_pack_unavailable')); }, []);
  async function copy(packet: RhChainDistributionPacket) { await navigator.clipboard?.writeText(`${packet.copy_text}\n\n${window.location.origin}${packet.link}`); setCopied(packet.id); }
  return <div className="shell narrative-shell rh-chain-shell distribution-shell"><a className="skip-link" href="#distribution-content">Skip to content</a><header className="site-header"><nav className="global-toolbar narrative-toolbar" aria-label="RH Chain navigation"><a className="nav-brand" href="/"><span>Infopunks</span><strong>RH Chain</strong></a><div className="terminal-nav terminal-nav-scroll-rail"><a href="/rh-chain-signal-desk">Signal Desk</a><a href="/rh-chain-signal-desk/meme-pulse">Meme Pulse</a><a href="/rh-chain-signal-desk/daily-receipts">Daily Receipts</a><a className="active" aria-current="page" href="/rh-chain-signal-desk/distribution-pack">Distribution Pack</a></div></nav></header><main id="distribution-content" className="narrative-page rh-chain-page distribution-page">{error && <section className="panel"><p className="route-state error">{error}</p></section>}{!pack && !error && <section className="panel"><p className="route-state">Packing public intelligence…</p></section>}{pack && <><section className="panel hero rh-chain-hero distribution-hero"><div><p className="eyebrow">Public intelligence distribution</p><h1>RH Chain Distribution Pack</h1><p className="copy">Copy the receipt. Keep the caveat.</p><p className="distribution-line">Sharp enough to travel. Grounded enough to stay useful.</p></div><aside className="rh-chain-hero-rail"><p className="section-kicker">Distribution doctrine</p><p>{pack.doctrine}</p><p className="rh-chain-disclaimer">{pack.disclaimer}</p></aside></section><section className="distribution-section"><div className="rh-chain-section-head"><div><p className="section-kicker">Share packets</p><h2>Public intelligence, ready to copy</h2></div><a className="methodology-trigger" href="/v1/rh-chain/distribution-pack">Pack JSON</a></div><div className="distribution-grid">{pack.packets.map((packet) => <article key={packet.id}><div className="distribution-card-head"><div><p className="section-kicker">{packet.intended_surface}</p><h3>{packet.title}</h3></div><button className="execute compact secondary" onClick={() => void copy(packet)}>{copied === packet.id ? 'Copied' : 'Copy post'}</button></div><pre>{packet.copy_text}</pre><a className="distribution-link" href={packet.link}>{packet.link}</a><p className="distribution-caveat">{packet.risk_disclaimer}</p><p className="panel-caption">Source: {packet.source_artifact} · Updated {packet.last_updated}</p></article>)}</div></section><section className="panel distribution-guardrail"><p className="section-kicker">Distribution guardrail</p><h2>Do not spam. Do not coordinate raids.</h2><p>Share source-linked public intelligence where it is relevant. Do not use these packets for harassment, fake urgency, group pressure, or promotion of a token.</p></section></>}</main></div>;
}
