import React, { useEffect, useState } from 'react';
import './rhChainReflexiveRadar.css';

type Asset = { asset_id: string; ticker: string; name: string; canonical_contract: string; current_multiplier: string; status: string; pending_multiplier: string | null; pending_multiplier_effective_at: string | null; logo: string | null };
type Pair = { pair_id: string; mission_symbol: string; venue: string; launched_at: string; canonicality: string; quote_contract: string; stock_asset_id: string; first_party_asset: boolean; evidence: Array<{ href: string; source: string; observed_at: string; note: string }> };
type Observation = { pair_id: string; observed_at: string; mission_usd_price: number | null; stock_dex_usd_price: number | null; underlying_usd_price: number | null; liquidity_usd: number | null; volume_24h_usd: number | null; quote_inventory_share_equivalent: string | null; inventory_method: string; fresh: boolean; provenance: Array<{ href: string; source: string; note: string }> };
type Inventory = { status: 'AVAILABLE' | 'UNAVAILABLE'; reason: string | null; stock_principal_units: string | null; stock_share_equivalent_units: string | null; stock_total_supply_units: string | null; absorption_pct: string | null; range_state: string | null; observed_block: number | null; observed_at: string; method: string };
type Snapshot = { assets: Asset[]; pairs: Pair[]; observations: Observation[]; events: Array<{ event_id: string; event_type: string; occurred_at: string; trigger: string }>; thesis: Array<{ hypothesis_id: string; state: string; rationale: string; evidence_ids: string[] }>; refreshed_at: string };

async function api<T>(path: string): Promise<T> { const response = await fetch(path); const body = await response.json() as { data?: T; error?: string }; if (!response.ok || !body.data) throw new Error(body.error ?? 'reflexive_data_unavailable'); return body.data; }
const money = (value: number | null | undefined) => value == null ? 'UNAVAILABLE' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2, notation: 'compact' }).format(value);
const time = (value: string) => new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });

export function ReflexiveRadarPage() {
  const path = window.location.pathname; const pairId = path.match(/^\/4663\/reflexive\/pair\/([^/]+)/)?.[1]; const stockSymbol = path.match(/^\/4663\/reflexive\/stock\/([^/]+)/)?.[1];
  if (pairId) return <PairDossier pairId={decodeURIComponent(pairId)} />;
  if (stockSymbol) return <StockDossier symbol={decodeURIComponent(stockSymbol)} />;
  return <Home />;
}

function useResource<T>(url: string) { const [data, setData] = useState<T | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { let live = true; void api<T>(url).then((value) => live && setData(value), (reason: unknown) => live && setError(reason instanceof Error ? reason.message : 'unavailable')); return () => { live = false; }; }, [url]); return { data, error }; }
function Shell({ children }: { children: React.ReactNode }) { return <div className="reflexive-shell"><header><a href="/4663" className="reflexive-mark">INFOPUNKS <i>//4663</i></a><nav><a href="/4663/reflexive">REFLEXIVE RADAR</a><a href="/v1/4663/reflexive">API</a></nav></header>{children}</div>; }
function Home() { const { data, error } = useResource<Snapshot>('/v1/4663/reflexive'); const latest = data?.events[0]; return <Shell><main className="reflexive-main">
  <section className="reflexive-hero"><p>INFOPUNKS // REFLEXIVE RADAR</p><h1>STOCK TOKENS<br />ARE BECOMING MONEY.</h1><div><span>Robinhood Chain is creating markets where internet-native assets trade directly against real-world equity exposure.</span><span>Radar measures what happens when attention, liquidity and tokenized assets collide.</span></div><a className="reflexive-cta" href="#pairs">VIEW EVIDENCE <b>↓</b></a></section>
  {error && <State text={`MARKET OBSERVATIONS UNAVAILABLE · ${error}`} />}{!data && !error && <State text="LOADING VERIFIED MARKET OBSERVATIONS…" />}
  {data && <>
    <section className="reflexive-numbers" aria-label="Live category numbers"><Fact label="ACTIVE MISSION PAIRS" value={String(data.pairs.filter((item) => item.canonicality === 'verified').length)} sub="VERIFIED ONLY" /><Fact label="24H STOCK-QUOTE VOLUME" value="UNAVAILABLE" sub="NO DEFENSIBLE AGGREGATE YET" /><Fact label="TOP QUOTE STOCK" value={topStock(data) ?? 'UNAVAILABLE'} sub="BY VERIFIED PAIR COUNT" /><Fact label="STOCK-LINKED VOLUME SHARE" value="UNAVAILABLE" sub="DENOMINATOR PENDING" /></section>
    <section className="reflexive-event"><p>LATEST REFLEXIVITY EVENT</p>{latest ? <><h2>{latest.event_type.replaceAll('_', ' ')}</h2><span>{latest.trigger}</span><time>{time(latest.occurred_at)}</time></> : <><h2>NO EVENT HAS QUALIFIED.</h2><span>Radar records evidence, not promotional alerts.</span></>}</section>
    <section id="pairs" className="reflexive-section"><div className="reflexive-section-head"><p>VERIFIED MARKETS</p><h2>MISSION PAIRS</h2><span>Pairs require an exact canonical Robinhood contract match. A ticker alone does not qualify.</span></div><div className="reflexive-table"><div className="reflexive-table-head"><span>PAIR</span><span>MISSION ALPHA</span><span>QUOTE ABSORPTION</span><span>STOCK BASIS</span><span>24H VOLUME</span><span>STATUS</span></div>{data.pairs.length ? data.pairs.map((pair) => <PairRow key={pair.pair_id} pair={pair} asset={data.assets.find((asset) => asset.asset_id === pair.stock_asset_id)} observation={latestObservation(data.observations, pair.pair_id)} />) : <State text="NO VERIFIED STOCK-PAIRED MARKETS YET. DISCOVERY REMAINS FAIL-CLOSED." />}</div></section>
    <section className="reflexive-section reflexive-stocks"><div className="reflexive-section-head"><p>QUOTE ECONOMIES</p><h2>STOCK AS MONEY</h2><span>Gross Stock-touching volume, attributable inventory and supply change remain separate measures.</span></div><div className="reflexive-stock-grid">{data.assets.filter((asset) => data.pairs.some((pair) => pair.stock_asset_id === asset.asset_id)).map((asset) => <a href={`/4663/reflexive/stock/${asset.ticker}`} key={asset.asset_id}><p>{asset.ticker}</p><strong>{data.pairs.filter((pair) => pair.stock_asset_id === asset.asset_id).length} TRACKED MARKETS</strong><span>CANONICAL TOKEN · VERIFIED</span></a>)}{!data.assets.some((asset) => data.pairs.some((pair) => pair.stock_asset_id === asset.asset_id)) && <State text="QUOTE ECONOMIES APPEAR ONLY AFTER PAIR VERIFICATION." />}</div></section>
    <section className="reflexive-section"><div className="reflexive-section-head"><p>RMM THESIS BOARD</p><h2>THE RECORD CAN DISAGREE.</h2><span>No LLM changes a thesis state. These are deterministic evidence states.</span></div><div className="reflexive-thesis-grid">{data.thesis.map((item) => <article key={item.hypothesis_id}><p>{item.hypothesis_id}</p><b className={`state-${item.state}`}>{item.state.replace('_', ' ')}</b><span>{item.rationale}</span></article>)}</div></section>
    <footer className="reflexive-footer">REFRESHED {time(data.refreshed_at)} · {data.assets.length} CANONICAL ASSETS · METHODOLOGY RMM-V0.3.0<br />ATTENTION IS A SIGNAL. LIQUIDITY IS AN OUTCOME. SURVIVAL IS THE TEST.</footer>
  </>}</main></Shell>; }
function PairRow({ pair, asset, observation }: { pair: Pair; asset?: Asset; observation?: Observation }) { return <a className="reflexive-table-row" href={`/4663/reflexive/pair/${pair.pair_id}`}><span><b>{pair.mission_symbol} / {asset?.ticker ?? 'UNKNOWN'}</b><i>{pair.venue}</i></span><span>UNAVAILABLE</span><span>{observation?.quote_inventory_share_equivalent ?? 'UNAVAILABLE'}</span><span>UNAVAILABLE</span><span>{money(observation?.volume_24h_usd)}</span><span><i>CANONICAL<br />VERIFIED</i></span></a>; }
function PairDossier({ pairId }: { pairId: string }) { const { data, error } = useResource<{ pair: Pair; observations: Observation[]; inventory: Inventory; events: Array<{ event_type: string; occurred_at: string; trigger: string }> }>(`/v1/4663/reflexive/pairs/${encodeURIComponent(pairId)}`); const snapshot = useResource<Snapshot>('/v1/4663/reflexive'); const pair = data?.pair; const stock = snapshot.data?.assets.find((asset) => asset.asset_id === pair?.stock_asset_id); const latest = data?.observations.at(-1); const inventory = data?.inventory; return <Shell><main className="reflexive-main reflexive-dossier">{error && <State text={error} />}{pair && <><a className="reflexive-back" href="/4663/reflexive">← REFLEXIVE RADAR</a><p>MISSION PAIR DOSSIER</p><h1>{pair.mission_symbol} / {stock?.ticker ?? 'STOCK'}</h1><div className="reflexive-dossier-grid"><Fact label="MISSION ALPHA" value="UNAVAILABLE" sub="COMPLETE WINDOW REQUIRED" /><Fact label="PAIR LOCKED ABSORPTION" value={inventory?.absorption_pct ? `${inventory.absorption_pct}%` : 'UNAVAILABLE'} sub="CANONICAL LOCKED POSITION ONLY" /><Fact label="STOCK BASIS" value="UNAVAILABLE" sub="ALIGNED QUOTES REQUIRED" /><Fact label="24H VOLUME" value={money(latest?.volume_24h_usd)} sub={latest?.fresh ? 'FRESH OBSERVATION' : 'UNAVAILABLE'} /></div><section className="reflexive-truth"><p>QUOTE INVENTORY</p><h2>{inventory?.status === 'AVAILABLE' ? `${inventory.stock_principal_units} ${stock?.ticker} IN THE CANONICAL LOCKED POSITION` : 'CANONICAL LOCKED POSITION INVENTORY UNAVAILABLE'}</h2><span>{inventory?.status === 'AVAILABLE' ? `SHARE EQUIVALENT ${inventory.stock_share_equivalent_units} · ${inventory.range_state} · BLOCK ${inventory.observed_block}` : inventory?.reason ?? 'POSITION EVIDENCE REQUIRED'}</span></section><section className="reflexive-truth"><p>EXPOSURE TRUTH</p><dl><div><dt>QUOTED IN {stock?.ticker ?? 'STOCK'}</dt><dd>YES</dd></div><div><dt>BACKED BY {stock?.ticker ?? 'STOCK'}</dt><dd>UNKNOWN</dd></div><div><dt>REDEEMABLE AT FIXED NAV</dt><dd>UNKNOWN</dd></div><div><dt>CANONICAL STOCK TOKEN USED</dt><dd>YES</dd></div><div><dt>LEGAL OWNERSHIP OF UNDERLYING SHARES</dt><dd>NO</dd></div></dl></section><Evidence title="EVIDENCE" entries={[...pair.evidence, ...(latest?.provenance ?? [])]} /><section className="reflexive-section"><div className="reflexive-section-head"><p>LIFECYCLE</p><h2>MARKET MEMORY</h2><span>Missing checkpoints stay missing. Historical observations never mutate.</span></div>{data.observations.length ? <div className="reflexive-observations">{data.observations.map((observation) => <article key={observation.observed_at}><b>{time(observation.observed_at)}</b><span>LIQUIDITY {money(observation.liquidity_usd)} · VOLUME {money(observation.volume_24h_usd)}</span><small>{observation.inventory_method}</small></article>)}</div> : <State text="NO LIFECYCLE OBSERVATIONS YET." />}</section></>}</main></Shell>; }
function StockDossier({ symbol }: { symbol: string }) { const { data, error } = useResource<{ asset: Asset; pairs: Pair[]; observations: Observation[]; tracked_position_inventory: string | null; tracked_absorption_pct: string | null; verified_position_count: number; aggregation_status: string; supply_events: Array<{ event_type: string; timestamp: string; share_equivalent_amount: string | null }>; net_quote_demand: string }>(`/v1/4663/reflexive/stocks/${encodeURIComponent(symbol)}`); return <Shell><main className="reflexive-main reflexive-dossier">{error && <State text={error} />}{data && <><a className="reflexive-back" href="/4663/reflexive">← REFLEXIVE RADAR</a><p>QUOTE ECONOMY DOSSIER</p><h1>{data.asset.ticker} IS MONEY?</h1><div className="reflexive-dossier-grid"><Fact label="CANONICAL TOKEN" value="VERIFIED" sub={short(data.asset.canonical_contract)} /><Fact label="TRACKED PAIR POSITIONS" value={String(data.verified_position_count)} sub="VERIFIED LOCKED ONLY" /><Fact label="MISSION PAIRS" value={String(data.pairs.length)} sub="VERIFIED ONLY" /><Fact label="TRACKED LOCKED INVENTORY" value={data.tracked_position_inventory ?? 'UNAVAILABLE'} sub="PAIR POSITIONS ONLY" /></div><section className="reflexive-truth"><p>{data.asset.ticker} AS QUOTE ASSET</p><h2>{data.pairs.length ? `${data.asset.ticker} IS CURRENTLY USED BY ${data.pairs.length} TRACKED MISSION MARKET${data.pairs.length === 1 ? '' : 'S'}.` : 'NO VERIFIED MISSION MARKET IS CURRENTLY ATTRIBUTED.'}</h2><span>TRACKED PAIR LOCKED ABSORPTION: {data.tracked_absorption_pct ? `${data.tracked_absorption_pct}%` : 'UNAVAILABLE'} · {data.aggregation_status.replaceAll('_', ' ')}</span><span>NET QUOTE DEMAND: {data.net_quote_demand.replaceAll('_', ' ')}</span></section><section className="reflexive-section"><div className="reflexive-section-head"><p>RECENT SUPPLY</p><h2>MINT / BURN EVENTS</h2></div>{data.supply_events.length ? <div className="reflexive-observations">{data.supply_events.map((event) => <article key={event.timestamp}><b>{event.event_type.toUpperCase()}</b><span>{event.share_equivalent_amount ?? 'UNAVAILABLE'} SHARE-EQUIVALENT UNITS</span><small>{time(event.timestamp)}</small></article>)}</div> : <State text="NO CANONICAL SUPPLY EVENTS HAVE BEEN PERSISTED." />}</section></>}</main></Shell>; }
function Evidence({ title, entries }: { title: string; entries: Array<{ href: string; source: string; observed_at?: string; note: string }> }) { return <section className="reflexive-evidence"><p>{title}</p>{entries.length ? entries.map((entry, index) => <a key={`${entry.href}-${index}`} href={entry.href} target="_blank" rel="noreferrer"><b>{entry.source}</b><span>{entry.note}</span></a>) : <State text="NO SOURCE-SPECIFIC EVIDENCE PERSISTED." />}</section>; }
function Fact({ label, value, sub }: { label: string; value: string; sub: string }) { return <article className="reflexive-fact"><p>{label}</p><strong>{value}</strong><span>{sub}</span></article>; }
function State({ text }: { text: string }) { return <div className="reflexive-state">{text}</div>; }
function latestObservation(items: Observation[], pairId: string) { return items.filter((item) => item.pair_id === pairId).sort((a, b) => b.observed_at.localeCompare(a.observed_at))[0]; }
function topStock(data: Snapshot) { const counts = new Map<string, number>(); for (const pair of data.pairs) counts.set(pair.stock_asset_id, (counts.get(pair.stock_asset_id) ?? 0) + 1); const id = [...counts].sort((a, b) => b[1] - a[1])[0]?.[0]; return data.assets.find((asset) => asset.asset_id === id)?.ticker ?? null; }
function short(value: string) { return `${value.slice(0, 7)}…${value.slice(-4)}`; }
