import React, { useEffect, useState } from 'react';
import { fetchRhChain, RhChainHero, type RhChainEnvelope, RhChainRouteState, RhChainSuiteNav } from './rhChainUi';

type Layer = { layer: string; volume_24h: number | null; percentage: number | null; label: string; caveat: string };
type Structure = {
  title: string; statement: string; market_pulse: { chain_volume_24h: number | null; observed_transaction_count: number | null; tracked_dexes: string[]; tracked_pair_count: number; classified_market_coverage: number | null; unclassified_market_coverage: number | null; observed_at: string; source_notes: string[]; freshness: string; methodology_caveat: string };
  market_composition: Layer[]; layer_leaders: Array<{ layer: string; assets: Array<{ contract: string; ticker: string | null; display_name: string | null; dexscreener_pair: string | null; canonical_pair: { dex: string | null; quote_token: string | null; volume_24h: number | null } | null; classification_confidence: string; classification_source: string; evidence_state: string; caveat: string | null }> }>;
  observed_coverage: { tracked_exact_contracts: number; classified_exact_contracts: number; canonical_pair_only: boolean }; latest_related_receipts: Array<{ receipt_id: string; timestamp: string; summary: string }>;
};
type CrossLayer = { title: string; entries: Array<{ category: string; contract: string; display_name: string | null; dexscreener_pair: string | null; primary_layer: string; secondary_layers: string[]; explanation: string; evidence_state: string; attention_quality_state: string; missing_evidence: string[]; caveat: string | null }>; categories: string[]; observed_at: string };
type Attention = { title: string; observations: Array<{ contract: string; boost_amount: number | null; total_boost_amount: number | null; paid_order_types: string[]; observed_at: string; pair_metrics: { dexId: string | null; volume: { h24: number | null }; liquidityUsd: number | null } | null }>; attention_quality: Array<{ contract: string; state: string; score: number | null; caveats: string[] }> };
type AttentionHistory = { contract: string; latest_snapshot_at: string | null; snapshot_count: number; paid_attention_context: { active_boosts: number; paid_order_types: string[]; paid_order_statuses: string[] } | null; state: string; score: number | null; caveats: string[] };
type View = 'main' | 'cross-layer' | 'attention-quality';

const fmt = (value: number | null) => value === null ? 'Source required' : new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 }).format(value);

export function RhChainMarketStructurePage({ view = 'main' }: { view?: View }) {
  const path = view === 'cross-layer' ? '/v1/rh-chain/market-structure/cross-layer' : view === 'attention-quality' ? '/v1/rh-chain/market-structure/attention-quality' : '/v1/rh-chain/market-structure';
  const [envelope, setEnvelope] = useState<RhChainEnvelope<Structure | CrossLayer | Attention> | null>(null);
  const [error, setError] = useState<string | null>(null);
  const load = () => { setError(null); return fetchRhChain<Structure | CrossLayer | Attention>(path).then(setEnvelope).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'market_structure_unavailable')); };
  useEffect(() => { document.title = view === 'main' ? '4663 Market Structure | Infopunks' : view === 'cross-layer' ? 'Cross-Layer Assets | Infopunks' : 'Paid Attention Watch | Infopunks'; void load(); }, [path]);
  const data = envelope?.data;
  return <div className="shell narrative-shell rh-chain-shell market-structure-shell"><a className="skip-link" href="#market-structure-content">Skip to market structure</a><header className="site-header"><RhChainSuiteNav current="/rh-chain-signal-desk/market-structure" /></header><main id="market-structure-content" className="narrative-page rh-chain-page market-structure-page">
    {error && <RhChainRouteState state="unavailable" detail={error} onRetry={() => void load()} />}
    {!data && !error && <RhChainRouteState state="loading" />}
    {data && envelope && <>{view === 'main' && <StructureView payload={data as Structure} envelope={envelope as RhChainEnvelope<Structure>} />}{view === 'cross-layer' && <CrossLayerView payload={data as CrossLayer} envelope={envelope as RhChainEnvelope<CrossLayer>} />}{view === 'attention-quality' && <AttentionView payload={data as Attention} envelope={envelope as RhChainEnvelope<Attention>} />}</>}
  </main></div>;
}

function StructureView({ payload, envelope }: { payload: Structure; envelope: RhChainEnvelope<Structure> }) { return <>
  <RhChainHero eyebrow="RH Chain Signal Desk" title="4663 Market Structure" copy={payload.statement} line="Exact contract. Canonical pair. Reviewed judgment." envelope={envelope} doctrine="Provider data is context only. Infopunks classifications are review-gated." disclaimer="No trading, launch, or endorsement flow. Provider observations never alter reviewed classifications." primaryCta={{ href: '#market-composition', label: 'Read composition' }} secondaryCta={{ href: '/rh-chain-signal-desk/market-structure/attention-quality', label: 'Open attention watch' }} />
  <section id="market-composition" className="meme-pulse-section"><Head kicker="Market composition" title="Observed coverage, not a complete market claim" /><div className="meme-pulse-snapshot-grid">{[['Chain volume (24h)', fmt(payload.market_pulse.chain_volume_24h)], ['Observed transactions', fmt(payload.market_pulse.observed_transaction_count)], ['Tracked canonical pairs', String(payload.market_pulse.tracked_pair_count)], ['Classified coverage', payload.market_pulse.classified_market_coverage === null ? 'Source required' : `${payload.market_pulse.classified_market_coverage}%`]].map(([label, value]) => <article className="meme-pulse-snapshot" key={label}><p>{label}</p><strong>{value}</strong></article>)}</div><p className="rh-chain-disclaimer">{payload.market_pulse.methodology_caveat}</p></section>
  <section className="meme-pulse-section"><Head kicker="Layer leaders" title="Canonical pair context" action="/v1/rh-chain/market-structure" /><div className="meme-pulse-assets">{payload.layer_leaders.map((group) => <article className="meme-pulse-asset" key={group.layer}><p className="section-kicker">{group.layer}</p><h3>{group.assets.length ? `${group.assets.length} observed assets` : 'No reviewed coverage'}</h3>{group.assets.map((asset) => <p key={asset.contract}>{asset.display_name && <><strong>{asset.display_name}</strong> · </>}<code>{asset.contract}</code> · {asset.canonical_pair?.dex ?? (asset.dexscreener_pair ? 'Reviewed pair link' : 'Pair source required')} · {fmt(asset.canonical_pair?.volume_24h ?? null)} 24h volume · {asset.dexscreener_pair && <a href={asset.dexscreener_pair} target="_blank" rel="noreferrer">DexScreener pair</a>} · <span className="meme-pulse-risk risk-source_required">{asset.classification_source === 'manual_review' ? 'reviewed intake' : 'auto-observed'} · {asset.evidence_state} · {asset.classification_confidence}</span>{asset.caveat && <> · <small>{asset.caveat}</small></>}</p>)}</article>)}</div></section>
  <section className="meme-pulse-section"><Head kicker="Cross-layer assets" title="More than one structural layer" /><p><a className="execute compact secondary" href="/rh-chain-signal-desk/market-structure/cross-layer">Open exact-contract cross-layer record</a></p></section>
  <section className="meme-pulse-section"><Head kicker="Paid Attention Watch" title="Visibility is context, not conviction" /><p><a className="execute compact secondary" href="/rh-chain-signal-desk/market-structure/attention-quality">Inspect documented boost and order observations</a></p></section>
  <section className="meme-pulse-section"><Head kicker="Methodology and coverage" title="Source policy" /><p>Tracked DEXes: {payload.market_pulse.tracked_dexes.join(', ') || 'Source required'} · observed {payload.market_pulse.observed_at} · freshness: {payload.market_pulse.freshness}.</p>{payload.market_pulse.source_notes.map((note) => <p className="rh-chain-disclaimer" key={note}>{note}</p>)}</section>
  <section className="meme-pulse-section"><Head kicker="Latest related receipts" title="Memory before momentum" />{payload.latest_related_receipts.length ? payload.latest_related_receipts.map((receipt) => <article className="meme-pulse-asset" key={receipt.receipt_id}><h3>{receipt.receipt_id}</h3><p>{receipt.summary}</p><small>{receipt.timestamp}</small></article>) : <RhChainRouteState state="source_required" detail="No related reviewed receipt is available for this market view." />}</section>
</>; }
function CrossLayerView({ payload, envelope }: { payload: CrossLayer; envelope: RhChainEnvelope<CrossLayer> }) { return <><RhChainHero eyebrow="4663 Market Structure" title="Cross-Layer Assets" copy="Structural overlap is review-gated and exact-contract only." envelope={envelope} disclaimer="Provider observations cannot create a cross-layer classification." primaryCta={{ href: '#cross-layer-assets', label: 'Read entries' }} secondaryCta={{ href: '/rh-chain-signal-desk/market-structure', label: 'Market structure' }} /><section id="cross-layer-assets" className="meme-pulse-section"><Head kicker="Cross-layer assets" title="Reviewed intersections" />{payload.entries.length ? <div className="meme-pulse-assets">{payload.entries.map((entry) => <article className="meme-pulse-asset" key={entry.contract}><p className="section-kicker">{crossLayerLabel(entry.category)}</p><h3>{entry.display_name ?? <code>{entry.contract}</code>}</h3><p><code>{entry.contract}</code>{entry.dexscreener_pair && <> · <a href={entry.dexscreener_pair} target="_blank" rel="noreferrer">DexScreener pair</a></>}</p><p>{entry.primary_layer} · {entry.secondary_layers.join(' · ')}</p><p>{entry.explanation}</p><p>Attention quality: {entry.attention_quality_state} · Evidence: {entry.evidence_state}</p>{entry.caveat && <p className="rh-chain-disclaimer">{entry.caveat}</p>}{entry.missing_evidence.map((item) => <small key={item}>{item}</small>)}</article>)}</div> : <RhChainRouteState state="source_required" detail="No exact-contract reviewed cross-layer classifications are available." />}</section></>; }
function AttentionView({ payload, envelope }: { payload: Attention; envelope: RhChainEnvelope<Attention> }) {
  const [history, setHistory] = useState<Record<string, AttentionHistory>>({});
  useEffect(() => { void Promise.all(payload.observations.map((item) => fetchRhChain<AttentionHistory>(`/v1/rh-chain/market/attention-quality/${encodeURIComponent(item.contract)}`).then((response) => [item.contract, response.data] as const).catch(() => null))).then((results) => setHistory(Object.fromEntries(results.filter((result): result is readonly [string, AttentionHistory] => Boolean(result))))); }, [payload.observations]);
  return <><RhChainHero eyebrow="4663 Market Structure" title="Paid Attention Watch" copy="Paid visibility is observed without being mistaken for organic conviction." envelope={envelope} disclaimer="A paid boost is not misconduct. A boost rank is not organic demand." primaryCta={{ href: '#paid-attention', label: 'Read observations' }} secondaryCta={{ href: '/rh-chain-signal-desk/market-structure', label: 'Market structure' }} /><section id="paid-attention" className="meme-pulse-section"><Head kicker="Documented API observations" title="Boosts, orders, pair context" />{payload.observations.length ? <div className="meme-pulse-assets">{payload.observations.map((item) => <article className="meme-pulse-asset" key={item.contract}><h3><code>{item.contract}</code></h3><p>Boost: {fmt(item.boost_amount)} · Total boost: {fmt(item.total_boost_amount)}</p><p>Paid order types: {item.paid_order_types.join(', ') || 'None observed'}</p><p>Canonical pair: {item.pair_metrics?.dexId ?? 'Source required'} · volume {fmt(item.pair_metrics?.volume.h24 ?? null)} · liquidity {fmt(item.pair_metrics?.liquidityUsd ?? null)}</p><small>{item.observed_at}</small></article>)}</div> : <RhChainRouteState state="source_required" detail="No current paid-attention observation is available from the public API." />}</section><section className="meme-pulse-section"><Head kicker="Attention quality" title="History-gated, never inferred" />{payload.observations.map((item) => <AttentionHistoryCard key={item.contract} fallback={payload.attention_quality.find((quality) => quality.contract === item.contract)} history={history[item.contract]} contract={item.contract} />)}</section></>;
}
function AttentionHistoryCard({ contract, history, fallback }: { contract: string; history?: AttentionHistory; fallback?: Attention['attention_quality'][number] }) { const value = history ?? fallback; return <article className="meme-pulse-asset"><h3><code>{contract}</code></h3><p>Latest snapshot: {history?.latest_snapshot_at ?? 'Source required'} · snapshots: {history?.snapshot_count ?? 0}</p><p>State: {value?.state ?? 'source_required'} · score {value?.score ?? 'Insufficient history'}</p>{history?.paid_attention_context && <p>Paid attention context: {history.paid_attention_context.active_boosts} active boosts · {history.paid_attention_context.paid_order_types.join(', ') || 'no paid order type observed'}</p>}{value?.caveats.map((caveat) => <small key={caveat}>{caveat}</small>)}</article>; }
function Head({ kicker, title, action }: { kicker: string; title: string; action?: string }) { return <div className="rh-chain-section-head"><div><p className="section-kicker">{kicker}</p><h2>{title}</h2></div>{action && <a className="methodology-trigger" href={action}>JSON</a>}</div>; }
function crossLayerLabel(category: string) { return category === 'meme_x_ai_narrative' ? 'Meme × AI Narrative (agent activity unverified)' : category.replaceAll('_', ' × '); }
