import React, { useEffect, useState } from 'react';
import type { RhChainTokenDossier } from '../data/rhChain';
import { fetchRhChain, RhChainHero, type RhChainEnvelope, RhChainRouteState, RhChainSuiteNav } from './rhChainUi';
import { RhChainPortableCard } from './rhChainPortableCard';

const short = (value: string) => value.length > 18 ? `${value.slice(0, 10)}…${value.slice(-6)}` : value;
const label = (value: string) => value.replaceAll('_', ' ');

export function RhChainTokenDossierPage({ contract }: { contract: string }) {
  const [envelope, setEnvelope] = useState<RhChainEnvelope<RhChainTokenDossier> | null>(null);
  const [error, setError] = useState<string | null>(null);
  const load = () => {
    setError(null);
    return fetchRhChain<RhChainTokenDossier>(`/v1/rh-chain/tokens/${encodeURIComponent(contract)}/dossier`)
      .then(setEnvelope).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'token_dossier_unavailable'));
  };
  useEffect(() => {
    document.title = 'RH Chain Token Dossier | Infopunks';
    setEnvelope(null);
    void load();
  }, [contract]);
  const dossier = envelope?.data ?? null;
  const copyLink = () => void navigator.clipboard?.writeText(window.location.href);
  return <div className="shell narrative-shell rh-chain-shell dossier-shell"><a className="skip-link" href="#dossier-content">Skip to content</a>
    <header className="site-header"><RhChainSuiteNav current="" /></header>
    <main id="dossier-content" className="narrative-page rh-chain-page dossier-page">{error && <RhChainRouteState state="unavailable" detail={error} onRetry={() => void load()} />}{!dossier && !error && <RhChainRouteState state="loading" />}{dossier && envelope && <>
      {dossier.identity_status === 'source_required' && <RhChainRouteState state="source_required" detail="This route will not aggregate placeholder contracts or infer identity from provider context." />}
      <RhChainHero eyebrow="RH Chain token dossier" title={<>{dossier.ticker ?? 'Unknown token'}{dossier.name ? <span> / {dossier.name}</span> : ''}</>} copy="A calm, exact-contract intelligence file. Unknown stays unknown." line={short(dossier.contract)} envelope={envelope} doctrine={dossier.doctrine} disclaimer={dossier.disclaimer} primaryCta={{ href: '#dossier-memory', label: 'Read desk memory' }} secondaryCta={{ href: '/rh-chain-signal-desk/submit', label: 'Add source evidence' }} />
      <section className="rh-chain-portable-card-wrap" aria-label="Token Dossier Card"><RhChainPortableCard type="Token Dossier Card" label={`${dossier.ticker ?? 'Unknown'} · exact contract`} finding={dossier.memory.campaign_asset?.classification_note ?? dossier.memory.index?.infopunks_verdict ?? dossier.memory.scout_summary} caveat={dossier.risk_notes[0] ?? 'No exact contract match is a source-required state, not a positive signal.'} timestamp={dossier.generated_at} reference={dossier.memory.campaign_asset ? '100 Receipts · Day 1' : dossier.memory.index?.source.source_name ?? dossier.memory.review_items[0]?.source.source_name ?? 'Token Dossier memory'} deskHref={`/rh-chain-signal-desk/tokens/${encodeURIComponent(dossier.contract)}`} /></section>
      <section id="dossier-memory" className="dossier-section"><div className="rh-chain-section-head"><div><p className="section-kicker">Infopunks Memory</p><h2>What the desk remembers</h2></div></div><div className="dossier-memory-grid"><article><p className="section-kicker">4663 Index context</p><h3>{dossier.memory.index ? `${dossier.memory.index.signal_score} signal score` : dossier.memory.campaign_asset ? 'Reviewed campaign memory' : 'Not indexed'}</h3><p>{dossier.memory.index?.infopunks_verdict ?? dossier.memory.campaign_asset?.classification_note ?? 'No exact contract match is in the public index. Dossiers never add a token to the index.'}</p></article><article><p className="section-kicker">Scout retrieval</p><h3>Read-only desk context</h3><p>{dossier.memory.scout_summary}</p></article></div>{dossier.memory.review_items.map((item) => <article className="dossier-record" key={item.review_id}><p className="section-kicker">Review Queue · {label(item.review_state)}</p><h3>{item.ticker}</h3><p>{item.evidence_summary}</p><p className="panel-caption">Missing: {item.missing_evidence.join(' · ')}</p></article>)}</section>
      {dossier.memory.campaign_asset && <section className="dossier-section campaign-dossier-memory" aria-label="100 Receipts campaign memory"><div className="rh-chain-section-head"><div><p className="section-kicker">100 Receipts · Day 1</p><h2>Reviewed campaign record</h2></div><a className="execute compact secondary" href="/rh-chain-signal-desk/100-receipts">Open campaign</a></div><div className="dossier-launch-grid">{[['Evidence state', dossier.memory.campaign_asset.evidence_state], ['Classification', dossier.memory.campaign_asset.classification], ['Risk state', dossier.memory.campaign_asset.risk_state], ['Launch surface', dossier.memory.campaign_asset.launch_surface], ['Reviewed at', dossier.memory.campaign_asset.reviewed_at], ['Outcome check due', dossier.memory.campaign_asset.outcome_check_due_at], ['Seven-day outcome', dossier.memory.campaign_asset.seven_day_outcome], ['Attribution', dossier.memory.campaign_asset.attribution]].map(([key, value]) => <p key={key}><span>{key}</span><strong>{label(value)}</strong></p>)}</div><p>{dossier.memory.campaign_asset.classification_note}</p><div className="campaign-outcome-check"><p className="section-kicker">7-day outcome check</p><ul>{dossier.memory.campaign_asset.outcome_check_questions.map((question) => <li key={question}>{question}</li>)}</ul></div><p className="panel-caption"><b>Missing evidence:</b> {dossier.memory.campaign_asset.missing_evidence.join(' · ')}</p><div className="campaign-source-links">{dossier.memory.campaign_asset.source_links.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.label}</a>)}</div></section>}
      <section className="dossier-section"><div className="rh-chain-section-head"><div><p className="section-kicker">External Context</p><h2>Provider context, never a verdict</h2></div></div><div className="dossier-context-grid"><Context title="DexScreener pair" value={dossier.external_context.token_pair?.pair_address ?? 'Unavailable'} note={dossier.external_context.token_pair ? `Chain ${dossier.external_context.token_pair.chain_match_status.replaceAll('_', ' ')} · liquidity ${dossier.external_context.token_pair.liquidity_usd ?? 'unknown'} · 24h volume ${dossier.external_context.token_pair.volume_24h_usd ?? 'unknown'} · ${dossier.external_context.token_pair.freshness}` : 'No pair context returned.'} href={dossier.external_context.token_pair?.dex_url ?? null} /><Context title="Blockscout explorer" value={dossier.external_context.explorer?.availability === 'unavailable' ? 'Verification unavailable' : dossier.external_context.explorer?.contract_verified ? 'Verified source' : 'Unverified'} note={`Contract ${dossier.external_context.explorer?.contract_exists === null ? 'unknown' : dossier.external_context.explorer?.contract_exists ? 'found' : 'not found'} · type ${dossier.external_context.explorer?.contract_type ?? 'unknown'} · deployer ${dossier.external_context.explorer?.deployer_address ?? 'unknown'} · ${dossier.external_context.explorer?.freshness ?? 'unavailable'}`} href={dossier.external_context.explorer?.explorer_url ?? null} /><Context title="CoinGecko relevance" value={dossier.external_context.category_relevance.freshness} note={dossier.external_context.category_relevance.label} href={null} /></div></section>
      <section className="dossier-section"><div className="rh-chain-section-head"><div><p className="section-kicker">Launch Context</p><h2>Claims stay claims until receipted</h2></div></div>{dossier.launch_context ? <div className="dossier-launch-grid">{[['Launch source', dossier.launch_context.launch_source], ['Pair', dossier.launch_context.pair_address ?? 'unknown'], ['Deployer', dossier.launch_context.deployer_address ?? 'unknown'], ['LP status claim', dossier.launch_context.lp_status], ['Contract verified', String(dossier.launch_context.contract_verified)], ['Confidence', dossier.launch_context.confidence_level]].map(([key, value]) => <p key={key}><span>{key}</span><strong>{label(value)}</strong></p>)}</div> : <p className="dossier-empty">No launch context is attached to this exact contract record.</p>}</section>
      <section className="dossier-section"><div className="rh-chain-section-head"><div><p className="section-kicker">Risk Notes</p><h2>Evidence gaps remain visible</h2></div></div><div className="dossier-risk-list">{dossier.risk_notes.map((note) => <p key={note}>{note}</p>)}</div></section>
      <section className="dossier-section"><div className="rh-chain-section-head"><div><p className="section-kicker">Receipt Trail</p><h2>Public memory, timestamped</h2></div></div>{dossier.receipt_trail.length ? <div className="dossier-trail">{dossier.receipt_trail.map((item) => <a key={item.id} href={item.href ?? undefined}><span>{item.label}</span><time>{item.timestamp}</time></a>)}</div> : <p className="dossier-empty">No receipt, review update, or safely exposed audit event is attached to this exact contract.</p>}</section>
      <section className="panel dossier-cta"><p className="section-kicker">Improve the record</p><h2>Evidence before narrative.</h2><div className="panel-actions"><a className="execute" href="/rh-chain-signal-desk/submit">Submit more evidence</a><button className="execute compact secondary" onClick={copyLink}>Share Token Dossier</button><a className="execute compact secondary" href="/rh-chain-signal-desk/distribution-pack">Open Distribution Pack</a></div></section>
    </>}</main></div>;
}

function Context({ title, value, note, href }: { title: string; value: string; note: string; href: string | null }) { return <article><p className="section-kicker">{title}</p><h3>{href ? <a href={href} target="_blank" rel="noreferrer">{value}</a> : value}</h3><p>{note}</p></article>; }
