import React, { useEffect, useState } from 'react';
import type { RhChainTokenDossier } from '../data/rhChain';
import { getApiBaseUrl, toApiUrl } from './apiBaseUrl';

const API_BASE_URL = getApiBaseUrl();
const short = (value: string) => value.length > 18 ? `${value.slice(0, 10)}…${value.slice(-6)}` : value;
const label = (value: string) => value.replaceAll('_', ' ');

export function RhChainTokenDossierPage({ contract }: { contract: string }) {
  const [dossier, setDossier] = useState<RhChainTokenDossier | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    document.title = 'RH Chain Token Dossier | Infopunks';
    fetch(toApiUrl(API_BASE_URL, `/v1/rh-chain/tokens/${encodeURIComponent(contract)}/dossier`), { headers: { Accept: 'application/json' } })
      .then(async (response) => { if (!response.ok) throw new Error(`token_dossier ${response.status}`); return response.json() as Promise<{ data: RhChainTokenDossier }>; })
      .then(({ data }) => setDossier(data)).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'token_dossier_unavailable'));
  }, [contract]);
  const copyLink = () => void navigator.clipboard?.writeText(window.location.href);
  return <div className="shell narrative-shell rh-chain-shell dossier-shell"><a className="skip-link" href="#dossier-content">Skip to content</a>
    <header className="site-header"><nav className="global-toolbar narrative-toolbar" aria-label="RH Chain navigation"><a className="nav-brand" href="/"><span>Infopunks</span><strong>RH Chain</strong></a><div className="terminal-nav terminal-nav-scroll-rail"><a href="/rh-chain-signal-desk">Signal Desk</a><a href="/rh-chain-signal-desk/meme-pulse">Meme Pulse</a><a href="/rh-chain-signal-desk/review-queue">Review Queue</a><a href="/rh-chain-signal-desk/scout">Scout Agent</a></div></nav></header>
    <main id="dossier-content" className="narrative-page rh-chain-page dossier-page">{error && <section className="panel"><p className="route-state error">{error}</p></section>}{!dossier && !error && <section className="panel"><p className="route-state">Opening intelligence file…</p></section>}{dossier && <>
      <section className="panel hero rh-chain-hero dossier-hero"><div><p className="eyebrow">RH Chain token dossier</p><h1>{dossier.ticker ?? 'Unknown token'}{dossier.name ? <span> / {dossier.name}</span> : ''}</h1><p className="dossier-contract" title={dossier.contract}>{short(dossier.contract)}</p><div className="dossier-badges"><span>{dossier.chain}</span><span>{label(dossier.review_status)}</span><span className={`meme-pulse-risk risk-${dossier.risk_state}`}>{label(dossier.risk_state)}</span><span>{dossier.data_mode}</span></div></div><aside className="rh-chain-hero-rail"><p className="section-kicker">Dossier doctrine</p><p>{dossier.doctrine}</p><p className="rh-chain-disclaimer">{dossier.disclaimer}</p></aside></section>
      <section className="dossier-section"><div className="rh-chain-section-head"><div><p className="section-kicker">Infopunks Memory</p><h2>What the desk remembers</h2></div></div><div className="dossier-memory-grid"><article><p className="section-kicker">4663 Index</p><h3>{dossier.memory.index ? `${dossier.memory.index.signal_score} signal score` : 'Not indexed'}</h3><p>{dossier.memory.index?.infopunks_verdict ?? 'No exact contract match is in the public index. Dossiers never add a token to the index.'}</p></article><article><p className="section-kicker">Scout retrieval</p><h3>Read-only desk context</h3><p>{dossier.memory.scout_summary}</p></article></div>{dossier.memory.review_items.map((item) => <article className="dossier-record" key={item.review_id}><p className="section-kicker">Review Queue · {label(item.review_state)}</p><h3>{item.ticker}</h3><p>{item.evidence_summary}</p><p className="panel-caption">Missing: {item.missing_evidence.join(' · ')}</p></article>)}</section>
      <section className="dossier-section"><div className="rh-chain-section-head"><div><p className="section-kicker">External Context</p><h2>Provider context, never a verdict</h2></div></div><div className="dossier-context-grid"><Context title="DexScreener pair" value={dossier.external_context.token_pair?.pair_address ?? 'Unavailable'} note={dossier.external_context.token_pair ? `Liquidity ${dossier.external_context.token_pair.liquidity_usd ?? 'unknown'} · 24h volume ${dossier.external_context.token_pair.volume_24h_usd ?? 'unknown'} · ${dossier.external_context.token_pair.freshness}` : 'No pair context returned.'} href={dossier.external_context.token_pair?.dex_url ?? null} /><Context title="Blockscout explorer" value={dossier.external_context.explorer?.contract_verified === null ? 'Verification unknown' : String(dossier.external_context.explorer?.contract_verified ?? 'Unavailable')} note={`Deployer: ${dossier.external_context.explorer?.deployer_address ?? 'unknown'} · ${dossier.external_context.explorer?.freshness ?? 'unavailable'}`} href={dossier.external_context.explorer?.explorer_url ?? null} /><Context title="CoinGecko relevance" value={dossier.external_context.category_relevance.freshness} note={dossier.external_context.category_relevance.label} href={null} /></div></section>
      <section className="dossier-section"><div className="rh-chain-section-head"><div><p className="section-kicker">Launch Context</p><h2>Claims stay claims until receipted</h2></div></div>{dossier.launch_context ? <div className="dossier-launch-grid">{[['Launch source', dossier.launch_context.launch_source], ['Pair', dossier.launch_context.pair_address ?? 'unknown'], ['Deployer', dossier.launch_context.deployer_address ?? 'unknown'], ['LP status claim', dossier.launch_context.lp_status], ['Contract verified', String(dossier.launch_context.contract_verified)], ['Confidence', dossier.launch_context.confidence_level]].map(([key, value]) => <p key={key}><span>{key}</span><strong>{label(value)}</strong></p>)}</div> : <p className="dossier-empty">No launch context is attached to this exact contract record.</p>}</section>
      <section className="dossier-section"><div className="rh-chain-section-head"><div><p className="section-kicker">Risk Notes</p><h2>Evidence gaps remain visible</h2></div></div><div className="dossier-risk-list">{dossier.risk_notes.map((note) => <p key={note}>{note}</p>)}</div></section>
      <section className="dossier-section"><div className="rh-chain-section-head"><div><p className="section-kicker">Receipt Trail</p><h2>Public memory, timestamped</h2></div></div>{dossier.receipt_trail.length ? <div className="dossier-trail">{dossier.receipt_trail.map((item) => <a key={item.id} href={item.href ?? undefined}><span>{item.label}</span><time>{item.timestamp}</time></a>)}</div> : <p className="dossier-empty">No receipt, review update, or safely exposed audit event is attached to this exact contract.</p>}</section>
      <section className="panel dossier-cta"><p className="section-kicker">Improve the record</p><h2>Evidence before narrative.</h2><div className="panel-actions"><a className="execute" href="/rh-chain-signal-desk/submit">Submit more evidence</a><a className="execute compact secondary" href="/rh-chain-signal-desk/scout">Ask Scout</a><button className="execute compact secondary" onClick={copyLink}>Copy dossier link</button></div></section>
    </>}</main></div>;
}

function Context({ title, value, note, href }: { title: string; value: string; note: string; href: string | null }) { return <article><p className="section-kicker">{title}</p><h3>{href ? <a href={href} target="_blank" rel="noreferrer">{value}</a> : value}</h3><p>{note}</p></article>; }
